
/*
 * JDCierreCaja.java
 *
 * Created on 12/04/2010, 16:46:16
 */

package jgestion.gui;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author FiruzzZ
 */
public class JDCierreCaja extends javax.swing.JDialog {

    /** Creates new form JDCierreCaja */
    public JDCierreCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        labelCAJACERRADA.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        cbCaja = new javax.swing.JComboBox();
        dcApertura = new com.toedter.calendar.JDateChooser();
        dcCierre = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bCerrar = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        labelCAJACERRADA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimientos de Cajas");
        setMinimumSize(new java.awt.Dimension(625, 372));

        jLabel15.setText("Cajas");

        cbCaja.setName("caja"); // NOI18N

        dcApertura.setEnabled(false);

        jLabel16.setText("Fecha apertura");

        jLabel17.setText("Fecha cierre");

        jTable1.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane1.setViewportView(jTable1);

        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lock.png"))); // NOI18N
        bCerrar.setText("Cerrar");
        bCerrar.setName("cerrar"); // NOI18N

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/impresora.png"))); // NOI18N
        bImprimir.setText("Imprimir");
        bImprimir.setName("imprimir"); // NOI18N

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setToolTipText("Buscar Cajas Cerradas");
        bBuscar.setName("buscar"); // NOI18N

        labelCAJACERRADA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCAJACERRADA.setForeground(new java.awt.Color(255, 51, 51));
        labelCAJACERRADA.setText("CAJA CERRADA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bImprimir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCAJACERRADA)
                            .addComponent(bBuscar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dcCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCAJACERRADA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JComboBox cbCaja;
    private com.toedter.calendar.JDateChooser dcApertura;
    private com.toedter.calendar.JDateChooser dcCierre;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCAJACERRADA;
    // End of variables declaration//GEN-END:variables

   public void setListener(Object o) {
      cbCaja.addActionListener((ActionListener) o);
      bCerrar.addActionListener((ActionListener) o);
      bImprimir.addActionListener((ActionListener) o);
      bBuscar.addActionListener((ActionListener) o);
   }

   public JComboBox getCbCaja() {
      return cbCaja;
   }

   public Date getDcApertura() {
      return dcApertura.getDate();
   }

   public Date getFechaCierre() {
      return dcCierre.getDate();
   }

   public JTable getjTable1() {
      return jTable1;
   }

   public javax.swing.table.DefaultTableModel getDtm() {
      return (javax.swing.table.DefaultTableModel) jTable1.getModel();
   }

   public void setDcApertura(Date apertura) {
      dcApertura.setDate(apertura);
   }
   
   public void setDcCierre(Date cierre) {
      dcCierre.setDate(cierre);
   }

   /**
   * Setea un mensaje de información.
   * Si @param messageType < -1 || > 3 no hace NADA.
   * @param msg,.. mensaje.
   * @param titulo (puede tener título o no).
   * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
   */
   public void showMessage(String msg, String titulo, int messageType) {
      if(messageType >= -1 && messageType <= 2)
         javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, messageType);
      else
         javax.swing.JOptionPane.showMessageDialog(this, msg);
   }

   public JButton getbCerrar() {
      return bCerrar;
   }

   public JDateChooser getDcCierre() {
      return dcCierre;
   }

   public JLabel getLabelCAJACERRADA() {
      return labelCAJACERRADA;
   }

   public JButton getbBuscar() {
      return bBuscar;
   }

   public JButton getbImprimir() {
      return bImprimir;
   }

}
