/*
 * JDVenta.java
 *
 * Created on 25/11/2009, 18:46:25
 */
package jgestion.gui;

import jgestion.controller.Contabilidad;
import jgestion.controller.Valores;
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;
import jgestion.JGestionUtils;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;

/**
 *
 * @author Administrador
 */
public class JDFacturaVenta extends javax.swing.JDialog {

    private final int modoUso;
    private boolean viewMode;
    private boolean editMode;

    public JDFacturaVenta(Window parent, boolean modal, int factVenta1_Presup2_Remito3) {
        super(parent, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        modoUso = factVenta1_Presup2_Remito3;
        initComponents();
        labelObservacion.setVisible(false);
        tfObservacion.setVisible(false);
        btnAnular.setVisible(false); // <--- solo visible cuando se va ANULAR ALGO
        if (factVenta1_Presup2_Remito3 != 1) {
            btnAceptar.setText("Aceptar");
            btnAceptar.setMnemonic('a');
            btnFacturar.setVisible(false);
            labelCaja.setVisible(false);
            cbCaja.setVisible(false);
            //Presup y Remito no se los puede vincular con un Remito
            labelRemito.setVisible(false);
            tfRemito.setVisible(false);
            btnBuscarRemito.setVisible(false);
            labelUnidadNegocio.setVisible(false);
            cbUnidadDeNegocio.setVisible(false);
            labelCuenta.setVisible(false);
            cbCuenta.setVisible(false);
            labelSubCuenta.setVisible(false);
            cbSubCuenta.setVisible(false);
            //Rem no tienen FORMA DE PAGO
            if (factVenta1_Presup2_Remito3 == 2) {
                setTitle("Presupuesto");
                labelNumMovimiento.setVisible(false);
                tfNumMovimiento.setVisible(false);
                labelNumFactura.setVisible(false);
                tfFacturaCuarto.setVisible(false);
                tfFacturaOcteto.setVisible(false);
                labeFecha.setVisible(false);
                dcFechaFactura.setVisible(false);
            }
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosFacturacion = new javax.swing.JPanel();
        labelNumFactura = new javax.swing.JLabel();
        labeFecha = new javax.swing.JLabel();
        tfFacturaCuarto = new javax.swing.JTextField();
        tfFacturaOcteto = new javax.swing.JTextField();
        labelLetra = new javax.swing.JLabel();
        cbFacturaTipo = new javax.swing.JComboBox();
        cbCaja = new javax.swing.JComboBox();
        labelCaja = new javax.swing.JLabel();
        labelNumMovimiento = new javax.swing.JLabel();
        tfNumMovimiento = new javax.swing.JTextField();
        labelListaPrecios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        btnCliente = new javax.swing.JButton();
        cbListaPrecio = new javax.swing.JComboBox();
        dcFechaFactura = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cbSucursal = new javax.swing.JComboBox();
        labelFormaPago = new javax.swing.JLabel();
        cbFormaPago = new javax.swing.JComboBox();
        labelDias = new javax.swing.JLabel();
        tfDias = new javax.swing.JTextField();
        labelRemito = new javax.swing.JLabel();
        tfRemito = new javax.swing.JTextField();
        btnBuscarRemito = new javax.swing.JButton();
        labelListaPrecioParaCatalogo = new javax.swing.JLabel();
        tfObservacion = new javax.swing.JTextField();
        labelObservacion = new javax.swing.JLabel();
        labelUnidadNegocio = new javax.swing.JLabel();
        cbUnidadDeNegocio = new javax.swing.JComboBox();
        labelCuenta = new javax.swing.JLabel();
        cbCuenta = new javax.swing.JComboBox();
        labelSubCuenta = new javax.swing.JLabel();
        cbSubCuenta = new javax.swing.JComboBox();
        labelObservacionCharactersCount = new javax.swing.JLabel();
        labelVendedor = new javax.swing.JLabel();
        cbVendedor = new javax.swing.JComboBox();
        labelCAE = new javax.swing.JLabel();
        tfCAE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        panelProducto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfProductoCodigo = new javax.swing.JTextField();
        bBuscarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        tfPrecioUnitario = new javax.swing.JTextField();
        tfProductoIVA = new javax.swing.JTextField();
        btnADD = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        labelDescuento = new javax.swing.JLabel();
        tfProductoDesc = new javax.swing.JTextField();
        cbDesc = new javax.swing.JComboBox();
        cbProductos = new javax.swing.JComboBox();
        labelCodigoNoRegistrado = new javax.swing.JLabel();
        labelCodigoNoRegistrado.setVisible(false);
        labelIsInOferta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tfTotalGravado = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTotalIVA21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfTotalDesc = new javax.swing.JTextField();
        tfTotalOtrosImps = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tfDiferenciaRedondeo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfTotalIVA105 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfTotalNoGravado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación - Ventas");
        setResizable(false);

        panelDatosFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos facturación"));

        labelNumFactura.setText("Nº factura");

        labeFecha.setText("Fecha");

        tfFacturaCuarto.setEditable(false);
        tfFacturaCuarto.setColumns(4);
        tfFacturaCuarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfFacturaCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFacturaCuarto.setText("0000");
        tfFacturaCuarto.setFocusable(false);
        tfFacturaCuarto.setRequestFocusEnabled(false);

        tfFacturaOcteto.setEditable(false);
        tfFacturaOcteto.setColumns(8);
        tfFacturaOcteto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfFacturaOcteto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFacturaOcteto.setText("12345678");
        tfFacturaOcteto.setToolTipText("<html>\nDébido a la característica multi-usuario del sistema, el número de comprobante es representativo y puede\n<br> diferir del número final que se asignará una vez finalizada y aceptada la creación del mismo.\n</html>");
        tfFacturaOcteto.setFocusable(false);
        tfFacturaOcteto.setRequestFocusEnabled(false);
        tfFacturaOcteto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFacturaOctetoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFacturaOctetoFocusLost(evt);
            }
        });
        tfFacturaOcteto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFacturaOctetoKeyTyped(evt);
            }
        });

        labelLetra.setText("Tipo");

        cbFacturaTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbFacturaTipo.setName("facturaLetra"); // NOI18N

        cbCaja.setName("caja"); // NOI18N

        labelCaja.setText("Caja");

        labelNumMovimiento.setText("Nº");

        tfNumMovimiento.setEditable(false);
        tfNumMovimiento.setColumns(4);
        tfNumMovimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfNumMovimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumMovimiento.setText("0000");
        tfNumMovimiento.setToolTipText("Nº de movimiento interno");
        tfNumMovimiento.setFocusable(false);
        tfNumMovimiento.setRequestFocusEnabled(false);

        labelListaPrecios.setText("Lista Precios");

        jLabel1.setText("Cliente");

        cbCliente.setName("cliente"); // NOI18N

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add.png"))); // NOI18N
        btnCliente.setName("btnClientes"); // NOI18N

        cbListaPrecio.setName("listaPrecios"); // NOI18N

        dcFechaFactura.setMaxSelectableDate(new java.util.Date(4070923260000L));
        dcFechaFactura.setMinSelectableDate(new java.util.Date(-2208969732000L));

        jLabel2.setText("Sucursal");

        cbSucursal.setName("sucursal"); // NOI18N

        labelFormaPago.setText("Forma Pago");

        cbFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFormaPagoActionPerformed(evt);
            }
        });
        cbFormaPago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbFormaPagoFocusLost(evt);
            }
        });

        labelDias.setText("Días");

        tfDias.setEnabled(false);
        tfDias.setName("dias"); // NOI18N
        tfDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDiasKeyTyped(evt);
            }
        });

        labelRemito.setText("Remito");

        tfRemito.setEditable(false);
        tfRemito.setColumns(12);
        tfRemito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfRemito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRemito.setFocusable(false);
        tfRemito.setRequestFocusEnabled(false);

        btnBuscarRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add.png"))); // NOI18N
        btnBuscarRemito.setToolTipText("Vincular a un Remito");
        btnBuscarRemito.setName("btnBuscarRemito"); // NOI18N

        labelListaPrecioParaCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_star_offer.png"))); // NOI18N
        labelListaPrecioParaCatalogo.setToolTipText("Lista de precios para CATÁLOGO WEB");
        labelListaPrecioParaCatalogo.setVisible(false);

        tfObservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfObservacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfObservacionFocusLost(evt);
            }
        });
        tfObservacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfObservacionKeyReleased(evt);
            }
        });

        labelObservacion.setText("Observación");

        labelUnidadNegocio.setText("Unidad de Negocio");

        cbUnidadDeNegocio.setName(""); // NOI18N

        labelCuenta.setText("Cuenta");

        cbCuenta.setName(""); // NOI18N

        labelSubCuenta.setText("Sub Cuenta");

        cbSubCuenta.setName(""); // NOI18N

        labelObservacionCharactersCount.setText("0/100");
        labelObservacionCharactersCount.setFocusable(false);
        labelObservacionCharactersCount.setRequestFocusEnabled(false);

        labelVendedor.setText("Vendedor");

        labelCAE.setText("CAE");

        tfCAE.setEditable(false);
        tfCAE.setToolTipText("Código de Autorización Eletrónico");

        javax.swing.GroupLayout panelDatosFacturacionLayout = new javax.swing.GroupLayout(panelDatosFacturacion);
        panelDatosFacturacion.setLayout(panelDatosFacturacionLayout);
        panelDatosFacturacionLayout.setHorizontalGroup(
            panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelObservacion)
                    .addComponent(labelListaPrecios)
                    .addComponent(jLabel1)
                    .addComponent(labelLetra)
                    .addComponent(labelCuenta)
                    .addComponent(labelFormaPago))
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelRemito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscarRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelListaPrecioParaCatalogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelUnidadNegocio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUnidadDeNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelNumFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(labelCAE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCAE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeFecha)
                                .addGap(10, 10, 10)
                                .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(labelNumMovimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelObservacionCharactersCount))
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSubCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSubCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelDias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosFacturacionLayout.setVerticalGroup(
            panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRemito)
                    .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelListaPrecios)
                    .addComponent(jLabel2)
                    .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelListaPrecioParaCatalogo)
                    .addComponent(cbListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUnidadNegocio)
                    .addComponent(cbUnidadDeNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumFactura)
                    .addComponent(labelLetra)
                    .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNumMovimiento)
                            .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labeFecha)
                            .addComponent(labelCAE)
                            .addComponent(tfCAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCaja)
                    .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFormaPago)
                    .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCuenta)
                        .addComponent(cbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelSubCuenta))
                    .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSubCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelVendedor)
                        .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObservacion)
                    .addComponent(labelObservacionCharactersCount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane1.setViewportView(jTable1);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_button_cancel.png"))); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("cancelar"); // NOI18N

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
        btnAceptar.setMnemonic('a');
        btnAceptar.setText("Aceptar");
        btnAceptar.setName("aceptar"); // NOI18N
        btnAceptar.setPreferredSize(new java.awt.Dimension(111, 41));

        panelProducto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel8.setText("Código");

        tfProductoCodigo.setColumns(4);
        tfProductoCodigo.setToolTipText("ingrese el código y presione Enter");
        tfProductoCodigo.setName("productoCodigo"); // NOI18N

        bBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        bBuscarProducto.setToolTipText("Buscar Producto");
        bBuscarProducto.setName("btnProducto"); // NOI18N
        bBuscarProducto.setRequestFocusEnabled(false);

        jLabel9.setText("Nombre");

        jLabel10.setText("Cantidad");

        jLabel11.setText("Precio U.");

        jLabel17.setText("IVA %");

        tfCantidad.setColumns(5);
        tfCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCantidad.setName("productoCant"); // NOI18N
        tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCantidadFocusGained(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });

        tfPrecioUnitario.setColumns(8);
        tfPrecioUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPrecioUnitario.setToolTipText("Precio venta + Lista Precios");
        tfPrecioUnitario.setName("productoPrecio"); // NOI18N
        tfPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrecioUnitarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrecioUnitarioFocusLost(evt);
            }
        });

        tfProductoIVA.setEditable(false);
        tfProductoIVA.setColumns(4);
        tfProductoIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfProductoIVA.setFocusable(false);
        tfProductoIVA.setRequestFocusEnabled(false);

        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnADD.setToolTipText("Agragar producto");
        btnADD.setName("add"); // NOI18N
        btnADD.setRequestFocusEnabled(false);
        btnADD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnADDFocusLost(evt);
            }
        });

        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnDEL.setToolTipText("Quitar producto");
        btnDEL.setName("del"); // NOI18N
        btnDEL.setRequestFocusEnabled(false);

        labelDescuento.setText("Desc");

        tfProductoDesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfProductoDesc.setText("0");
        tfProductoDesc.setToolTipText("Descuento sobre Precio Unitario");
        tfProductoDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfProductoDescFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfProductoDescFocusLost(evt);
            }
        });

        cbDesc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%", "$" }));
        cbDesc.setToolTipText("<html>Margen de descuento aplicado al <b>Precio Unitario</b>\n<br><b>%</b> Porcentual (máximo 100)\n<br><b>$</b> Monto fijo  (precio Unitario - monto fijo => 0)\n</html>");

        labelCodigoNoRegistrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCodigoNoRegistrado.setForeground(new java.awt.Color(255, 51, 0));
        labelCodigoNoRegistrado.setText("¡CÓDIGO NO REGISTRADO!");

        labelIsInOferta.setForeground(new java.awt.Color(255, 102, 0));
        labelIsInOferta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_star_offer.png"))); // NOI18N
        labelIsInOferta.setText("¡EN OFERTA!");
        labelIsInOferta.setVisible(false);

        jLabel4.setText("Marca");

        tfMarca.setEditable(false);

        javax.swing.GroupLayout panelProductoLayout = new javax.swing.GroupLayout(panelProducto);
        panelProducto.setLayout(panelProductoLayout);
        panelProductoLayout.setHorizontalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDescuento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProductoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCodigoNoRegistrado))
                    .addGroup(panelProductoLayout.createSequentialGroup()
                        .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIsInOferta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProductoLayout.setVerticalGroup(
            panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoLayout.createSequentialGroup()
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoNoRegistrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIsInOferta)
                    .addComponent(jLabel4)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfProductoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescuento)
                    .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel23.setText("Gravado");

        tfTotalGravado.setEditable(false);
        tfTotalGravado.setColumns(8);
        tfTotalGravado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalGravado.setText("0.00");

        tfTotal.setEditable(false);
        tfTotal.setColumns(10);
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotal.setText("0.00");
        tfTotal.setToolTipText("<html>Importe total\n<br>Este importe puede variar entre un <b>Consumidor Final o Tipo B</b>\n<br>y un <b>Responsable Inscripto, tipo A</b>\n");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Total");

        jLabel25.setText("  IVA 21%");

        tfTotalIVA21.setEditable(false);
        tfTotalIVA21.setColumns(6);
        tfTotalIVA21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalIVA21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalIVA21.setText("0.00");

        jLabel27.setText("Desc.");

        tfTotalDesc.setEditable(false);
        tfTotalDesc.setColumns(6);
        tfTotalDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalDesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalDesc.setText("0.00");

        tfTotalOtrosImps.setEditable(false);
        tfTotalOtrosImps.setColumns(6);
        tfTotalOtrosImps.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalOtrosImps.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalOtrosImps.setText("0.00");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Otros Imps.");

        tfDiferenciaRedondeo.setEditable(false);
        tfDiferenciaRedondeo.setColumns(10);
        tfDiferenciaRedondeo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDiferenciaRedondeo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDiferenciaRedondeo.setText("0.00");
        tfDiferenciaRedondeo.setToolTipText("<html>\nIndica la perdida o ganancia por redondeo:\n<br>Positivo: a favor del comerciante.\n<br>Negativo: del Cliente (comprador).\n<br><b>Este item SOLO es visible en las Facturas que no discriminan impuestos/alicuotas</b>\n</html>\n");

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dif. Redondeo");

        tfTotalIVA105.setEditable(false);
        tfTotalIVA105.setColumns(6);
        tfTotalIVA105.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalIVA105.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalIVA105.setText("0.00");

        jLabel26.setText("IVA 10,5%");

        tfTotalNoGravado.setEditable(false);
        tfTotalNoGravado.setColumns(6);
        tfTotalNoGravado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalNoGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalNoGravado.setText("0.00");

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("No Gravado");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalOtrosImps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(tfTotalNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiferenciaRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiferenciaRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotalGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalOtrosImps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addContainerGap())
        );

        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/impresora.png"))); // NOI18N
        btnFacturar.setMnemonic('f');
        btnFacturar.setText("Facturar");
        btnFacturar.setName("facturar"); // NOI18N

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_editdelete.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.setName("facturar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193)
                        .addComponent(btnFacturar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
        SwingUtil.checkInputDigit(evt);
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void cbFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagoActionPerformed
        //habilitando el textfield para poner la cantidad de días de cta cte
        if (cbFormaPago.getSelectedIndex() > 0) {
            Valores.FormaPago formaPago = (Valores.FormaPago) cbFormaPago.getSelectedItem();
            boolean habilitarDias = formaPago.equals(Valores.FormaPago.CTA_CTE);
            tfDias.setEnabled(habilitarDias);
            tfDias.setRequestFocusEnabled(tfDias.isEnabled());
            tfDias.setText("");
            //deshabilita la selección de caja
            //ya que cuando es CtaCte o Cheque, no hay movimiento de Caja
            cbCaja.setEnabled(!habilitarDias);
        } else {
            tfDias.setEnabled(false);
            tfDias.setRequestFocusEnabled(false);
            tfDias.setText("");
        }
}//GEN-LAST:event_cbFormaPagoActionPerformed

    private void cbFormaPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFormaPagoFocusLost
        if (tfDias.isEnabled()) {
            tfDias.requestFocus();
        }
}//GEN-LAST:event_cbFormaPagoFocusLost

    private void tfDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiasKeyTyped
        SwingUtil.checkInputDigit(evt, 3);
}//GEN-LAST:event_tfDiasKeyTyped

    private void tfPrecioUnitarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusGained
        tfPrecioUnitario.setSelectionStart(0);
    }//GEN-LAST:event_tfPrecioUnitarioFocusGained

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
        tfCantidad.selectAll();
    }//GEN-LAST:event_tfCantidadFocusGained

    private void btnADDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnADDFocusLost
        tfProductoCodigo.requestFocus();
    }//GEN-LAST:event_btnADDFocusLost

    private void tfProductoDescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProductoDescFocusGained
        tfProductoDesc.setSelectionStart(0);
    }//GEN-LAST:event_tfProductoDescFocusGained

    private void tfObservacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfObservacionKeyReleased
        controlDeCaracteres(tfObservacion);
    }//GEN-LAST:event_tfObservacionKeyReleased

    private void tfObservacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfObservacionFocusGained
        controlDeCaracteres(tfObservacion);
    }//GEN-LAST:event_tfObservacionFocusGained

    private void tfObservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfObservacionFocusLost
        controlDeCaracteres(tfObservacion);
    }//GEN-LAST:event_tfObservacionFocusLost

private void tfPrecioUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusLost
    try {
        tfPrecioUnitario.setText(JGestionUtils.setScale(tfPrecioUnitario).toString());
        tfPrecioUnitario.setForeground(Color.BLACK);
    } catch (Exception ex) {
        tfPrecioUnitario.setForeground(Color.RED);
    }
}//GEN-LAST:event_tfPrecioUnitarioFocusLost

private void tfProductoDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfProductoDescFocusLost
    if (cbDesc.getSelectedIndex() == 1) {
        try {
            tfProductoDesc.setText(JGestionUtils.setScale(tfProductoDesc).toString());
            tfProductoDesc.setForeground(Color.BLACK);
        } catch (Exception ex) {
            tfProductoDesc.setForeground(Color.RED);
        }
    }
}//GEN-LAST:event_tfProductoDescFocusLost

    private void tfFacturaOctetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaOctetoKeyTyped
        SwingUtil.checkInputDigit(evt, 8);
    }//GEN-LAST:event_tfFacturaOctetoKeyTyped

    private void tfFacturaOctetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaOctetoFocusLost
        String x = UTIL.AGREGAR_CEROS(tfFacturaOcteto.getText(), 8);
        tfFacturaOcteto.setText(x);
    }//GEN-LAST:event_tfFacturaOctetoFocusLost

    private void tfFacturaOctetoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaOctetoFocusGained
        ((JTextComponent) tfFacturaOcteto).selectAll();
    }//GEN-LAST:event_tfFacturaOctetoFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarProducto;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnBuscarRemito;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JComboBox cbCaja;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbCuenta;
    private javax.swing.JComboBox cbDesc;
    private javax.swing.JComboBox cbFacturaTipo;
    private javax.swing.JComboBox cbFormaPago;
    private javax.swing.JComboBox cbListaPrecio;
    private javax.swing.JComboBox cbProductos;
    private javax.swing.JComboBox cbSubCuenta;
    private javax.swing.JComboBox cbSucursal;
    private javax.swing.JComboBox cbUnidadDeNegocio;
    private javax.swing.JComboBox cbVendedor;
    private com.toedter.calendar.JDateChooser dcFechaFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeFecha;
    private javax.swing.JLabel labelCAE;
    private javax.swing.JLabel labelCaja;
    private javax.swing.JLabel labelCodigoNoRegistrado;
    private javax.swing.JLabel labelCuenta;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelDias;
    private javax.swing.JLabel labelFormaPago;
    private javax.swing.JLabel labelIsInOferta;
    private javax.swing.JLabel labelLetra;
    private javax.swing.JLabel labelListaPrecioParaCatalogo;
    private javax.swing.JLabel labelListaPrecios;
    private javax.swing.JLabel labelNumFactura;
    private javax.swing.JLabel labelNumMovimiento;
    private javax.swing.JLabel labelObservacion;
    private javax.swing.JLabel labelObservacionCharactersCount;
    private javax.swing.JLabel labelRemito;
    private javax.swing.JLabel labelSubCuenta;
    private javax.swing.JLabel labelUnidadNegocio;
    private javax.swing.JLabel labelVendedor;
    private javax.swing.JPanel panelDatosFacturacion;
    private javax.swing.JPanel panelProducto;
    private javax.swing.JTextField tfCAE;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfDias;
    private javax.swing.JTextField tfDiferenciaRedondeo;
    private javax.swing.JTextField tfFacturaCuarto;
    private javax.swing.JTextField tfFacturaOcteto;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfNumMovimiento;
    private javax.swing.JTextField tfObservacion;
    private javax.swing.JTextField tfPrecioUnitario;
    private javax.swing.JTextField tfProductoCodigo;
    private javax.swing.JTextField tfProductoDesc;
    private javax.swing.JTextField tfProductoIVA;
    private javax.swing.JTextField tfRemito;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalDesc;
    private javax.swing.JTextField tfTotalGravado;
    private javax.swing.JTextField tfTotalIVA105;
    private javax.swing.JTextField tfTotalIVA21;
    private javax.swing.JTextField tfTotalNoGravado;
    private javax.swing.JTextField tfTotalOtrosImps;
    // End of variables declaration//GEN-END:variables

    // <editor-fold defaultstate="collapsed" desc="GETTERS">
    public JComboBox getCbProductos() {
        return cbProductos;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public String getTfDias() {
        return tfDias.getText().trim();
    }

    public void setTfDias(String dias) {
        tfDias.setText(dias);
    }

    public JComboBox getCbFormaPago() {
        return cbFormaPago;
    }

    public JComboBox getCbCaja() {
        return cbCaja;
    }

    public DefaultTableModel getDtm() {
        return (DefaultTableModel) getjTable1().getModel();
    }

    public JTextField getTfCAE() {
        return tfCAE;
    }

    public JTextField getTfCantidad() {
        return tfCantidad;
    }

    public String getTfTotalDesc() {
        return tfTotalDesc.getText().trim();
    }

    public String getTfFacturaCuarto() {
        return tfFacturaCuarto.getText().trim();
    }

    public String getTfFacturaOcteto() {
        return tfFacturaOcteto.getText().trim();
    }

    public String getTfTotalGravado() {
        return tfTotalGravado.getText().trim();
    }

    public String getTfTotalNoGravado() {
        return tfTotalNoGravado.getText().trim();
    }

    public String getTfPrecioUnitario() {
        return tfPrecioUnitario.getText().trim();
    }

    public JTextField getTfProductoCodigo() {
        return tfProductoCodigo;
    }

    public String getTfProductoDesc() {
        return tfProductoDesc.getText().trim();
    }

    public String getTfProductoIVA() {
        return tfProductoIVA.getText().trim();
    }

    public String getTfTotal() {
        return tfTotal.getText().trim();
    }

    public String getTfTotalIVA105() {
        return tfTotalIVA105.getText().trim();
    }

    public String getTfTotalIVA21() {
        return tfTotalIVA21.getText().trim();
    }

    public String getTfTotalOtrosImps() {
        return tfTotalOtrosImps.getText();
    }

    public JComboBox getCbCliente() {
        return cbCliente;
    }

    public JComboBox getCbDesc() {
        return cbDesc;
    }

    public JComboBox getCbFacturaTipo() {
        return cbFacturaTipo;
    }

    public JComboBox getCbListaPrecio() {
        return cbListaPrecio;
    }

    public JComboBox getCbSucursal() {
        return cbSucursal;
    }

    public Date getDcFechaFactura() {
        return dcFechaFactura.getDate();
    }

    public JTextField getTfMarca() {
        return tfMarca;
    }

    public JTextField getTfDiferenciaRedondeo() {
        return tfDiferenciaRedondeo;
    }

    public JComboBox getCbCuenta() {
        return cbCuenta;
    }

    public JComboBox getCbSubCuenta() {
        return cbSubCuenta;
    }

    public JComboBox getCbUnidadDeNegocio() {
        return cbUnidadDeNegocio;
    }

    public JComboBox getCbVendedor() {
        return cbVendedor;
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="SETTERS">
    public void setTfRemito(String remito) {
        tfRemito.setText(remito);
    }

    public void setDcFechaFactura(java.util.Date fechaFactura) {
        dcFechaFactura.setDate(fechaFactura);
    }

    public void setTfFacturaCuarto(String tfFacturaCuarto) {
        this.tfFacturaCuarto.setText(tfFacturaCuarto);
    }

    public void setTfFacturaOcteto(String tfFacturaOcteto) {
        this.tfFacturaOcteto.setText(tfFacturaOcteto);
    }

    public void setTfGravado(String tfGravado) {
        this.tfTotalGravado.setText(tfGravado);
    }

    public void setTfTotalNoGravado(String noGravado) {
        this.tfTotalNoGravado.setText(noGravado);
    }

    public void setTfProductoCodigo(String tfProductoCodigo) {
        this.tfProductoCodigo.setText(tfProductoCodigo);
    }

    public void setTfProductoIVA(String tfProductoIVA) {
        this.tfProductoIVA.setText(tfProductoIVA);
    }

    public void setTfTotal(String tfTotal2) {
        this.tfTotal.setText(tfTotal2);
    }

    public void setTfTotalIVA105(String tfTotalIVA107) {
        this.tfTotalIVA105.setText(tfTotalIVA107);
    }

    public void setTfTotalIVA21(String tfTotalIVA23) {
        this.tfTotalIVA21.setText(tfTotalIVA23);
    }

    public void setTfTotalOtrosImps(String tfTotalOtrosImps) {
        this.tfTotalOtrosImps.setText(tfTotalOtrosImps);
    }

    public void setTfPrecioUnitario(String precio) {
        this.tfPrecioUnitario.setText(precio);
    }

    public void setTfTotalDesc(String TotalDescuento) {
        this.tfTotalDesc.setText(TotalDescuento);
    }

    // </editor-fold>
    /**
     * Setea un mensaje de información.
     *
     * @param msg ,.. mensaje.
     * @param titulo (puede tener título o no).
     * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
     */
    public void showMessage(String msg, String titulo, int messageType) {
        if (messageType >= -1 && messageType <= 2) {
            javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, messageType);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, msg);
        }
    }

    public JLabel getLabelDias() {
        return labelDias;
    }

    public void setTfNumMovimiento(String tfMovimientoInterno) {
        this.tfNumMovimiento.setText(tfMovimientoInterno);
    }

    public void modoVista() {
        viewMode = true;
        editMode = false;
        SwingUtil.setComponentsEnabled(panelDatosFacturacion.getComponents(), false, true, (Class<? extends Component>[]) null);
        SwingUtil.setComponentsEnabled(panelProducto.getComponents(), false, true, (Class<? extends Component>[]) null);
        btnAceptar.setEnabled(true);
    }

    public JButton getBtnFacturar() {
        return btnFacturar;
    }

    /**
     * Botón usado para aceptar e imprimir Comprobantes de Venta y Remitos.
     *
     * @return
     */
    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnAnular() {
        return btnAnular;
    }

    public JButton getbBuscarProducto() {
        return bBuscarProducto;
    }

    public JButton getBtnADD() {
        return btnADD;
    }

    public JButton getBtnBuscarRemito() {
        return btnBuscarRemito;
    }

    public JButton getBtnCliente() {
        return btnCliente;
    }

    public JButton getBtnDEL() {
        return btnDEL;
    }

    /**
     * 1 = FacturaVenta, 2 = Presupuesto, 3 = Remito
     *
     * @return
     */
    public int getModoUso() {
        return modoUso;
    }

    public void setLabelCodigoNoRegistradoVisible(boolean visible) {
        labelCodigoNoRegistrado.setVisible(visible);
    }

    public JPanel getPanelDatosFacturacion() {
        return panelDatosFacturacion;
    }

    public JPanel getPanelProducto() {
        return panelProducto;
    }

    public void setLabelOfertaVisible(boolean isOferta) {
        labelIsInOferta.setVisible(isOferta);
    }

    /**
     * Settea si o no van a estar habilitados los componenetes: <ol>
     * <ul>tfPrecioUnitario</ul> <ul>tfProductoDesc</ul> <ul>cdDesc</ul> </ol>
     *
     * @param habilitar ....
     */
    public void enableModificacionPrecios(boolean habilitar) {
        tfPrecioUnitario.setEnabled(habilitar);
        tfProductoDesc.setEnabled(habilitar);
        cbDesc.setEnabled(habilitar);
    }

    public void setVisibleEstrellita(boolean visible) {
        labelListaPrecioParaCatalogo.setVisible(visible);
    }

    public JTextField getTfObservacion() {
        return tfObservacion;
    }

    /**
     * Settea la Ventana para ser utilizada por NotaCredito.
     */
    public void setUIToNotaCredito() {
        setTitle("ABM - Nota de Crédito");
        labelNumFactura.setText("Nº");
        btnAceptar.setText("Aceptar");
        btnAceptar.setMnemonic('a');
        labelObservacion.setVisible(true);
        tfObservacion.setVisible(true);
        labelNumFactura.setVisible(true);
        tfFacturaCuarto.setVisible(true);
        tfFacturaOcteto.setVisible(true);
        labeFecha.setVisible(true);
        dcFechaFactura.setVisible(true);

        btnFacturar.setVisible(false);
        //no binding to remitos
        labelRemito.setVisible(false);
        tfRemito.setVisible(false);
        btnBuscarRemito.setVisible(false);
        //no formas de pago
        labelFormaPago.setVisible(false);
        cbFormaPago.setVisible(false);
        //no días de ctacte
        labelDias.setVisible(false);
        tfDias.setVisible(false);
        //por ahora no...
        labelNumMovimiento.setVisible(false);
        tfNumMovimiento.setVisible(false);
        labelCaja.setVisible(false);
        cbCaja.setVisible(false);
        //no se Vendedor
        labelVendedor.setVisible(false);
        cbVendedor.setVisible(false);
        //no descuentos
        labelDescuento.setVisible(false);
        cbDesc.setVisible(false);
        tfProductoDesc.setVisible(false);
        pack();
    }

    public void setUIToFacturaVenta() {
        labelObservacion.setVisible(true);
        tfObservacion.setVisible(true);
        pack();
    }

    public void setUIToPresupuesto() {
        setTitle("Presupuestos");
        btnAceptar.setText("Aceptar");
        btnAceptar.setMnemonic('a');
        btnFacturar.setVisible(false);
        labelCaja.setVisible(false);
        cbCaja.setVisible(false);
        //tienen tipo: A B C
        labelLetra.setVisible(false);
        cbFacturaTipo.setVisible(false);
        //Presup y Remito no se los puede vincular con un Remito
        labelRemito.setVisible(false);
        tfRemito.setVisible(false);
        btnBuscarRemito.setVisible(false);
        labelUnidadNegocio.setVisible(false);
        cbUnidadDeNegocio.setVisible(false);
        labelCuenta.setVisible(false);
        cbCuenta.setVisible(false);
        labelSubCuenta.setVisible(false);
        cbSubCuenta.setVisible(false);
        labelNumMovimiento.setVisible(false);
        tfNumMovimiento.setVisible(false);
        labelNumFactura.setVisible(false);
        tfFacturaCuarto.setVisible(false);
        tfFacturaOcteto.setVisible(false);
        labeFecha.setVisible(false);
        dcFechaFactura.setVisible(false);
        //no CAE
        labelCAE.setVisible(false);
        tfCAE.setVisible(false);
        //no se Vendedor
        labelVendedor.setVisible(false);
        cbVendedor.setVisible(false);
        pack();
    }

    public void setUIToRemito() {
        setTitle("Remito");
        labelNumFactura.setText("Nº Remito");
        labelNumMovimiento.setVisible(false);
        tfNumMovimiento.setVisible(true);
        //tienen tipo: A B C
        labelLetra.setVisible(false);
        cbFacturaTipo.setVisible(false);
        //Campo se pagan!
        labelFormaPago.setVisible(false);
        cbFormaPago.setVisible(false);
        labelDias.setVisible(false);
        tfDias.setVisible(false);
        labelListaPrecios.setVisible(false);
        cbListaPrecio.setVisible(false);
        labelListaPrecioParaCatalogo.setVisible(false);
    }

    private void controlDeCaracteres(JTextField textField) {
        int length = textField.getText().length();
        labelObservacionCharactersCount.setText(length + "/100");
        if (length > 100) {
            tfObservacion.setBackground(Color.RED);
        } else {
            tfObservacion.setBackground(null);
        }
    }

    /**
     * Sirve de guia para saber si la ventana se está utilizando en modo vista
     *
     * @param viewMode
     */
    public void setViewMode(boolean viewMode) {
        this.viewMode = viewMode;
        editMode = !viewMode;
    }

    /**
     * @see JDFacturaVenta#setViewMode(boolean)}
     * @return
     */
    public boolean isViewMode() {
        return viewMode;
    }

    /**
     * Si es modo edición, cambian algunos check constraints
     *
     * @return
     */
    public boolean isEditMode() {
        return editMode;
    }

    public void setEditMode(boolean editMode) {
        this.editMode = editMode;
        viewMode = !editMode;
    }

    public void setVisibleListaPrecio(boolean b) {
        cbListaPrecio.setVisible(b);
        labelListaPrecios.setVisible(b);
    }

    public void setNumeroFacturaEditable(boolean b) {
        tfFacturaOcteto.setFocusable(true);
        tfFacturaOcteto.setRequestFocusEnabled(true);
        tfFacturaOcteto.setEnabled(b);
        tfFacturaOcteto.setEditable(b);
    }

    public void setEnableDcFechaFactura(boolean enable) {
        dcFechaFactura.setEnabled(enable);
    }

    public void setModoEdicion() {
        viewMode = false;
        editMode = true;
        cbListaPrecio.setEnabled(false);
        //////////////////
        tfProductoCodigo.setEnabled(false);
        bBuscarProducto.setEnabled(false);
        cbProductos.setEnabled(false);
        tfCantidad.setEnabled(false);
        tfPrecioUnitario.setEnabled(false);
        tfProductoIVA.setEnabled(false);
        cbDesc.setEnabled(false);
        tfProductoDesc.setEnabled(false);
        btnADD.setEnabled(false);
        btnDEL.setEnabled(false);
        btnAnular.setVisible(false);
    }
}
