
/*
 * JDImportarProductos.java
 *
 * Created on Dec 26, 2020, 11:48:54 AM
 */
package jgestion.gui;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author FiruzzZ
 */
public class JDImportarProductos extends javax.swing.JDialog {

    /**
     * Creates new form JDImportarProductos
     */
    public JDImportarProductos(java.awt.Window parent, boolean modal) {
        super(parent, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfPathFile = new javax.swing.JTextField();
        btnSearchFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        btnFormatoInfo = new javax.swing.JButton();
        btnReadFile = new javax.swing.JButton();
        btnImportar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        checkActualizarPrecioVenta = new javax.swing.JCheckBox();
        cbRubro = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfCantidadImportar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Archivo");

        tfPathFile.setEditable(false);

        btnSearchFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        btnSearchFile.setText("Buscar");

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Marca", "Rubro", "IVA", "Precio Venta", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jXTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jXTable1);
        if (jXTable1.getColumnModel().getColumnCount() > 0) {
            jXTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jXTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jXTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
            jXTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jXTable1.getColumnModel().getColumn(4).setMinWidth(50);
            jXTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jXTable1.getColumnModel().getColumn(4).setMaxWidth(50);
            jXTable1.getColumnModel().getColumn(5).setMinWidth(60);
            jXTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
            jXTable1.getColumnModel().getColumn(5).setMaxWidth(90);
            jXTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        btnFormatoInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/excel.png"))); // NOI18N
        btnFormatoInfo.setText("Ver formato de Importación");
        btnFormatoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatoInfoActionPerformed(evt);
            }
        });

        btnReadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/view_detail_16x.png"))); // NOI18N
        btnReadFile.setText("Cargar archivo");

        btnImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/24px_undo_arrow.png"))); // NOI18N
        btnImportar.setText("Importar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones globales (serán aplicadas a todos los productos importados)"));

        checkActualizarPrecioVenta.setText("Actualizar Precio venta según Precio compra");

        jLabel3.setText("Rubro");

        jLabel4.setText("(rubro a aplicar cuando no se especificó en archivo)");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/information.png"))); // NOI18N
        jLabel2.setText("<html>Si la columna Estado es distinta de <b>OK</b>, ese producto no se importará al sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkActualizarPrecioVenta)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkActualizarPrecioVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setText("Cantidad a importar");

        tfCantidadImportar.setEditable(false);
        tfCantidadImportar.setColumns(8);
        tfCantidadImportar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReadFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnFormatoInfo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCantidadImportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImportar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchFile)
                    .addComponent(btnFormatoInfo)
                    .addComponent(btnReadFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImportar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(tfCantidadImportar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormatoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatoInfoActionPerformed
        JOptionPane.showMessageDialog(this, "<html>Debe ser un archivo Excel con las siguientes columnas y orden:"
                + "<br>Las columnas código, nombre, marca son obligatorias."
                + "<br><b>Código</b>: longitud= 15, solo caracteres alfanuméricos (sin espacios, guiones, barras, comas, puntos etc.), se recomienda usar <b>EAN-13</b>"
                + "<br><b>Nombre</b>: longitud= 150, caracteres alfanuméricos, guión medio, punto"
                + "<br>Ej: Lápiz N° 1, Resma 60/80, Módulo 1.20.5, Medida-x-s"
                + "<br><b>Marca</b>: longitud= 40, caracteres alfanuméricos, guión medio, punto"
                + "<br><b>Rubro</b>: longitud= 50, caracteres alfanuméricos, guión medio, punto"
                + "<br><b>IVA</b>: longitud= 4, formato esperado ej: 21 o 10.5 o 10,5 o 0 (cero). La ausencia de un valor será interpretada como 0%"
                + "<br><b>Precio Venta</b>: longitud= 12, solo números y un punto ej: 123456791 o 123456789.99 o 0.59"
                + " La ausencia de un valor será interpretada como $0",
                 "Formato de Importación", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnFormatoInfoActionPerformed

    public JButton getBtnImportar() {
        return btnImportar;
    }

    public void setBtnImportar(JButton btnImportar) {
        this.btnImportar = btnImportar;
    }

    public JButton getBtnReadFile() {
        return btnReadFile;
    }

    public void setBtnReadFile(JButton btnReadFile) {
        this.btnReadFile = btnReadFile;
    }

    public JButton getBtnSearchFile() {
        return btnSearchFile;
    }

    public void setBtnSearchFile(JButton btnSearchFile) {
        this.btnSearchFile = btnSearchFile;
    }

    public JCheckBox getCheckActualizarPrecioVenta() {
        return checkActualizarPrecioVenta;
    }

    public void setCheckActualizarPrecioVenta(JCheckBox checkActualizarPrecioVenta) {
        this.checkActualizarPrecioVenta = checkActualizarPrecioVenta;
    }

    public JXTable getjXTable1() {
        return jXTable1;
    }

    public void setjXTable1(JXTable jXTable1) {
        this.jXTable1 = jXTable1;
    }

    public JTextField getTfCantidadImportar() {
        return tfCantidadImportar;
    }

    public void setTfCantidadImportar(JTextField tfCantidadImportar) {
        this.tfCantidadImportar = tfCantidadImportar;
    }

    public JTextField getTfPathFile() {
        return tfPathFile;
    }

    public void setTfPathFile(JTextField tfPathFile) {
        this.tfPathFile = tfPathFile;
    }

    public JComboBox getCbRubro() {
        return cbRubro;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormatoInfo;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnReadFile;
    private javax.swing.JButton btnSearchFile;
    private javax.swing.JComboBox cbRubro;
    private javax.swing.JCheckBox checkActualizarPrecioVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JTextField tfCantidadImportar;
    private javax.swing.JTextField tfPathFile;
    // End of variables declaration//GEN-END:variables

}
