/*
 * JDRecibosRemesas.java
 *
 * Created on 05/04/2010, 11:03:26
 */
package jgestion.gui;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;
import utilities.swing.components.NumberRenderer;

/**
 * Ventana usada para el ABM de Recibos y Remitos
 *
 * @author FiruzzZ
 */
public class JDReRe extends javax.swing.JDialog {

    public JDReRe(Window owner, boolean modal) {
        super(owner, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        initComponents();
        tableAPagar.getColumnModel().getColumn(2).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        tablePagos.getColumnModel().getColumn(3).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        UTIL.hideColumnTable(tableAPagar, 0);
        UTIL.hideColumnTable(tablePagos, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAPagar = new javax.swing.JTable();
        bImprimir = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        panelDatos = new javax.swing.JPanel();
        tfCuarto = new javax.swing.JTextField();
        labelReRe = new javax.swing.JLabel();
        labelClienteProveedor = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbClienteProveedor = new javax.swing.JComboBox();
        cbSucursal = new javax.swing.JComboBox();
        dcFechaReRe = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tfOcteto = new javax.swing.JTextField();
        cbCaja = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        labelCreditoDebito = new javax.swing.JLabel();
        tfCreditoDebitoDisponible = new javax.swing.JTextField();
        btnDetalleCreditoDebito = new javax.swing.JButton();
        labelAnulado = new javax.swing.JLabel();
        labelLetra = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox();
        bAnular = new javax.swing.JButton();
        panelAPagar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cbCtaCtes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfImporte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPagado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        tfEntrega = new javax.swing.JTextField();
        tfTotalAPagar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        checkOcultarDatos = new javax.swing.JCheckBox();
        panelPagos = new javax.swing.JPanel();
        cbFormasDePago = new javax.swing.JComboBox();
        btnAddPago = new javax.swing.JButton();
        btnDelPago = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePagos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        tfTotalPagado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("setear título!");
        setResizable(false);

        tableAPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Object", "Factura", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAPagar);
        if (tableAPagar.getColumnModel().getColumnCount() > 0) {
            tableAPagar.getColumnModel().getColumn(0).setResizable(false);
            tableAPagar.getColumnModel().getColumn(0).setPreferredWidth(1);
            tableAPagar.getColumnModel().getColumn(1).setResizable(false);
            tableAPagar.getColumnModel().getColumn(1).setPreferredWidth(80);
            tableAPagar.getColumnModel().getColumn(2).setResizable(false);
        }

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_fileprint.png"))); // NOI18N
        bImprimir.setMnemonic('i');
        bImprimir.setText("Imprimir");
        bImprimir.setName("Print"); // NOI18N

        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
        bAceptar.setMnemonic('a');
        bAceptar.setText("Aceptar");
        bAceptar.setName("aceptar"); // NOI18N

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        bCancelar.setMnemonic('c');
        bCancelar.setText("Cancelar");
        bCancelar.setName("cancelar"); // NOI18N

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        tfCuarto.setEditable(false);
        tfCuarto.setColumns(4);
        tfCuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCuarto.setRequestFocusEnabled(false);

        labelReRe.setText("Nº ReReRe");

        labelClienteProveedor.setText("Prov/Client");

        jLabel20.setText("Sucursal");

        cbClienteProveedor.setName("cbClienteProveedor"); // NOI18N

        cbSucursal.setName("cbSucursal"); // NOI18N

        dcFechaReRe.setDate(new java.util.Date());

        jLabel4.setText("Fecha");

        tfOcteto.setEditable(false);
        tfOcteto.setColumns(8);
        tfOcteto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfOcteto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfOcteto.setRequestFocusEnabled(false);
        tfOcteto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfOctetoKeyTyped(evt);
            }
        });

        cbCaja.setName("caja"); // NOI18N

        jLabel15.setText("Caja");

        labelCreditoDebito.setText("Crédito");

        tfCreditoDebitoDisponible.setEditable(false);
        tfCreditoDebitoDisponible.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfCreditoDebitoDisponible.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCreditoDebitoDisponible.setText("0");
        tfCreditoDebitoDisponible.setFocusable(false);
        tfCreditoDebitoDisponible.setRequestFocusEnabled(false);

        btnDetalleCreditoDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/view_detail_16x.png"))); // NOI18N

        labelAnulado.setVisible(false);
        labelAnulado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelAnulado.setForeground(new java.awt.Color(255, 0, 0));
        labelAnulado.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelAnulado.setText("ANULADO");

        labelLetra.setText("Tipo");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "X" }));
        cbTipo.setName("facturaLetra"); // NOI18N

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelClienteProveedor)
                    .addComponent(jLabel20)
                    .addComponent(labelLetra)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelReRe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcFechaReRe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAnulado))
                    .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbSucursal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbClienteProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, 395, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCreditoDebito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCreditoDebitoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalleCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelClienteProveedor)
                    .addComponent(labelCreditoDebito)
                    .addComponent(tfCreditoDebitoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalleCreditoDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelReRe)
                    .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra)
                    .addComponent(dcFechaReRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(labelAnulado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_editdelete.png"))); // NOI18N
        bAnular.setText("Anular");
        bAnular.setToolTipText("");
        bAnular.setFocusable(false);
        bAnular.setName("anular"); // NOI18N
        bAnular.setRequestFocusEnabled(false);

        panelAPagar.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle a Pagar"));

        jLabel8.setText("Entrega");

        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N
        btnADD.setToolTipText("Agregar entrega al detalle");
        btnADD.setName("add"); // NOI18N
        btnADD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnADDFocusLost(evt);
            }
        });

        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
        btnDEL.setToolTipText("Eliminar entrega");
        btnDEL.setFocusable(false);
        btnDEL.setName("del"); // NOI18N
        btnDEL.setRequestFocusEnabled(false);

        jLabel21.setText("Facturas");

        cbCtaCtes.setName("cbCtactes"); // NOI18N

        jLabel5.setText("Importe");

        tfImporte.setEditable(false);
        tfImporte.setColumns(6);
        tfImporte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfImporte.setText("0");
        tfImporte.setFocusable(false);
        tfImporte.setRequestFocusEnabled(false);

        jLabel6.setText("Pagado");

        tfPagado.setEditable(false);
        tfPagado.setColumns(6);
        tfPagado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfPagado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPagado.setText("0");
        tfPagado.setFocusable(false);
        tfPagado.setRequestFocusEnabled(false);

        jLabel3.setText("Saldo");

        tfSaldo.setEditable(false);
        tfSaldo.setColumns(6);
        tfSaldo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSaldo.setText("0");
        tfSaldo.setToolTipText("Saldo restante");
        tfSaldo.setFocusable(false);
        tfSaldo.setRequestFocusEnabled(false);

        tfEntrega.setColumns(6);
        tfEntrega.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfEntrega.setToolTipText("Monto ($)");
        tfEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectAllText(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEntregaFocusLost(evt);
            }
        });
        tfEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfEntregaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelAPagarLayout = new javax.swing.GroupLayout(panelAPagar);
        panelAPagar.setLayout(panelAPagarLayout);
        panelAPagarLayout.setHorizontalGroup(
            panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAPagarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCtaCtes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelAPagarLayout.createSequentialGroup()
                        .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEntrega)
                            .addComponent(tfImporte))
                        .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAPagarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAPagarLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAPagarLayout.setVerticalGroup(
            panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAPagarLayout.createSequentialGroup()
                .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAPagarLayout.createSequentialGroup()
                        .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbCtaCtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(tfPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAPagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tfTotalAPagar.setEditable(false);
        tfTotalAPagar.setColumns(10);
        tfTotalAPagar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalAPagar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalAPagar.setText("0");
        tfTotalAPagar.setFocusable(false);
        tfTotalAPagar.setRequestFocusEnabled(false);

        jLabel1.setText("Total a pagar");

        checkOcultarDatos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        checkOcultarDatos.setMnemonic('o');
        checkOcultarDatos.setText("Ocultar Datos");
        checkOcultarDatos.setFocusable(false);
        checkOcultarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        checkOcultarDatos.setMargin(new java.awt.Insets(1, 1, 1, 1));
        checkOcultarDatos.setRequestFocusEnabled(false);
        checkOcultarDatos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkOcultarDatosStateChanged(evt);
            }
        });

        panelPagos.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pago"));

        cbFormasDePago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Cheque Propio", "Cheque Tercero", "Nota de Crédito", "Retención", "Transferencia", "Especie" }));

        btnAddPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N

        btnDelPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
        btnDelPago.setToolTipText("Eliminar entrega");
        btnDelPago.setFocusable(false);
        btnDelPago.setName("del"); // NOI18N
        btnDelPago.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelPagosLayout = new javax.swing.GroupLayout(panelPagos);
        panelPagos.setLayout(panelPagosLayout);
        panelPagosLayout.setHorizontalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbFormasDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPagosLayout.setVerticalGroup(
            panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagosLayout.createSequentialGroup()
                .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbFormasDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddPago, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Object", "Tipo", "Descripción", "Importe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePagos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePagos);
        if (tablePagos.getColumnModel().getColumnCount() > 0) {
            tablePagos.getColumnModel().getColumn(0).setResizable(false);
            tablePagos.getColumnModel().getColumn(0).setPreferredWidth(10);
            tablePagos.getColumnModel().getColumn(1).setResizable(false);
            tablePagos.getColumnModel().getColumn(1).setPreferredWidth(20);
            tablePagos.getColumnModel().getColumn(2).setResizable(false);
            tablePagos.getColumnModel().getColumn(2).setPreferredWidth(200);
            tablePagos.getColumnModel().getColumn(3).setResizable(false);
            tablePagos.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        jLabel12.setText("Total");

        tfTotalPagado.setEditable(false);
        tfTotalPagado.setColumns(10);
        tfTotalPagado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalPagado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalPagado.setText("0");
        tfTotalPagado.setFocusable(false);
        tfTotalPagado.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panelAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(panelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTotalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(checkOcultarDatos))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAnular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkOcultarDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(tfTotalPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void selectAllText(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectAllText
       ((JTextField) evt.getSource()).setSelectionStart(0);
   }//GEN-LAST:event_selectAllText

   private void btnADDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnADDFocusLost
       cbCtaCtes.requestFocus();
   }//GEN-LAST:event_btnADDFocusLost

private void checkOcultarDatosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkOcultarDatosStateChanged
    panelDatos.setVisible(!checkOcultarDatos.isSelected());
    pack();
}//GEN-LAST:event_checkOcultarDatosStateChanged

private void tfEntregaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntregaFocusLost
    try {
        tfEntrega.setText(UTIL.PRECIO_CON_PUNTO.format(Double.valueOf(tfEntrega.getText())));
        tfEntrega.setForeground(Color.BLACK);
    } catch (Exception exception) {
        tfEntrega.setForeground(Color.RED);
    }
}//GEN-LAST:event_tfEntregaFocusLost

    private void tfOctetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOctetoKeyTyped
        SwingUtil.checkInputDigit(evt, 8);
    }//GEN-LAST:event_tfOctetoKeyTyped

    private void tfEntregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEntregaKeyTyped
        SwingUtil.checkInputDigit(evt, true);
    }//GEN-LAST:event_tfEntregaKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnular;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnAddPago;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDelPago;
    private javax.swing.JButton btnDetalleCreditoDebito;
    private javax.swing.JComboBox cbCaja;
    private javax.swing.JComboBox cbClienteProveedor;
    private javax.swing.JComboBox cbCtaCtes;
    private javax.swing.JComboBox cbFormasDePago;
    private javax.swing.JComboBox cbSucursal;
    private javax.swing.JComboBox cbTipo;
    private javax.swing.JCheckBox checkOcultarDatos;
    private com.toedter.calendar.JDateChooser dcFechaReRe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAnulado;
    private javax.swing.JLabel labelClienteProveedor;
    private javax.swing.JLabel labelCreditoDebito;
    private javax.swing.JLabel labelLetra;
    private javax.swing.JLabel labelReRe;
    private javax.swing.JPanel panelAPagar;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelPagos;
    private javax.swing.JTable tableAPagar;
    private javax.swing.JTable tablePagos;
    private javax.swing.JTextField tfCreditoDebitoDisponible;
    private javax.swing.JTextField tfCuarto;
    private javax.swing.JTextField tfEntrega;
    private javax.swing.JTextField tfImporte;
    private javax.swing.JTextField tfOcteto;
    private javax.swing.JTextField tfPagado;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTotalAPagar;
    private javax.swing.JTextField tfTotalPagado;
    // End of variables declaration//GEN-END:variables

    /**
     * Setea un mensaje de información.
     *
     * @param msg mensaje.
     * @param titulo (puede tener título o no).
     * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
     */
    public void showMessage(String msg, String titulo, int messageType) {
        if (messageType >= -1 && messageType <= 2) {
            javax.swing.JOptionPane.showMessageDialog(this, msg, titulo,
                    messageType);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, msg);
        }
    }

    public void addActionListener(Object o) {
        btnADD.addActionListener((ActionListener) o);
        btnDEL.addActionListener((ActionListener) o);
        bCancelar.addActionListener((ActionListener) o);
        bAceptar.addActionListener((ActionListener) o);
        bImprimir.addActionListener((ActionListener) o);
        bAnular.addActionListener((ActionListener) o);
        cbClienteProveedor.addActionListener((ActionListener) o);
        cbCtaCtes.addActionListener((ActionListener) o);
    }

    public void limpiarDetalles() {
        DefaultTableModel dtm = (DefaultTableModel) tableAPagar.getModel();
        dtm.setRowCount(0);
        dtm = (DefaultTableModel) tablePagos.getModel();
        dtm.setRowCount(0);
        tfImporte.setText("");
        tfPagado.setText("");
        tfSaldo.setText("");
        tfEntrega.setText("");
    }

    public void defaultSetFields() {
        dcFechaReRe.setDate(new Date());
        cbSucursal.setSelectedIndex(0);
        cbCaja.setSelectedIndex(0);
        cbClienteProveedor.setSelectedIndex(0);
    }

    // <editor-fold defaultstate="collapsed" desc="GETTERS">
    public JButton getBtnAddPago() {
        return btnAddPago;
    }

    public JButton getBtnDelPago() {
        return btnDelPago;
    }

    public JComboBox getCbFormasDePago() {
        return cbFormasDePago;
    }

    public JTextField getTfTotalPagado() {
        return tfTotalPagado;
    }

    public JTextField getTfTotalAPagar() {
        return tfTotalAPagar;
    }

    public JButton getBtnDetalleCreditoDebito() {
        return btnDetalleCreditoDebito;
    }

    public JTextField getTfCreditoDebitoDisponible() {
        return tfCreditoDebitoDisponible;
    }

    public JComboBox getCbTipo() {
        return cbTipo;
    }

    public JComboBox getCbCaja() {
        return cbCaja;
    }

    public JComboBox getCbClienteProveedor() {
        return cbClienteProveedor;
    }

    public JComboBox getCbCtaCtes() {
        return cbCtaCtes;
    }

    public JComboBox getCbSucursal() {
        return cbSucursal;
    }

    public JDateChooser getDcFechaReRe() {
        return dcFechaReRe;
    }

    public JLabel getLabelAnulado() {
        return labelAnulado;
    }

    public JLabel getLabelClienteProveedor() {
        return labelClienteProveedor;
    }

    public JLabel getLabelReRe() {
        return labelReRe;
    }

    public JTextField getTfEntrega() {
        return tfEntrega;
    }

    public JTable getTableAPagar() {
        return tableAPagar;
    }

    public JTable getTablePagos() {
        return tablePagos;
    }

    public DefaultTableModel getDtmAPagar() {
        return (DefaultTableModel) tableAPagar.getModel();
    }

    public String getTfCuarto() {
        return tfCuarto.getText();
    }

    public String getTfOcteto() {
        return tfOcteto.getText();
    }

    public JButton getbAnular() {
        return bAnular;
    }

    public JButton getBtnADD() {
        return btnADD;
    }

    public JButton getBtnDEL() {
        return btnDEL;
    }

    public JButton getbAceptar() {
        return bAceptar;
    }

    public JButton getbImprimir() {
        return bImprimir;
    }

    public JButton getbCancelar() {
        return bCancelar;
    }

    public JPanel getPanelDatos() {
        return panelDatos;
    }

    public JPanel getPanelAPagar() {
        return panelAPagar;
    }

    public JPanel getPanelPagos() {
        return panelPagos;
    }

    // </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="SETTERS">
    public void setTfCuarto(String tfCuarto) {
        this.tfCuarto.setText(tfCuarto);
    }

    public void setTfEntrega(String tfEntrega) {
        this.tfEntrega.setText(tfEntrega);
    }

    public void setTfImporte(String tfImporte) {
        this.tfImporte.setText(tfImporte);
    }

    public void setTfOcteto(String tfOcteto) {
        this.tfOcteto.setText(tfOcteto);
    }

    public void setTfPagado(String tfPagado) {
        this.tfPagado.setText(tfPagado);
    }

    public void setTfSaldo(String tfSaldo) {
        this.tfSaldo.setText(tfSaldo);
    }
    // </editor-fold>

    public void setUIForRecibos() {
        setTitle("Recibos");
        getLabelReRe().setText("Nº Recibo");
        getLabelClienteProveedor().setText("Cliente");
        labelCreditoDebito.setText("Crédito");
        btnDetalleCreditoDebito.setToolTipText("Ver detalle de Crédito");
        pack();
    }

    public void setUIForRemesas() {
        setTitle("Remesas");
        getLabelReRe().setText("Nº Remesa");
        getLabelClienteProveedor().setText("Proveedor");
        labelCreditoDebito.setText("Débito");
        btnDetalleCreditoDebito.setToolTipText("Ver detalle de débito");
//        labelReRe.setVisible(false);
        tfCuarto.setText(null);
        tfCuarto.setFocusable(false);
        tfCuarto.setRequestFocusEnabled(false);
        tfOcteto.setText(null);
        tfOcteto.setFocusable(false);
        tfOcteto.setRequestFocusEnabled(false);
        pack();
    }

    public void setTfOctetoEditable(boolean b) {
        tfOcteto.setEnabled(true);
        tfOcteto.setEditable(true);
        tfOcteto.setFocusable(true);
        tfOcteto.setRequestFocusEnabled(true);
    }

    public DefaultTableModel getDtmPagos() {
        return (DefaultTableModel) tablePagos.getModel();
    }

    public BigDecimal displayABMEfectivo(BigDecimal toEdit) {
        if (toEdit == null) {
            DefaultTableModel dtm = getDtmPagos();
            for (int row = 0; row < dtm.getRowCount(); row++) {
                if (dtm.getValueAt(row, 1).toString().equalsIgnoreCase("EF")) {
                    JOptionPane.showMessageDialog(this, "Ya existe un pago en Efectivo en el detalle", "Error", JOptionPane.WARNING_MESSAGE);
                    return null;
                }
            }
        }
        String monto = JOptionPane.showInputDialog(this, "Ingrese el monton en efectivo:", toEdit == null ? BigDecimal.ZERO : toEdit);
        if (monto != null && !monto.isEmpty()) {
            try {
                monto = UTIL.PRECIO_CON_PUNTO.format(Double.valueOf(monto));
                if (new BigDecimal(monto).compareTo(BigDecimal.ZERO) != 1) {
                    throw new Exception();
                }
                return new BigDecimal(monto);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Monto no válido, ingrese solo números y utilicé el punto como separador decimal.");
                //recursive method..
                return displayABMEfectivo(toEdit);
            }
        }
        return null;
    }
}
