package jgestion.gui;

import com.toedter.calendar.JDateChooser;
import jgestion.entity.Banco;
import java.awt.Window;
import java.io.File;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jgestion.JGestionUtils;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;
import utilities.swing.components.ComboBoxWrapper;
import utilities.swing.components.FormatRenderer;
import utilities.swing.components.NumberRenderer;

/**
 *
 * @author FiruzzZ
 */
public class JDConciliacionBancaria extends javax.swing.JDialog {

    public JDConciliacionBancaria(Window parent, boolean modal) {
        super(parent, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        initComponents();
        buttonGroup1.add(radioDebito);
        buttonGroup1.add(jRadioButton2);
        setLocationRelativeTo(parent);
        jTableExtracto.getColumnModel().getColumn(0).setCellRenderer(FormatRenderer.getDateRenderer());
        jTableExtracto.getColumnModel().getColumn(2).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        jTableExtracto.getColumnModel().getColumn(3).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        jTableExtracto.getColumnModel().getColumn(4).setCellRenderer(NumberRenderer.getCurrencyRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovimientos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        dcDesde = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        cbBancos = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbCuentabancaria = new javax.swing.JComboBox();
        dcHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnImportar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfConcepto = new javax.swing.JTextField();
        dcConceptoFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        tfImporte = new javax.swing.JTextField();
        radioDebito = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnAddAjuste = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnConciliar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableExtracto = new javax.swing.JTable();
        btnImportarExtractoBancario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Object", "Fecha", "Concepto", "Débito", "Crédito", "Saldo", "Conciliado"
            }
        ));
        jScrollPane1.setViewportView(jTableMovimientos);
        if (jTableMovimientos.getColumnModel().getColumnCount() > 0) {
            jTableMovimientos.getColumnModel().getColumn(0).setHeaderValue("Object");
            jTableMovimientos.getColumnModel().getColumn(1).setResizable(false);
            jTableMovimientos.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTableMovimientos.getColumnModel().getColumn(2).setResizable(false);
            jTableMovimientos.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTableMovimientos.getColumnModel().getColumn(3).setResizable(false);
            jTableMovimientos.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableMovimientos.getColumnModel().getColumn(4).setResizable(false);
            jTableMovimientos.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableMovimientos.getColumnModel().getColumn(5).setResizable(false);
            jTableMovimientos.getColumnModel().getColumn(5).setPreferredWidth(70);
            jTableMovimientos.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel4.setText("Hasta");

        dcDesde.setMaxSelectableDate(new java.util.Date(2524622463000L));
        dcDesde.setMinSelectableDate(new java.util.Date(14463000L));

        jLabel1.setText("N° Cuenta");

        jLabel10.setText("Banco");

        dcHasta.setMaxSelectableDate(new java.util.Date(2524622463000L));
        dcHasta.setMinSelectableDate(new java.util.Date(14463000L));

        jLabel3.setText("Desde");

        btnImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        btnImportar.setText("Buscar");
        btnImportar.setName("buscarBuscador"); // NOI18N

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajuste"));

        jLabel2.setText("Importe");

        tfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfImporteKeyTyped(evt);
            }
        });

        radioDebito.setSelected(true);
        radioDebito.setText("Débito");

        jRadioButton2.setText("Crédito");

        btnAddAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add_circular.png"))); // NOI18N
        btnAddAjuste.setText("Agregar");

        jLabel7.setText("Concepto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(dcConceptoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddAjuste)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dcConceptoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnAddAjuste)
                    .addComponent(jLabel2)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(radioDebito))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnConciliar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_change_values.png"))); // NOI18N
        btnConciliar.setText("Conciliar");

        jTableExtracto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Concepto", "Débito", "Crédito", "Saldo", "Conciliado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableExtracto.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableExtracto);
        if (jTableExtracto.getColumnModel().getColumnCount() > 0) {
            jTableExtracto.getColumnModel().getColumn(0).setResizable(false);
            jTableExtracto.getColumnModel().getColumn(0).setPreferredWidth(40);
            jTableExtracto.getColumnModel().getColumn(1).setResizable(false);
            jTableExtracto.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTableExtracto.getColumnModel().getColumn(2).setResizable(false);
            jTableExtracto.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableExtracto.getColumnModel().getColumn(3).setResizable(false);
            jTableExtracto.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableExtracto.getColumnModel().getColumn(4).setResizable(false);
            jTableExtracto.getColumnModel().getColumn(4).setPreferredWidth(70);
            jTableExtracto.getColumnModel().getColumn(5).setResizable(false);
        }

        btnImportarExtractoBancario.setText("Importar Extracto Bancario");
        btnImportarExtractoBancario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarExtractoBancarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbBancos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCuentabancaria, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImportar)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnImprimir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnConciliar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImportarExtractoBancario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cbCuentabancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnImportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarExtractoBancario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConciliar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteKeyTyped
        SwingUtil.checkInputDigit(evt, true, 12);
    }//GEN-LAST:event_tfImporteKeyTyped

    private void btnImportarExtractoBancarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarExtractoBancarioActionPerformed
        DlgImportarArchivoExtraBancario dlg = new DlgImportarArchivoExtraBancario(this);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);
        if (dlg.getImportedData() != null) {
            List<Object[]> data = dlg.getImportedData();
            DefaultTableModel dtm = (DefaultTableModel) jTableExtracto.getModel();
            dtm.setRowCount(0);
            for (Object[] objects : data) {
                dtm.addRow(objects);
            }
        }
    }//GEN-LAST:event_btnImportarExtractoBancarioActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAjuste;
    private javax.swing.JButton btnConciliar;
    private javax.swing.JButton btnImportar;
    private javax.swing.JButton btnImportarExtractoBancario;
    private javax.swing.JButton btnImprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbBancos;
    private javax.swing.JComboBox cbCuentabancaria;
    private com.toedter.calendar.JDateChooser dcConceptoFecha;
    private com.toedter.calendar.JDateChooser dcDesde;
    private com.toedter.calendar.JDateChooser dcHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableExtracto;
    private javax.swing.JTable jTableMovimientos;
    private javax.swing.JRadioButton radioDebito;
    private javax.swing.JTextField tfConcepto;
    private javax.swing.JTextField tfImporte;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnImportar() {
        return btnImportar;
    }

    public JButton getBtnAgregar() {
        return btnAddAjuste;
    }

    public JComboBox getCbCuentabancaria() {
        return cbCuentabancaria;
    }

    public JDateChooser getDcDesde() {
        return dcDesde;
    }

    public JDateChooser getDcHasta() {
        return dcHasta;
    }

    public JTable getjTableMovimientos() {
        return jTableMovimientos;
    }

    public JTable getjTableExtracto() {
        return jTableExtracto;
    }

    public JComboBox getCbBancos() {
        return cbBancos;
    }

    public JDateChooser getDcConceptoFecha() {
        return dcConceptoFecha;
    }

    public JRadioButton getRadioDebito() {
        return radioDebito;
    }

    public JTextField getTfConcepto() {
        return tfConcepto;
    }

    public JTextField getTfImporte() {
        return tfImporte;
    }
}
