
/*
 * JDVentaSimple.java
 *
 * Created on 27/01/2015, 07:33:08
 */
package jgestion.gui;

import jgestion.controller.Contabilidad;
import jgestion.controller.ProductoController;
import jgestion.entity.ListaPrecios;
import jgestion.entity.Producto;
import jgestion.entity.Rubro;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import jgestion.JGestionUtils;
import jgestion.jpa.controller.ProductoJpaController;
import utilities.general.UTIL;

/**
 *
 * @author FiruzzZ
 */
public class JDVentaSimple extends javax.swing.JDialog {

    private Producto selectedProducto;
    private List<Producto> productos;
    private ListaPrecios listaPrecio;

    public JDVentaSimple(Window parent, boolean modal) {
        super(parent, DEFAULT_MODALITY_TYPE);
//        setUndecorated(true);
        initComponents();
        UTIL.getDefaultTableModel(jTable1,
                new String[]{"Object", "Producto", "Cantidad", "Precio U.", "Total"},
                new int[]{0, 200, 30, 50, 50},
                new Class<?>[]{null, null, Integer.class, BigDecimal.class, BigDecimal.class});
        UTIL.hideColumnTable(jTable1, 0);
//        setBounds(GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds());
        //<editor-fold defaultstate="collapsed" desc="locating window on center screen">
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfPrecioUnitario = new javax.swing.JTextField();
        btnIncrease = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        btnFacturar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnDecrease = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productosButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfVuelto = new javax.swing.JTextField();
        tfPago = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        rubroButtonPanel = new javax.swing.JPanel();
        btnIncreaseCant = new javax.swing.JButton();
        btnDecreaseCant = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Cantidad");

        tfCantidad.setEditable(false);
        tfCantidad.setColumns(5);
        tfCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCantidad.setName("productoCant"); // NOI18N
        tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCantidadFocusGained(evt);
            }
        });
        tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Precio U.");

        tfPrecioUnitario.setEditable(false);
        tfPrecioUnitario.setColumns(8);
        tfPrecioUnitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfPrecioUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPrecioUnitario.setToolTipText("Precio venta + Lista Precios");
        tfPrecioUnitario.setName("productoPrecio"); // NOI18N
        tfPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPrecioUnitarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPrecioUnitarioFocusLost(evt);
            }
        });

        btnIncrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arrow_up.png"))); // NOI18N
        btnIncrease.setToolTipText("Agragar producto");
        btnIncrease.setName("add"); // NOI18N
        btnIncrease.setRequestFocusEnabled(false);
        btnIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseActionPerformed(evt);
            }
        });

        btnDeleteItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
        btnDeleteItem.setToolTipText("Quitar producto");
        btnDeleteItem.setName("del"); // NOI18N
        btnDeleteItem.setRequestFocusEnabled(false);
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fernet Branca",  new Double(50.0),  new Integer(2),  new Double(100.0)}
            },
            new String [] {
                "Producto", "Precio Unitario", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Total");

        tfTotal.setEditable(false);
        tfTotal.setColumns(10);
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotal.setText("0.00");

        btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_invoice.png"))); // NOI18N
        btnFacturar.setMnemonic('f');
        btnFacturar.setName("facturar"); // NOI18N

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
        btnAceptar.setMnemonic('a');
        btnAceptar.setName("aceptar"); // NOI18N
        btnAceptar.setPreferredSize(new java.awt.Dimension(111, 41));

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N
        btnAddItem.setToolTipText("Agragar producto");
        btnAddItem.setName("add"); // NOI18N
        btnAddItem.setRequestFocusEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnDecrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arrow_down.png"))); // NOI18N
        btnDecrease.setToolTipText("Agragar producto");
        btnDecrease.setName("add"); // NOI18N
        btnDecrease.setRequestFocusEnabled(false);
        btnDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productosButtonPanelLayout = new javax.swing.GroupLayout(productosButtonPanel);
        productosButtonPanel.setLayout(productosButtonPanelLayout);
        productosButtonPanelLayout.setHorizontalGroup(
            productosButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        productosButtonPanelLayout.setVerticalGroup(
            productosButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(productosButtonPanel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Producto");

        tfProducto.setEditable(false);
        tfProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vuelto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pago");

        tfVuelto.setEditable(false);
        tfVuelto.setColumns(10);
        tfVuelto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfVuelto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfVuelto.setText("0.00");

        tfPago.setColumns(10);
        tfPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfPago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPagoKeyReleased(evt);
            }
        });

        rubroButtonPanel.setPreferredSize(new java.awt.Dimension(1000, 50));

        javax.swing.GroupLayout rubroButtonPanelLayout = new javax.swing.GroupLayout(rubroButtonPanel);
        rubroButtonPanel.setLayout(rubroButtonPanelLayout);
        rubroButtonPanelLayout.setHorizontalGroup(
            rubroButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        rubroButtonPanelLayout.setVerticalGroup(
            rubroButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(rubroButtonPanel);

        btnIncreaseCant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arrow_up.png"))); // NOI18N
        btnIncreaseCant.setToolTipText("Agragar producto");
        btnIncreaseCant.setName("add"); // NOI18N
        btnIncreaseCant.setRequestFocusEnabled(false);
        btnIncreaseCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseCantActionPerformed(evt);
            }
        });

        btnDecreaseCant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arrow_down.png"))); // NOI18N
        btnDecreaseCant.setToolTipText("Agragar producto");
        btnDecreaseCant.setName("add"); // NOI18N
        btnDecreaseCant.setRequestFocusEnabled(false);
        btnDecreaseCant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseCantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIncreaseCant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecreaseCant, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDecrease, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfVuelto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnAddItem)
                            .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(btnIncreaseCant)
                            .addComponent(btnDecreaseCant))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncrease)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDecrease)
                                .addGap(12, 12, 12)
                                .addComponent(btnDeleteItem))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
        tfCantidad.setSelectionStart(0);
    }//GEN-LAST:event_tfCantidadFocusGained

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void tfPrecioUnitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusLost

    }//GEN-LAST:event_tfPrecioUnitarioFocusLost

    private void tfPrecioUnitarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusGained
        tfPrecioUnitario.setSelectionStart(0);
    }//GEN-LAST:event_tfPrecioUnitarioFocusGained

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if (selectedProducto == null) {
            return;
        }
        Integer ca = Integer.valueOf(tfCantidad.getText());
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        BigDecimal precio = selectedProducto.getPrecioVenta();
        Double margen = Contabilidad.GET_MARGEN_SEGUN_LISTAPRECIOS(listaPrecio, selectedProducto, precio.doubleValue());
        precio = precio.add(BigDecimal.valueOf(margen));
        dtm.addRow(new Object[]{selectedProducto, selectedProducto.getNombre(), ca, precio, precio.multiply(BigDecimal.valueOf(ca))});
        calcularTotal();
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        Integer cant = (Integer) dtm.getValueAt(selectedRow, 2);
        BigDecimal $pre = (BigDecimal) dtm.getValueAt(selectedRow, 3);
        cant++;
        dtm.setValueAt(cant, selectedRow, 2);
        dtm.setValueAt($pre.multiply(BigDecimal.valueOf(cant)), selectedRow, 4);
        calcularTotal();
    }//GEN-LAST:event_btnIncreaseActionPerformed

    private void btnDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            return;
        }
        Integer cant = (Integer) dtm.getValueAt(selectedRow, 2);
        if (cant == 1) {
            return;
        }
        BigDecimal $pre = (BigDecimal) dtm.getValueAt(selectedRow, 3);
        cant--;
        dtm.setValueAt(cant, selectedRow, 2);
        dtm.setValueAt($pre.multiply(BigDecimal.valueOf(cant)), selectedRow, 4);
        calcularTotal();
    }//GEN-LAST:event_btnDecreaseActionPerformed

    private void tfPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPagoKeyReleased
        try {
            BigDecimal pago = new BigDecimal(tfPago.getText());
            BigDecimal total = new BigDecimal(tfTotal.getText());
            tfVuelto.setText(pago.subtract(total).toPlainString());
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tfPagoKeyReleased

    private void btnIncreaseCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseCantActionPerformed
        Integer i = Integer.valueOf(tfCantidad.getText());
        i++;
        tfCantidad.setText(i.toString());
    }//GEN-LAST:event_btnIncreaseCantActionPerformed

    private void btnDecreaseCantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseCantActionPerformed
        Integer i = Integer.valueOf(tfCantidad.getText());
        if (i == 1) {
            return;
        }
        i--;
        tfCantidad.setText(i.toString());
    }//GEN-LAST:event_btnDecreaseCantActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        UTIL.removeSelectedRows(jTable1);
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(JDVentaSimple.class.getSimpleName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDVentaSimple dialog = new JDVentaSimple(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnDecrease;
    private javax.swing.JButton btnDecreaseCant;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnIncrease;
    private javax.swing.JButton btnIncreaseCant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel productosButtonPanel;
    private javax.swing.JPanel rubroButtonPanel;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfPago;
    private javax.swing.JTextField tfPrecioUnitario;
    private javax.swing.JTextField tfProducto;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfVuelto;
    // End of variables declaration//GEN-END:variables

    private void calcularTotal() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        BigDecimal total = BigDecimal.ZERO;
        for (int row = 0; row < dtm.getRowCount(); row++) {
            BigDecimal x = (BigDecimal) dtm.getValueAt(row, 4);
            total = total.add(x);
        }
        tfTotal.setText(total.toPlainString());
    }

    public void loadRubros(final List<Rubro> rubros) {
        GridLayout layout = new GridLayout(1, 0);
        rubroButtonPanel.setLayout(layout);
        for (Rubro rubro : rubros) {
            final JButton btn = new JButton(rubro.getNombre(), null);
            btn.setFont(new Font("Tahoma", Font.BOLD, 14));
            btn.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    for (Rubro r : rubros) {
                        if (r.getNombre().equals(btn.getActionCommand())) {
                            buildProductosButtonPanel(r);
                            break;
                        }
                    }
                }

            });
            rubroButtonPanel.add(btn);
        }
    }

    private void buildProductosButtonPanel(Rubro rubro) {
        productosButtonPanel.removeAll();
        GridLayout layout = new GridLayout(0, 4, 10, 10);
        productosButtonPanel.setLayout(layout);
        productos = new ProductoJpaController().findBy(rubro);
        for (Producto p : productos) {
            ImageIcon ii = null;
            if (p.getFoto() != null) {
                if (p.getFoto().length > 0) {
                    ii = new ImageIcon(p.getFoto());
                    Image img = ii.getImage().getScaledInstance(60, 60, java.awt.Image.SCALE_SMOOTH);
                    ii = new ImageIcon(img);
                } else {
                    System.out.println("sin imagen: " + p.toString());
                }
            }
//                File foto = new File("./imgs/" + p.getCodigo() + ".jpg");
//            URL rsc = getClass().getResource("/jgestionclub/imgs/" + p.getCodigo().toLowerCase() + ".jpg");
//            if (rsc == null) {
//                rsc = getClass().getResource("/jgestionclub/imgs/" + p.getCodigo().toLowerCase() + ".png");
//            }
            final JButton btn = new JButton(p.getNombre(), ii);
            btn.setPreferredSize(new Dimension(50, 20));
            btn.setFont(new Font("Tahoma", Font.BOLD, 14));
            btn.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    for (Producto pp : productos) {
                        if (pp.getNombre().equals(btn.getActionCommand())) {
                            loadProductoInfo(pp);
                            break;
                        }
                    }
                }

            });
            productosButtonPanel.add(btn);
        }
        productosButtonPanel.revalidate();
        productosButtonPanel.repaint();
    }

    private void loadProductoInfo(Producto pp) {
        selectedProducto = pp;
        tfProducto.setText(pp.getNombre());
        tfCantidad.setText("1");
        BigDecimal precio = selectedProducto.getPrecioVenta();
        Double margen = Contabilidad.GET_MARGEN_SEGUN_LISTAPRECIOS(listaPrecio, selectedProducto, precio.doubleValue());
        precio = precio.add(BigDecimal.valueOf(margen));
        tfPrecioUnitario.setText(precio.toPlainString());
    }

}
