package jgestion.gui;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Window;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;

/**
 *
 * @author FiruzzZ
 */
public class JDNotaDebito extends javax.swing.JDialog {

    public JDNotaDebito(Window owner, boolean modal, boolean paraProveedor) {
        super(owner, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        initComponents();
        SwingUtil.addDigitsInputListener(tfCantidad, 6);
        SwingUtil.getInstance().getCharacterCountListener(tfObservacion, labelObservacionCharactersCount, 100);
        SwingUtil.getInstance().getCharacterCountListener(tfConcepto, labelConceptoCharactersCount, 200);
        this.setLocationRelativeTo(owner);
        if (paraProveedor) {
            setToProveedor();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosFacturacion = new javax.swing.JPanel();
        labelN_factura = new javax.swing.JLabel();
        labeFecha = new javax.swing.JLabel();
        tfFacturaCuarto = new javax.swing.JTextField();
        tfFacturaOcteto = new javax.swing.JTextField();
        labelLetra = new javax.swing.JLabel();
        cbFacturaTipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        btnCliente = new javax.swing.JButton();
        dcFechaFactura = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        cbSucursal = new javax.swing.JComboBox();
        tfObservacion = new javax.swing.JTextField();
        labelObservacion = new javax.swing.JLabel();
        labelObservacionCharactersCount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCAE = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tfGravado = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTotalIVA21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tfTotalDesc = new javax.swing.JTextField();
        tfTotalOtrosImps = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        tfDiferenciaRedondeo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tfTotalIVA105 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfTotalNoGravado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelDetalle = new javax.swing.JPanel();
        btnADD = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfConcepto = new javax.swing.JTextField();
        tfImporte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cbIVA = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfSubTotal = new javax.swing.JTextField();
        labelConceptoCharactersCount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nota de Débito");
        setResizable(false);

        panelDatosFacturacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos facturación"));

        labelN_factura.setText("Nº");

        labeFecha.setText("Fecha");

        tfFacturaCuarto.setEditable(false);
        tfFacturaCuarto.setColumns(4);
        tfFacturaCuarto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfFacturaCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFacturaCuarto.setText("0000");
        tfFacturaCuarto.setFocusable(false);
        tfFacturaCuarto.setRequestFocusEnabled(false);
        tfFacturaCuarto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFacturaCuartoFocusLost(evt);
            }
        });
        tfFacturaCuarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFacturaCuartoKeyTyped(evt);
            }
        });

        tfFacturaOcteto.setEditable(false);
        tfFacturaOcteto.setColumns(8);
        tfFacturaOcteto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfFacturaOcteto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfFacturaOcteto.setText("12345678");
        tfFacturaOcteto.setToolTipText("<html>\nDébido a la característica multi-usuario del sistema, el número de comprobante es representativo y puede\n<br> diferir del número final que se asignará una vez finalizada y aceptada la creación del mismo.\n</html>");
        tfFacturaOcteto.setFocusable(false);
        tfFacturaOcteto.setRequestFocusEnabled(false);
        tfFacturaOcteto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFacturaOctetoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFacturaOctetoFocusLost(evt);
            }
        });
        tfFacturaOcteto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFacturaOctetoKeyTyped(evt);
            }
        });

        labelLetra.setText("Letra");

        cbFacturaTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbFacturaTipo.setEnabled(false);
        cbFacturaTipo.setName("facturaLetra"); // NOI18N

        jLabel1.setText("Cliente");

        cbCliente.setName("cliente"); // NOI18N

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add.png"))); // NOI18N
        btnCliente.setName("btnClientes"); // NOI18N

        dcFechaFactura.setMaxSelectableDate(new java.util.Date(4070923260000L));
        dcFechaFactura.setMinSelectableDate(new java.util.Date(-2208969732000L));

        jLabel2.setText("Sucursal");

        cbSucursal.setName("sucursal"); // NOI18N

        labelObservacion.setText("Observación");

        labelObservacionCharactersCount.setText("0/100");
        labelObservacionCharactersCount.setFocusable(false);
        labelObservacionCharactersCount.setRequestFocusEnabled(false);

        jLabel7.setText("CAE");

        tfCAE.setEditable(false);
        tfCAE.setToolTipText("Código de Autorización Eletrónico");

        javax.swing.GroupLayout panelDatosFacturacionLayout = new javax.swing.GroupLayout(panelDatosFacturacion);
        panelDatosFacturacion.setLayout(panelDatosFacturacionLayout);
        panelDatosFacturacionLayout.setHorizontalGroup(
            panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelObservacion)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLetra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelN_factura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labeFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCAE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                                .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelObservacionCharactersCount)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosFacturacionLayout.setVerticalGroup(
            panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFacturacionLayout.createSequentialGroup()
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLetra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelN_factura)
                        .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labeFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObservacion)
                    .addComponent(labelObservacionCharactersCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel23.setText("Gravado");

        tfGravado.setEditable(false);
        tfGravado.setColumns(8);
        tfGravado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfGravado.setText("0.00");
        tfGravado.setFocusable(false);

        tfTotal.setEditable(false);
        tfTotal.setColumns(10);
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotal.setText("0.00");
        tfTotal.setFocusable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Total");

        jLabel25.setText("  IVA 21%");

        tfTotalIVA21.setEditable(false);
        tfTotalIVA21.setColumns(6);
        tfTotalIVA21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalIVA21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalIVA21.setText("0.00");
        tfTotalIVA21.setFocusable(false);

        jLabel27.setText("Desc.");

        tfTotalDesc.setEditable(false);
        tfTotalDesc.setColumns(6);
        tfTotalDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalDesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalDesc.setText("0.00");
        tfTotalDesc.setFocusable(false);

        tfTotalOtrosImps.setEditable(false);
        tfTotalOtrosImps.setColumns(6);
        tfTotalOtrosImps.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalOtrosImps.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalOtrosImps.setText("0.00");
        tfTotalOtrosImps.setFocusable(false);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Otros Imps.");

        tfDiferenciaRedondeo.setEditable(false);
        tfDiferenciaRedondeo.setColumns(10);
        tfDiferenciaRedondeo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfDiferenciaRedondeo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfDiferenciaRedondeo.setText("0.00");
        tfDiferenciaRedondeo.setToolTipText("<html>\nIndica la perdida o ganancia por redondeo:\n<br>Positivo: a favor del comerciante.\n<br>Negativo: del Cliente (comprador).\n<br><b>Este item SOLO es visible en las Facturas que no discriminan impuestos/alicuotas</b>\n</html>\n");
        tfDiferenciaRedondeo.setFocusable(false);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Dif. Redondeo");

        tfTotalIVA105.setEditable(false);
        tfTotalIVA105.setColumns(6);
        tfTotalIVA105.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalIVA105.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalIVA105.setText("0.00");
        tfTotalIVA105.setFocusable(false);

        jLabel26.setText("IVA 10,5%");

        tfTotalNoGravado.setEditable(false);
        tfTotalNoGravado.setColumns(6);
        tfTotalNoGravado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalNoGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalNoGravado.setText("0.00");
        tfTotalNoGravado.setFocusable(false);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("No Gravado");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotalOtrosImps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(tfTotalNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiferenciaRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDiferenciaRedondeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalOtrosImps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalNoGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)))
                .addContainerGap())
        );

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_editdelete.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.setName("facturar"); // NOI18N

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
        btnAceptar.setMnemonic('a');
        btnAceptar.setText("Aceptar");
        btnAceptar.setName("aceptar"); // NOI18N
        btnAceptar.setPreferredSize(new java.awt.Dimension(111, 41));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_button_cancel.png"))); // NOI18N
        btnCancelar.setMnemonic('c');
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("cancelar"); // NOI18N

        jScrollPane1.setAutoscrolls(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        panelDetalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnADD.setToolTipText("Agragar producto");
        btnADD.setName("add"); // NOI18N
        btnADD.setRequestFocusEnabled(false);
        btnADD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnADDFocusLost(evt);
            }
        });

        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        btnDEL.setToolTipText("Quitar producto");
        btnDEL.setName("del"); // NOI18N
        btnDEL.setRequestFocusEnabled(false);

        jLabel3.setText("Concepto");

        jLabel4.setText("Importe");

        tfImporte.setColumns(8);
        tfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfImporte.setName("productoPrecio"); // NOI18N

        jLabel17.setText("IVA %");

        jLabel5.setText("Sub Total");

        tfSubTotal.setEditable(false);
        tfSubTotal.setColumns(8);
        tfSubTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSubTotal.setFocusable(false);

        labelConceptoCharactersCount.setText("0/200");
        labelConceptoCharactersCount.setFocusable(false);
        labelConceptoCharactersCount.setRequestFocusEnabled(false);

        jLabel6.setText("Cantidad");

        tfCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelDetalleLayout = new javax.swing.GroupLayout(panelDetalle);
        panelDetalle.setLayout(panelDetalleLayout);
        panelDetalleLayout.setHorizontalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetalleLayout.createSequentialGroup()
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetalleLayout.createSequentialGroup()
                        .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfConcepto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleLayout.createSequentialGroup()
                                .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConceptoCharactersCount)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelDetalleLayout.setVerticalGroup(
            panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetalleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConceptoCharactersCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17)
                    .addComponent(cbIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addComponent(panelDetalle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDatosFacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDatosFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFacturaOctetoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaOctetoFocusGained
        ((JTextComponent) tfFacturaOcteto).selectAll();
    }//GEN-LAST:event_tfFacturaOctetoFocusGained

    private void tfFacturaOctetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaOctetoFocusLost
        String x = UTIL.AGREGAR_CEROS(tfFacturaOcteto.getText(), 8);
        tfFacturaOcteto.setText(x);
    }//GEN-LAST:event_tfFacturaOctetoFocusLost

    private void tfFacturaOctetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaOctetoKeyTyped
        SwingUtil.checkInputDigit(evt, 8);
    }//GEN-LAST:event_tfFacturaOctetoKeyTyped

    private void btnADDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnADDFocusLost
        tfConcepto.requestFocusInWindow();
    }//GEN-LAST:event_btnADDFocusLost

    private void tfFacturaCuartoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaCuartoKeyTyped
        SwingUtil.checkInputDigit(evt, false, 4);
    }//GEN-LAST:event_tfFacturaCuartoKeyTyped

    private void tfFacturaCuartoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaCuartoFocusLost
        String x = UTIL.AGREGAR_CEROS(tfFacturaCuarto.getText(), 4);
        tfFacturaCuarto.setText(x);
    }//GEN-LAST:event_tfFacturaCuartoFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnDEL;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbFacturaTipo;
    private javax.swing.JComboBox cbIVA;
    private javax.swing.JComboBox cbSucursal;
    private com.toedter.calendar.JDateChooser dcFechaFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labeFecha;
    private javax.swing.JLabel labelConceptoCharactersCount;
    private javax.swing.JLabel labelLetra;
    private javax.swing.JLabel labelN_factura;
    private javax.swing.JLabel labelObservacion;
    private javax.swing.JLabel labelObservacionCharactersCount;
    private javax.swing.JPanel panelDatosFacturacion;
    private javax.swing.JPanel panelDetalle;
    private javax.swing.JTextField tfCAE;
    private javax.swing.JTextField tfCantidad;
    private javax.swing.JTextField tfConcepto;
    private javax.swing.JTextField tfDiferenciaRedondeo;
    private javax.swing.JTextField tfFacturaCuarto;
    private javax.swing.JTextField tfFacturaOcteto;
    private javax.swing.JTextField tfGravado;
    private javax.swing.JTextField tfImporte;
    private javax.swing.JTextField tfObservacion;
    private javax.swing.JTextField tfSubTotal;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalDesc;
    private javax.swing.JTextField tfTotalIVA105;
    private javax.swing.JTextField tfTotalIVA21;
    private javax.swing.JTextField tfTotalNoGravado;
    private javax.swing.JTextField tfTotalOtrosImps;
    // End of variables declaration//GEN-END:variables

    private void setToProveedor() {
        jLabel1.setText("Proveedor");
        jLabel2.setVisible(false);
        cbSucursal.setVisible(false);
        tfFacturaCuarto.setEditable(true);
        tfFacturaCuarto.setText("");
        tfFacturaCuarto.setFocusable(true);
        tfFacturaCuarto.setRequestFocusEnabled(true);
        tfFacturaOcteto.setEditable(true);
        tfFacturaOcteto.setText("");
        tfFacturaOcteto.setFocusable(true);
        tfFacturaOcteto.setRequestFocusEnabled(true);
    }

    public JButton getBtnADD() {
        return btnADD;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnAnular() {
        return btnAnular;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnCliente() {
        return btnCliente;
    }

    public JButton getBtnDEL() {
        return btnDEL;
    }

    public JComboBox getCbCliente() {
        return cbCliente;
    }

    public JComboBox getCbFacturaTipo() {
        return cbFacturaTipo;
    }

    public JComboBox getCbIVA() {
        return cbIVA;
    }

    public JComboBox getCbSucursal() {
        return cbSucursal;
    }

    public JDateChooser getDcFechaFactura() {
        return dcFechaFactura;
    }

    public JTextField getTfConcepto() {
        return tfConcepto;
    }

    public JTextField getTfDiferenciaRedondeo() {
        return tfDiferenciaRedondeo;
    }

    public JTextField getTfFacturaCuarto() {
        return tfFacturaCuarto;
    }

    public JTextField getTfFacturaOcteto() {
        return tfFacturaOcteto;
    }

    public JTextField getTfGravado() {
        return tfGravado;
    }

    public JTextField getTfImporte() {
        return tfImporte;
    }

    public JTextField getTfObservacion() {
        return tfObservacion;
    }

    public JTextField getTfSubTotal() {
        return tfSubTotal;
    }

    public JTextField getTfTotal() {
        return tfTotal;
    }

    public JTextField getTfTotalDesc() {
        return tfTotalDesc;
    }

    public JTextField getTfTotalIVA105() {
        return tfTotalIVA105;
    }

    public JTextField getTfTotalIVA21() {
        return tfTotalIVA21;
    }

    public JTextField getTfTotalNoGravado() {
        return tfTotalNoGravado;
    }

    public JTextField getTfTotalOtrosImps() {
        return tfTotalOtrosImps;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JPanel getPanelDatosFacturacion() {
        return panelDatosFacturacion;
    }

    public JPanel getPanelDetalle() {
        return panelDetalle;
    }

    public JTextField getTfCantidad() {
        return tfCantidad;
    }

    public JTextField getTfCAE() {
        return tfCAE;
    }
}
