/*
 * PanelNumeracionActual.java
 *
 * Created on 13/04/2012, 10:54:08
 */
package jgestion.gui;

import javax.swing.JTextField;

/**
 *
 * @author FiruzzZ
 */
public class PanelNumeracionActual extends javax.swing.JPanel {

    /**
     * Creates new form PanelNumeracionActual
     */
    public PanelNumeracionActual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        tfInicialNotaCredito = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfInicialReciboA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tfInicialFacturaB = new javax.swing.JTextField();
        tfInicialFacturaA = new javax.swing.JTextField();
        tfInicialRemito = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfInicialNotaDebitoA = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfInicialNotaDebitoB = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfInicialFacturaC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfFactuA_AFIP = new javax.swing.JTextField();
        tfFactuB_AFIP = new javax.swing.JTextField();
        tfFactuC_AFIP = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        tfReciboA_AFIP = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfInicialReciboB = new javax.swing.JTextField();
        tfReciboB_AFIP = new javax.swing.JTextField();
        tfInicialReciboC = new javax.swing.JTextField();
        tfReciboC_AFIP = new javax.swing.JTextField();

        jLabel20.setText("Nota Crédito");

        tfInicialNotaCredito.setEditable(false);
        tfInicialNotaCredito.setColumns(8);
        tfInicialNotaCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel19.setText("Recibo \"A\"");

        tfInicialReciboA.setEditable(false);
        tfInicialReciboA.setColumns(8);
        tfInicialReciboA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfInicialReciboA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInicialReciboAActionPerformed(evt);
            }
        });

        jLabel16.setText("Factura \"A\"");

        jLabel17.setText("Factura \"B\"");

        jLabel18.setText("Remito");

        tfInicialFacturaB.setEditable(false);
        tfInicialFacturaB.setColumns(8);
        tfInicialFacturaB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfInicialFacturaA.setEditable(false);
        tfInicialFacturaA.setColumns(8);
        tfInicialFacturaA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfInicialRemito.setEditable(false);
        tfInicialRemito.setColumns(8);
        tfInicialRemito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel21.setText("Nota Débito \"A\"");

        tfInicialNotaDebitoA.setEditable(false);
        tfInicialNotaDebitoA.setColumns(8);
        tfInicialNotaDebitoA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel22.setText("Nota Débito \"B\"");

        tfInicialNotaDebitoB.setEditable(false);
        tfInicialNotaDebitoB.setColumns(8);
        tfInicialNotaDebitoB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel23.setText("Factura \"C\"");

        tfInicialFacturaC.setEditable(false);
        tfInicialFacturaC.setColumns(8);
        tfInicialFacturaC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AFIP Números");

        tfFactuA_AFIP.setEditable(false);
        tfFactuA_AFIP.setColumns(8);
        tfFactuA_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfFactuB_AFIP.setEditable(false);
        tfFactuB_AFIP.setColumns(8);
        tfFactuB_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfFactuC_AFIP.setEditable(false);
        tfFactuC_AFIP.setColumns(8);
        tfFactuC_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField4.setEditable(false);
        jTextField4.setColumns(8);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField5.setEditable(false);
        jTextField5.setColumns(8);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfReciboA_AFIP.setEditable(false);
        tfReciboA_AFIP.setColumns(8);
        tfReciboA_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField7.setEditable(false);
        jTextField7.setColumns(8);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextField8.setEditable(false);
        jTextField8.setColumns(8);
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel24.setText("Recibo \"B\"");

        jLabel25.setText("Recibo \"C\"");

        tfInicialReciboB.setEditable(false);
        tfInicialReciboB.setColumns(8);
        tfInicialReciboB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfInicialReciboB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInicialReciboBActionPerformed(evt);
            }
        });

        tfReciboB_AFIP.setEditable(false);
        tfReciboB_AFIP.setColumns(8);
        tfReciboB_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfInicialReciboC.setEditable(false);
        tfInicialReciboC.setColumns(8);
        tfInicialReciboC.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfInicialReciboC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInicialReciboCActionPerformed(evt);
            }
        });

        tfReciboC_AFIP.setEditable(false);
        tfReciboC_AFIP.setColumns(8);
        tfReciboC_AFIP.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialNotaDebitoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialFacturaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFactuB_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialFacturaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFactuC_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialFacturaA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFactuA_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfInicialNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfInicialNotaDebitoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialReciboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfReciboA_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialReciboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfReciboB_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInicialReciboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfReciboC_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(tfInicialFacturaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFactuA_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel17)
                    .addComponent(tfInicialFacturaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFactuB_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfInicialFacturaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFactuC_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfInicialRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfInicialNotaDebitoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel19)
                    .addComponent(tfInicialReciboA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReciboA_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel24)
                    .addComponent(tfInicialReciboB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfReciboB_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfReciboC_AFIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInicialReciboC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInicialNotaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInicialNotaDebitoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfInicialReciboAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInicialReciboAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInicialReciboAActionPerformed

    private void tfInicialReciboBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInicialReciboBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInicialReciboBActionPerformed

    private void tfInicialReciboCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInicialReciboCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInicialReciboCActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField tfFactuA_AFIP;
    private javax.swing.JTextField tfFactuB_AFIP;
    private javax.swing.JTextField tfFactuC_AFIP;
    private javax.swing.JTextField tfInicialFacturaA;
    private javax.swing.JTextField tfInicialFacturaB;
    private javax.swing.JTextField tfInicialFacturaC;
    private javax.swing.JTextField tfInicialNotaCredito;
    private javax.swing.JTextField tfInicialNotaDebitoA;
    private javax.swing.JTextField tfInicialNotaDebitoB;
    private javax.swing.JTextField tfInicialReciboA;
    private javax.swing.JTextField tfInicialReciboB;
    private javax.swing.JTextField tfInicialReciboC;
    private javax.swing.JTextField tfInicialRemito;
    private javax.swing.JTextField tfReciboA_AFIP;
    private javax.swing.JTextField tfReciboB_AFIP;
    private javax.swing.JTextField tfReciboC_AFIP;
    // End of variables declaration//GEN-END:variables

    public void setTfInicialFacturaA(String numero) {
        this.tfInicialFacturaA.setText(numero);
    }

    public void setTfInicialFacturaB(String numero) {
        this.tfInicialFacturaB.setText(numero);
    }

    public void setTfInicialFacturaC(String numero) {
        this.tfInicialFacturaC.setText(numero);
    }

    public void setTfInicialNotaCredito(String numero) {
        this.tfInicialNotaCredito.setText(numero);
    }

    public void setTfInicialNotaDebitoA(String numero) {
        this.tfInicialNotaDebitoA.setText(numero);
    }

    public void setTfInicialNotaDebitoB(String numero) {
        this.tfInicialNotaDebitoB.setText(numero);
    }

    public void setTfInicialReciboA(String numero) {
        this.tfInicialReciboA.setText(numero);
    }

    public void setTfInicialReciboB(String numero) {
        this.tfInicialReciboB.setText(numero);
    }

    public void setTfInicialReciboC(String numero) {
        this.tfInicialReciboC.setText(numero);
    }

    public void setTfInicialRemito(String numero) {
        this.tfInicialRemito.setText(numero);
    }

    public JTextField getTfFactuA_AFIP() {
        return tfFactuA_AFIP;
    }

    public JTextField getTfFactuB_AFIP() {
        return tfFactuB_AFIP;
    }

    public JTextField getTfFactuC_AFIP() {
        return tfFactuC_AFIP;
    }
}
