
/*
 * PanelSetting.java
 *
 * Created on 15/07/2011, 09:43:09
 */
package jgestion.gui;

import com.toedter.calendar.JDateChooser;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author FiruzzZ
 */
public class WSFEVerificacionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PanelSetting
     */
    public WSFEVerificacionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbConceptos = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbComprobantes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbDocumentos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbMonendas = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tfCotizacion = new javax.swing.JTextField();
        btnGetCotizAFIP = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        tfTotalNeto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfTotalIVAs = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tfTotalTributos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        tfDocNumero = new javax.swing.JTextField();
        dcServDesde = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dcServHasta = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfCbteNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbTributos = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        dcFechaCbte = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setText("Concepto");

        cbConceptos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConceptosActionPerformed(evt);
            }
        });

        jLabel1.setText("Comprobante");

        cbComprobantes.setEnabled(false);

        jLabel3.setText("Documento");

        cbDocumentos.setEnabled(false);

        jLabel5.setText("Moneda");

        cbMonendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonendasActionPerformed(evt);
            }
        });

        jLabel8.setText("Cotización");

        tfCotizacion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCotizacion.setText("1");
        tfCotizacion.setEnabled(false);

        btnGetCotizAFIP.setText("Cotz. AFIP");
        btnGetCotizAFIP.setToolTipText("Obtener cotización según la AFIP");
        btnGetCotizAFIP.setEnabled(false);

        jLabel23.setText("$ Neto");

        tfTotalNeto.setEditable(false);
        tfTotalNeto.setColumns(6);
        tfTotalNeto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalNeto.setText("0.00");

        jLabel26.setText("$ Imp. IVA");

        tfTotalIVAs.setEditable(false);
        tfTotalIVAs.setColumns(6);
        tfTotalIVAs.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalIVAs.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalIVAs.setText("0.00");

        jLabel25.setText("$ Imp Tributos");

        tfTotalTributos.setEditable(false);
        tfTotalTributos.setColumns(6);
        tfTotalTributos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalTributos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalTributos.setText("0.00");

        jLabel24.setText("$ Total");

        tfTotal.setEditable(false);
        tfTotal.setColumns(8);
        tfTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotal.setText("0.00");

        tfDocNumero.setEditable(false);
        tfDocNumero.setColumns(10);
        tfDocNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        dcServDesde.setEnabled(false);

        jLabel4.setText("Servicio");

        jLabel6.setText("hasta");

        dcServHasta.setEnabled(false);

        jLabel7.setText("desde");

        jLabel9.setText("N°");

        tfCbteNumero.setEditable(false);
        tfCbteNumero.setColumns(10);
        tfCbteNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setText("Tributos");

        jLabel11.setText("Fecha Cbte");

        jLabel12.setText("N°");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTotalNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTotalIVAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfTotalTributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfCbteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfDocNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cbTributos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbMonendas, javax.swing.GroupLayout.Alignment.LEADING, 0, 143, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGetCotizAFIP))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dcFechaCbte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcServDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcServHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbConceptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dcServDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(dcServHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(dcFechaCbte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbComprobantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfCbteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDocNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbMonendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetCotizAFIP))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbTributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTotalIVAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTotalNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotalTributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void cbConceptosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConceptosActionPerformed
    boolean visible = (cbConceptos.getSelectedIndex() > 0);
    dcServDesde.setEnabled(visible);
    dcServHasta.setEnabled(visible);
}//GEN-LAST:event_cbConceptosActionPerformed

private void cbMonendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonendasActionPerformed
    tfCotizacion.setEnabled(cbMonendas.getSelectedIndex() > 0);
    btnGetCotizAFIP.setEnabled(cbMonendas.getSelectedIndex() > 0);
}//GEN-LAST:event_cbMonendasActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetCotizAFIP;
    private javax.swing.JComboBox cbComprobantes;
    private javax.swing.JComboBox cbConceptos;
    private javax.swing.JComboBox cbDocumentos;
    private javax.swing.JComboBox cbMonendas;
    private javax.swing.JComboBox cbTributos;
    private com.toedter.calendar.JDateChooser dcFechaCbte;
    private com.toedter.calendar.JDateChooser dcServDesde;
    private com.toedter.calendar.JDateChooser dcServHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfCbteNumero;
    private javax.swing.JTextField tfCotizacion;
    private javax.swing.JTextField tfDocNumero;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalIVAs;
    private javax.swing.JTextField tfTotalNeto;
    private javax.swing.JTextField tfTotalTributos;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnGetCotizAFIP() {
        return btnGetCotizAFIP;
    }

    public JComboBox getCbComprobantes() {
        return cbComprobantes;
    }

    public JComboBox getCbConceptos() {
        return cbConceptos;
    }

    public JComboBox getCbDocumentos() {
        return cbDocumentos;
    }

    public JComboBox getCbMonendas() {
        return cbMonendas;
    }

    public JTextField getTfCotizacion() {
        return tfCotizacion;
    }

    public JTextField getTfDocNumero() {
        return tfDocNumero;
    }

    public JTextField getTfTotal() {
        return tfTotal;
    }

    public JTextField getTfTotalIVAs() {
        return tfTotalIVAs;
    }

    public JTextField getTfTotalNeto() {
        return tfTotalNeto;
    }

    public JTextField getTfTotalTributos() {
        return tfTotalTributos;
    }

    public Date getDcServDesde() {
        return dcServDesde.getDate();
    }

    public Date getDcServHasta() {
        return dcServHasta.getDate();
    }

    public JTextField getTfCbteNumero() {
        return tfCbteNumero;
    }

    public JComboBox getCbTributos() {
        return cbTributos;
    }

    public JDateChooser getDcFechaCbte() {
        return dcFechaCbte;
    }

}
