
/*
 * JDBuscador.java
 *
 * Created on 05/05/2010, 17:54:59
 */
package gui;

import java.awt.Dialog;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JTable;

/**
 *
 * @author FiruzzZ
 */
public class JDBuscador extends javax.swing.JDialog {

   /** Creates new form JDBuscador */
   public JDBuscador(java.awt.Frame parent, boolean modal, javax.swing.JPanel panel, String title) {
      super(parent, modal);
      this.setTitle(title);
      this.getContentPane().add(panel, java.awt.BorderLayout.NORTH);
      pack();
      initComponents();
      ajustarAlPanel();
   }

   public JDBuscador(Dialog owner, boolean modal, javax.swing.JPanel panel, String title) {
      super(owner, modal);
      this.setTitle(title);
      this.getContentPane().add(panel, java.awt.BorderLayout.NORTH);
      pack();
      initComponents();
      ajustarAlPanel();
   }

   private void ajustarAlPanel() {
      this.setSize(panel.getWidth() + 220, this.getHeight());
      this.setMinimumSize(new java.awt.Dimension(this.getWidth(), this.getHeight()));
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      bLimpiar = new javax.swing.JButton();
      bBuscar = new javax.swing.JButton();
      bImprimir = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      panel = new javax.swing.JPanel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/broom32x32.png"))); // NOI18N
      bLimpiar.setText("Limpiar");
      bLimpiar.setFocusable(false);
      bLimpiar.setName("limpiarBuscador"); // NOI18N

      bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
      bBuscar.setText("Buscar");
      bBuscar.setName("buscarBuscador"); // NOI18N

      bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/impresora.png"))); // NOI18N
      bImprimir.setText("Imprimir");
      bImprimir.setName("imprimirBuscador"); // NOI18N

      jTable1.setModel(new javax.swing.table.DefaultTableModel());
      jScrollPane1.setViewportView(jTable1);

      javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
      panel.setLayout(panelLayout);
      panelLayout.setHorizontalGroup(
         panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 359, Short.MAX_VALUE)
      );
      panelLayout.setVerticalGroup(
         panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 121, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(bImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(bLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bBuscar;
   private javax.swing.JButton bImprimir;
   private javax.swing.JButton bLimpiar;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   private javax.swing.JPanel panel;
   // End of variables declaration//GEN-END:variables

   public void setListener(Object o) {
      bBuscar.addActionListener((ActionListener) o);
      bImprimir.addActionListener((ActionListener) o);
      bLimpiar.addActionListener((ActionListener) o);
      try {
         jTable1.addMouseListener((MouseListener) o);
      } catch (ClassCastException ex) {
         System.out.println("ERROR: " + ex.getClass().toString().toUpperCase()
                 + ": Culpa de ->"
                 + o.getClass() + "\nMSG: " + ex.getMessage());
      }
   }

   public JTable getjTable1() {
      return jTable1;
   }

   public javax.swing.table.DefaultTableModel getDtm() {
      return (javax.swing.table.DefaultTableModel) jTable1.getModel();
   }

   public void hideImprimir() {
      bImprimir.setVisible(false);
   }

   public void hideLimpiar() {
      bLimpiar.setVisible(false);
   }
}
