package gui;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooserCellEditor;
import controller.BancoController;
import controller.CuentaBancaria;
import controller.UsuarioController;
import controller.exceptions.MessageException;
import entity.Banco;
import entity.CuentabancariaMovimientos;
import entity.OperacionesBancarias;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jgestion.JGestionUtils;
import jpa.controller.CuentabancariaMovimientosJpaController;
import jpa.controller.OperacionesBancariasJpaController;
import org.bushe.swing.action.ActionList;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;
import utilities.swing.components.ComboBoxWrapper;
import utilities.swing.components.FormatRenderer;
import utilities.swing.components.NumberRenderer;

/**
 *
 * @author FiruzzZ
 */
public class JDCuentabancariaManager extends javax.swing.JDialog {

    private JDABM abm;

    public JDCuentabancariaManager(Window owner) {
        super(owner, ModalityType.APPLICATION_MODAL);
        initComponents();
        otroInit();
    }

    private void otroInit() {
        UTIL.loadComboBox(cbBancos, JGestionUtils.getWrappedBancos(new BancoController().findWithCuentasBancarias()), true, "<No existen banco con cuenta bancaria asociada>");
        List<ComboBoxWrapper<OperacionesBancarias>> l = JGestionUtils.getWrappedOperacionesBancarias(new OperacionesBancariasJpaController().findAll());
        UTIL.loadComboBox(cbOperacionesBancariasFiltro, l, true);
        UTIL.loadComboBox(cbOperacionesBancarias, l, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgFechas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbBancos = new javax.swing.JComboBox();
        cbCuentabancaria = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbOperacionesBancariasFiltro = new javax.swing.JComboBox();
        rbOperacion = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        dcDesde = new com.toedter.calendar.JDateChooser();
        dcHasta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        tfTotalCredito = new javax.swing.JTextField();
        tfTotalDebito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbOperacionesBancarias = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();

        bgFechas.add(rbOperacion);
        bgFechas.add(jRadioButton2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("N° Cuenta");

        jLabel10.setText("Banco");

        cbBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBancosActionPerformed(evt);
            }
        });

        jLabel2.setText("Operación");

        rbOperacion.setSelected(true);
        rbOperacion.setText("F. Operación");

        jRadioButton2.setText("F. Débito/Crédito");

        jLabel3.setText("Desde");

        jLabel4.setText("Hasta");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Descrip. Mov", "Crédito", "Débito", "Fecha Cré/Déb", "Concepto. Op.", "Fecha Op.", "Usuario", "F. Sistema"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(1).setMinWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(NumberRenderer.getCurrencyRenderer());
        jTable1.getColumnModel().getColumn(4).setMinWidth(60);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(4).setCellEditor(new JDateChooserCellEditor());
        jTable1.getColumnModel().getColumn(4).setCellRenderer(FormatRenderer.getDateRenderer());
        jTable1.getColumnModel().getColumn(6).setResizable(false);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(FormatRenderer.getDateRenderer());
        jTable1.getColumnModel().getColumn(7).setResizable(false);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(8).setResizable(false);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(60);
        jTable1.getColumnModel().getColumn(8).setCellRenderer(FormatRenderer.getDateTimeRenderer());

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setName("buscarBuscador"); // NOI18N

        tfTotalCredito.setEditable(false);
        tfTotalCredito.setColumns(10);
        tfTotalCredito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalCredito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tfTotalDebito.setEditable(false);
        tfTotalDebito.setColumns(10);
        tfTotalDebito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfTotalDebito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Crédito");

        jLabel15.setText("Débito");

        jLabel7.setText("Operación Bancaria");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add_circular.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBancos, 0, 309, Short.MAX_VALUE)
                            .addComponent(cbCuentabancaria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbOperacionesBancariasFiltro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbOperacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(btnBuscar))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbOperacionesBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbOperacion)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(dcDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(dcHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(cbBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(cbCuentabancaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cbOperacionesBancariasFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotalDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbOperacionesBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void cbBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBancosActionPerformed
        if (cbBancos.getItemCount() > 0) {
            if (cbBancos.getSelectedIndex() > 0) {
                Banco b = ((ComboBoxWrapper<Banco>) cbBancos.getSelectedItem()).getEntity();
                UTIL.loadComboBox(cbCuentabancaria, JGestionUtils.getWrappedCuentasBancarias(b.getCuentasbancaria()), true);
            } else {
                UTIL.loadComboBox(cbCuentabancaria, null, true, "<Todas las cuentas bancarias de todos los bancos>");
            }
        } else {
            UTIL.loadComboBox(cbCuentabancaria, null, true);
        }
    }//GEN-LAST:event_cbBancosActionPerformed

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        sumarCreditoDebito();
    }//GEN-LAST:event_jTable1ComponentResized

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        @SuppressWarnings("unchecked")
        OperacionesBancarias op = ((ComboBoxWrapper<OperacionesBancarias>) cbOperacionesBancarias.getSelectedItem()).getEntity();
        if (op.getNombre().equalsIgnoreCase("DEPÓSITO")) {
            displayDepositoGUI();
        } else if (op.getNombre().equalsIgnoreCase("EXTRACCIÓN")) {
        } else if (op.getNombre().equalsIgnoreCase("TRANSFERENCIA")) {
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgFechas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cbBancos;
    private javax.swing.JComboBox cbCuentabancaria;
    private javax.swing.JComboBox cbOperacionesBancarias;
    private javax.swing.JComboBox cbOperacionesBancariasFiltro;
    private com.toedter.calendar.JDateChooser dcDesde;
    private com.toedter.calendar.JDateChooser dcHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbOperacion;
    private javax.swing.JTextField tfTotalCredito;
    private javax.swing.JTextField tfTotalDebito;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

    public JButton getBtnAgregar() {
        return btnAgregar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JComboBox getCbBancos() {
        return cbBancos;
    }

    public JComboBox getCbCuentabancaria() {
        return cbCuentabancaria;
    }

    public JComboBox getCbOperacionesBancariasFiltro() {
        return cbOperacionesBancariasFiltro;
    }

    public Date getDcDesde() {
        return dcDesde.getDate();
    }

    public Date getDcHasta() {
        return dcHasta.getDate();
    }

    public boolean getRbOperacion() {
        return rbOperacion.isSelected();
    }

    public void sumarCreditoDebito() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        BigDecimal c = BigDecimal.ZERO;
        BigDecimal d = BigDecimal.ZERO;
        for (int row = 0; row < dtm.getRowCount(); row++) {
            c = c.add((BigDecimal) dtm.getValueAt(row, 2));
            d = d.add((BigDecimal) dtm.getValueAt(row, 3));
        }
        tfTotalCredito.setText(UTIL.DECIMAL_FORMAT.format(c));
        tfTotalDebito.setText(UTIL.DECIMAL_FORMAT.format(d));
    }

    private void displayDepositoGUI() {
        final PanelOperacionBancariaDeposito panelDeposito = new PanelOperacionBancariaDeposito();
        abm = new JDABM(this, "Depósito", true, panelDeposito);
        abm.getbAceptar().addActionListener(new ActionListener() {
            @Override
            @SuppressWarnings("unchecked")
            public void actionPerformed(ActionEvent e) {
                try {
                    CuentaBancaria cb;
                    BigDecimal monto;
                    try {
                        cb = ((ComboBoxWrapper<CuentaBancaria>) panelDeposito.getCbBancos().getSelectedItem()).getEntity();
                    } catch (ClassCastException ex) {
                        throw new MessageException("Cuenta bancanria no válida");
                    }
                    try {
                        monto = new BigDecimal(panelDeposito.getTfDebe().getText());
                    } catch (Exception ex) {
                        throw new MessageException("Importe no válido, ingrese solo números y utilice el punto como separador decimal");
                    }
                    String descrip = panelDeposito.getTfDescripcionMov().getText();
                    Date fechaCre = panelDeposito.getDcFechaCreditoDebito().getDate();
                    Date fechaOP = panelDeposito.getDcFechaOperacion().getDate();
                    OperacionesBancarias op = ((ComboBoxWrapper<OperacionesBancarias>) cbOperacionesBancarias.getSelectedItem()).getEntity();
                    CuentabancariaMovimientos cbm = new CuentabancariaMovimientos(fechaOP, descrip, fechaCre, monto, BigDecimal.ZERO, false, UsuarioController.getCurrentUser(), op, cb, null, null);
                    new CuentabancariaMovimientosJpaController().create(cbm);
                    abm.showMessage("operación n° " + cbm.getId() +" realizada", null, 1);
                } catch (MessageException ex) {
                    ex.displayMessage(abm);
                }
            }
        });
        abm.getbCancelar().addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abm.dispose();
            }
        });
        abm.setLocationRelativeTo(this);
        abm.setVisible(true);
    }
}
