/*
 * JDVenta.java
 *
 * Created on 25/11/2009, 18:46:25
 */

package gui;

import controller.Valores;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class JDFacturaVenta extends javax.swing.JDialog {
   private final int modoVista;

   /** Creates new form JDVenta */
   public JDFacturaVenta(java.awt.Frame parent, boolean modal, int factVenta1_Presup2_Remito3) {
      super(parent, modal);
      modoVista = factVenta1_Presup2_Remito3;
      initComponents();
      if (factVenta1_Presup2_Remito3 != 1) {
         this.setTitle("Remito");
         labelN_factura.setText("Nº Remito");
         btnAceptar.setText("Aceptar");
         btnFacturar.setVisible(false);
         labelLetra.setVisible(false);
         cbFacturaTipo.setVisible(false);
         labelCaja.setVisible(false);
         cbCaja.setVisible(false);
         labelRemito.setVisible(false);      // Referente
         tfRemito.setVisible(false);         //    a
         btnBuscarRemito.setVisible(false);  // Remito
         if (factVenta1_Presup2_Remito3 == 2) {
            this.setTitle("Presupuesto de Venta");
            labelN_factura.setVisible(false);
            tfFacturaCuarto.setVisible(false);
            tfFacturaOcteto.setVisible(false);
            labeFecha.setVisible(false);
            dcFechaFactura.setVisible(false);
            btnAceptar.setText("Presupuestar");
         }
      }
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel2 = new javax.swing.JPanel();
      labelN_factura = new javax.swing.JLabel();
      labeFecha = new javax.swing.JLabel();
      tfFacturaCuarto = new javax.swing.JTextField();
      tfFacturaOcteto = new javax.swing.JTextField();
      labelLetra = new javax.swing.JLabel();
      cbFacturaTipo = new javax.swing.JComboBox();
      cbCaja = new javax.swing.JComboBox();
      labelCaja = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      tfNumMovimiento = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      cbCliente = new javax.swing.JComboBox();
      btnCliente = new javax.swing.JButton();
      cbListaPrecio = new javax.swing.JComboBox();
      dcFechaFactura = new com.toedter.calendar.JDateChooser();
      jLabel2 = new javax.swing.JLabel();
      cbSucursal = new javax.swing.JComboBox();
      cbUsuario = new javax.swing.JComboBox();
      jLabel4 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      cbFormaPago = new javax.swing.JComboBox();
      jLabel15 = new javax.swing.JLabel();
      tfDias = new javax.swing.JTextField();
      labelRemito = new javax.swing.JLabel();
      tfRemito = new javax.swing.JTextField();
      btnBuscarRemito = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      btnCancelar = new javax.swing.JButton();
      btnAceptar = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      jLabel8 = new javax.swing.JLabel();
      tfProductoCodigo = new javax.swing.JTextField();
      bBuscarProducto = new javax.swing.JButton();
      jLabel9 = new javax.swing.JLabel();
      tfProductoNombre = new javax.swing.JTextField();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel17 = new javax.swing.JLabel();
      tfCantidad = new javax.swing.JTextField();
      tfPrecioUnitario = new javax.swing.JTextField();
      tfProductoIVA = new javax.swing.JTextField();
      btnADD = new javax.swing.JButton();
      btnDEL = new javax.swing.JButton();
      jLabel21 = new javax.swing.JLabel();
      tfProductoDesc = new javax.swing.JTextField();
      cbDesc = new javax.swing.JComboBox();
      jPanel6 = new javax.swing.JPanel();
      jLabel23 = new javax.swing.JLabel();
      tfGravado = new javax.swing.JTextField();
      tfTotal = new javax.swing.JTextField();
      jLabel24 = new javax.swing.JLabel();
      jLabel25 = new javax.swing.JLabel();
      tfTotalIVA21 = new javax.swing.JTextField();
      jLabel26 = new javax.swing.JLabel();
      tfTotalIVA105 = new javax.swing.JTextField();
      jLabel27 = new javax.swing.JLabel();
      tfTotalDesc = new javax.swing.JTextField();
      btnFacturar = new javax.swing.JButton();
      jPanel4 = new javax.swing.JPanel();
      tfMonto = new javax.swing.JTextField();
      tfCambio = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Facturación - Ventas");
      setResizable(false);

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos facturación"));

      labelN_factura.setText("Nº factura");

      labeFecha.setText("Fecha");

      tfFacturaCuarto.setColumns(4);
      tfFacturaCuarto.setEditable(false);
      tfFacturaCuarto.setFont(new java.awt.Font("Tahoma", 1, 12));
      tfFacturaCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfFacturaCuarto.setText("XXXX");
      tfFacturaCuarto.setFocusable(false);
      tfFacturaCuarto.setRequestFocusEnabled(false);

      tfFacturaOcteto.setColumns(8);
      tfFacturaOcteto.setEditable(false);
      tfFacturaOcteto.setFont(new java.awt.Font("Tahoma", 1, 12));
      tfFacturaOcteto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfFacturaOcteto.setText("1X2X3X4X");
      tfFacturaOcteto.setFocusable(false);
      tfFacturaOcteto.setRequestFocusEnabled(false);

      labelLetra.setText("Letra");

      cbFacturaTipo.setFont(new java.awt.Font("Tahoma", 1, 11));
      cbFacturaTipo.setName("facturaLetra"); // NOI18N

      cbCaja.setName("caja"); // NOI18N

      labelCaja.setText("Caja");

      jLabel13.setText("Nº");

      tfNumMovimiento.setColumns(4);
      tfNumMovimiento.setEditable(false);
      tfNumMovimiento.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfNumMovimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfNumMovimiento.setText("XXXX");
      tfNumMovimiento.setToolTipText("Nº de movimiento interno");
      tfNumMovimiento.setFocusable(false);
      tfNumMovimiento.setRequestFocusEnabled(false);

      jLabel3.setText("Lista Precios");

      jLabel1.setText("Cliente");

      cbCliente.setName("cliente"); // NOI18N

      btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add.png"))); // NOI18N
      btnCliente.setName("btnClientes"); // NOI18N

      cbListaPrecio.setName("listaPrecios"); // NOI18N

      dcFechaFactura.setDate(new java.util.Date());
      dcFechaFactura.setDateFormatString(entity.UTIL.DATE_FORMAT.toPattern());
      dcFechaFactura.setNextFocusableComponent(cbFacturaTipo);

      jLabel2.setText("Sucursal");

      cbSucursal.setName("sucursal"); // NOI18N

      cbUsuario.setEnabled(false);
      cbUsuario.setFocusable(false);
      cbUsuario.setName("usuario"); // NOI18N
      cbUsuario.setRequestFocusEnabled(false);

      jLabel4.setText("Operador");

      jLabel14.setText("Forma Pago");

      cbFormaPago.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbFormaPagoActionPerformed(evt);
         }
      });
      cbFormaPago.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            cbFormaPagoFocusLost(evt);
         }
      });

      jLabel15.setText("Días");

      tfDias.setColumns(3);
      tfDias.setEnabled(false);
      tfDias.setName("dias"); // NOI18N
      tfDias.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfDiasKeyTyped(evt);
         }
      });

      labelRemito.setText("Remito");

      tfRemito.setColumns(12);
      tfRemito.setEditable(false);
      tfRemito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
      tfRemito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfRemito.setFocusable(false);
      tfRemito.setRequestFocusEnabled(false);

      btnBuscarRemito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_add.png"))); // NOI18N
      btnBuscarRemito.setToolTipText("Vincular a un Remito");
      btnBuscarRemito.setName("btnBuscarRemito"); // NOI18N

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel3)
               .addComponent(labelCaja)
               .addComponent(jLabel1)
               .addComponent(labelLetra))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(cbListaPrecio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel4)
                     .addComponent(jLabel2))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(cbUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(labelRemito)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(6, 6, 6)
                  .addComponent(btnBuscarRemito, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(labelN_factura)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(labeFecha)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel13)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel14)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel15)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jLabel1)
               .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCliente)
               .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2)
               .addComponent(labelRemito)
               .addComponent(tfRemito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnBuscarRemito))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(cbListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3)
               .addComponent(cbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel13)
                     .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                     .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(labelN_factura)
                     .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(labeFecha)))
               .addComponent(labelLetra))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(labelCaja)
               .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel14)
               .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel15))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jTable1.setModel(new javax.swing.table.DefaultTableModel());
      jScrollPane1.setViewportView(jTable1);

      btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_button_cancel.png"))); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.setName("cancelar"); // NOI18N

      btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
      btnAceptar.setText("Aceptar");
      btnAceptar.setName("aceptar"); // NOI18N

      jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

      jLabel8.setText("Código");

      tfProductoCodigo.setColumns(4);
      tfProductoCodigo.setToolTipText("ingrese el código y presione Enter");
      tfProductoCodigo.setName("productoCodigo"); // NOI18N

      bBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
      bBuscarProducto.setToolTipText("Buscar Producto");
      bBuscarProducto.setName("btnProducto"); // NOI18N
      bBuscarProducto.setNextFocusableComponent(tfCantidad);

      jLabel9.setText("Nombre");

      tfProductoNombre.setColumns(10);
      tfProductoNombre.setEditable(false);
      tfProductoNombre.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfProductoNombre.setRequestFocusEnabled(false);

      jLabel10.setText("Cantidad");

      jLabel11.setText("Precio U.");

      jLabel17.setText("IVA %");

      tfCantidad.setColumns(4);
      tfCantidad.setName("productoCant"); // NOI18N
      tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfCantidadFocusGained(evt);
         }
      });
      tfCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfCantidadKeyTyped(evt);
         }
      });

      tfPrecioUnitario.setColumns(8);
      tfPrecioUnitario.setToolTipText("Precio venta + Margen + Lista Precios");
      tfPrecioUnitario.setName("productoPrecio"); // NOI18N
      tfPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfPrecioUnitarioFocusGained(evt);
         }
      });

      tfProductoIVA.setColumns(4);
      tfProductoIVA.setEditable(false);
      tfProductoIVA.setFocusable(false);
      tfProductoIVA.setRequestFocusEnabled(false);

      btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N
      btnADD.setToolTipText("Agragar producto");
      btnADD.setName("add"); // NOI18N
      btnADD.setNextFocusableComponent(tfProductoCodigo);

      btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
      btnDEL.setToolTipText("Quitar producto");
      btnDEL.setName("del"); // NOI18N
      btnDEL.setRequestFocusEnabled(false);

      jLabel21.setText("Desc");

      tfProductoDesc.setColumns(4);
      tfProductoDesc.setText("0");
      tfProductoDesc.setToolTipText("Descuento sobre Precio Unitario");
      tfProductoDesc.setNextFocusableComponent(btnADD);

      cbDesc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%", "$" }));
      cbDesc.setToolTipText("<html>Margen aplicado al precio\n<br>% - Porcentual\n<br>$  - Monto fijo \n</html>");
      cbDesc.setNextFocusableComponent(tfProductoDesc);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfProductoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(tfProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(25, 25, 25)
                  .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel8)
               .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(tfProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel10)
               .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel11)
               .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel17)
               .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel21)
               .addComponent(tfProductoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cbDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(btnDEL)
               .addComponent(btnADD)))
      );

      jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

      jLabel23.setText("  Gravado");

      tfGravado.setColumns(8);
      tfGravado.setEditable(false);
      tfGravado.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfGravado.setText("0.00");

      tfTotal.setColumns(8);
      tfTotal.setEditable(false);
      tfTotal.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotal.setText("0");

      jLabel24.setText("Total");

      jLabel25.setText("  IVA 21%");

      tfTotalIVA21.setColumns(6);
      tfTotalIVA21.setEditable(false);
      tfTotalIVA21.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotalIVA21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotalIVA21.setText("0.00");

      jLabel26.setText("IVA 10,5%");

      tfTotalIVA105.setColumns(6);
      tfTotalIVA105.setEditable(false);
      tfTotalIVA105.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotalIVA105.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotalIVA105.setText("0.00");

      jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel27.setText("Desc.");

      tfTotalDesc.setColumns(6);
      tfTotalDesc.setEditable(false);
      tfTotalDesc.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotalDesc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotalDesc.setText("0.00");

      javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
      jPanel6.setLayout(jPanel6Layout);
      jPanel6Layout.setHorizontalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel23)
               .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel26)
               .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(31, 31, 31)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel25))
            .addGap(43, 43, 43)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tfTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                  .addComponent(jLabel24)
                  .addGap(31, 31, 31)))
            .addContainerGap())
      );
      jPanel6Layout.setVerticalGroup(
         jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel6Layout.createSequentialGroup()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                  .addComponent(jLabel24)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
               .addGroup(jPanel6Layout.createSequentialGroup()
                  .addComponent(jLabel23)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
               .addGroup(jPanel6Layout.createSequentialGroup()
                  .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
               .addGroup(jPanel6Layout.createSequentialGroup()
                  .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfTotalDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
      );

      btnFacturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_fileprint.png"))); // NOI18N
      btnFacturar.setText("Facturar");
      btnFacturar.setName("facturar"); // NOI18N

      jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cambio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

      tfMonto.setColumns(6);
      tfMonto.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfMonto.setText("0");
      tfMonto.setName("monto"); // NOI18N
      tfMonto.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            tfMontoFocusLost(evt);
         }
      });
      tfMonto.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfMontoKeyTyped(evt);
         }
      });

      tfCambio.setColumns(6);
      tfCambio.setEditable(false);
      tfCambio.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfCambio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfCambio.setText("0");

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
            .addComponent(tfCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(tfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(tfCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                  .addComponent(btnFacturar)
                  .addGap(46, 46, 46)
                  .addComponent(btnAceptar)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnCancelar))
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnAceptar)
                  .addComponent(btnFacturar))
               .addComponent(btnCancelar))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void tfCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadKeyTyped
       soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tfCantidadKeyTyped

    private void tfMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMontoKeyTyped
       soloNumeros_Y_punto(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tfMontoKeyTyped

    private void cbFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagoActionPerformed
       //habilitando el textfield para poner la cantidad de días de cta cte
       tfDias.setEnabled((cbFormaPago.getSelectedItem().toString().equals(Valores.FormaPago.CTA_CTE.getNombre())));
       tfDias.setRequestFocusEnabled(tfDias.isEnabled());
       tfDias.setText("");
       //deshabilita la selección de caja
       //ya que cuando es CtaCte, no hay movimiento de Caja
       cbCaja.setEnabled(!tfDias.isEnabled());
}//GEN-LAST:event_cbFormaPagoActionPerformed

    private void cbFormaPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFormaPagoFocusLost
       if (tfDias.isEnabled()) {
          tfDias.requestFocus();
       }
}//GEN-LAST:event_cbFormaPagoFocusLost

    private void tfDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiasKeyTyped
       soloNumeros(evt);
}//GEN-LAST:event_tfDiasKeyTyped

    private void tfMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMontoFocusLost
      setCambio();
    }//GEN-LAST:event_tfMontoFocusLost

    private void tfPrecioUnitarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusGained
      tfPrecioUnitario.setSelectionStart(0);
    }//GEN-LAST:event_tfPrecioUnitarioFocusGained

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
      tfCantidad.setSelectionStart(0);
    }//GEN-LAST:event_tfCantidadFocusGained

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bBuscarProducto;
   private javax.swing.JButton btnADD;
   private javax.swing.JButton btnAceptar;
   private javax.swing.JButton btnBuscarRemito;
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnCliente;
   private javax.swing.JButton btnDEL;
   private javax.swing.JButton btnFacturar;
   private javax.swing.JComboBox cbCaja;
   private javax.swing.JComboBox cbCliente;
   private javax.swing.JComboBox cbDesc;
   private javax.swing.JComboBox cbFacturaTipo;
   private javax.swing.JComboBox cbFormaPago;
   private javax.swing.JComboBox cbListaPrecio;
   private javax.swing.JComboBox cbSucursal;
   private javax.swing.JComboBox cbUsuario;
   private com.toedter.calendar.JDateChooser dcFechaFactura;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel27;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel6;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   private javax.swing.JLabel labeFecha;
   private javax.swing.JLabel labelCaja;
   private javax.swing.JLabel labelLetra;
   private javax.swing.JLabel labelN_factura;
   private javax.swing.JLabel labelRemito;
   private javax.swing.JTextField tfCambio;
   private javax.swing.JTextField tfCantidad;
   private javax.swing.JTextField tfDias;
   private javax.swing.JTextField tfFacturaCuarto;
   private javax.swing.JTextField tfFacturaOcteto;
   private javax.swing.JTextField tfGravado;
   private javax.swing.JTextField tfMonto;
   private javax.swing.JTextField tfNumMovimiento;
   private javax.swing.JTextField tfPrecioUnitario;
   private javax.swing.JTextField tfProductoCodigo;
   private javax.swing.JTextField tfProductoDesc;
   private javax.swing.JTextField tfProductoIVA;
   private javax.swing.JTextField tfProductoNombre;
   private javax.swing.JTextField tfRemito;
   private javax.swing.JTextField tfTotal;
   private javax.swing.JTextField tfTotalDesc;
   private javax.swing.JTextField tfTotalIVA105;
   private javax.swing.JTextField tfTotalIVA21;
   // End of variables declaration//GEN-END:variables

   private void soloNumeros(java.awt.event.KeyEvent evt) {
      int k = evt.getKeyChar();
      if (k < 48 || k > 57) {
         evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
      }
   }

   private void soloNumeros_Y_punto(KeyEvent evt) {
      int k = evt.getKeyChar();
      if ((k < 48 || k > 57) && (k != 46)) {
         evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
      }
   }

   public void setListener(Object o) {
      btnADD.addActionListener((ActionListener) o);
      btnDEL.addActionListener((ActionListener) o);
      bBuscarProducto.addActionListener((ActionListener) o);
//      jTable1.addMouseListener((MouseListener) o);
      btnAceptar.addActionListener((ActionListener) o);
      btnCancelar.addActionListener((ActionListener) o);
      btnFacturar.addActionListener((ActionListener) o);
      btnCliente.addActionListener((ActionListener) o);
      cbListaPrecio.addActionListener((ActionListener) o);
      cbCliente.addActionListener((ActionListener) o);
      btnBuscarRemito.addActionListener((ActionListener) o);
      tfProductoCodigo.addKeyListener((KeyListener) o);
      tfMonto.addKeyListener((KeyListener) o);
   }

   // <editor-fold defaultstate="collapsed" desc="GETTERS">
   public JTable getjTable1() {
      return jTable1;
   }

   public String getTfDias() {
      return tfDias.getText().trim();
   }

   public void setTfDias(String dias) {
      tfDias.setText(dias);
   }

   public JComboBox getCbFormaPago() {
      return cbFormaPago;
   }

   public JComboBox getCbCaja() {
      return cbCaja;
   }

   public DefaultTableModel getDTM() {
      return (DefaultTableModel) getjTable1().getModel();
   }

   public String getTfCantidad() {
      return tfCantidad.getText().trim();
   }

   public String getTfTotalDesc() {
      return tfTotalDesc.getText().trim();
   }

   public String getTfFacturaCuarto() {
      return tfFacturaCuarto.getText().trim();
   }

   public String getTfFacturaOcteto() {
      return tfFacturaOcteto.getText().trim();
   }

   public String getTfGravado() {
      return tfGravado.getText().trim();
   }

   public String getTfPrecioUnitario() {
      return tfPrecioUnitario.getText().trim();
   }

   public String getTfProductoCodigo() {
      return tfProductoCodigo.getText().trim();
   }

   public String getTfProductoDesc() {
      return tfProductoDesc.getText().trim();
   }

   public String getTfProductoIVA() {
      return tfProductoIVA.getText().trim();
   }

   public String getTfProductoNombre() {
      return tfProductoNombre.getText().trim();
   }

   public String getTfTotal() {
      return tfTotal.getText().trim();
   }

   public String getTfTotalIVA105() {
      return tfTotalIVA105.getText().trim();
   }

   public String getTfTotalIVA21() {
      return tfTotalIVA21.getText().trim();
   }

   public JComboBox getCbCliente() {
      return cbCliente;
   }

   public JComboBox getCbDesc() {
      return cbDesc;
   }

   public JComboBox getCbFacturaTipo() {
      return cbFacturaTipo;
   }

   public JComboBox getCbListaPrecio() {
      return cbListaPrecio;
   }

   public JComboBox getCbSucursal() {
      return cbSucursal;
   }

   public JComboBox getCbUsuario() {
      return cbUsuario;
   }

   public java.util.Date getDcFechaFactura() {
      return dcFechaFactura.getDate();
   }// </editor-fold>

   // <editor-fold defaultstate="collapsed" desc="SETTERS">
   public void setTfRemito(String remito) {
      tfRemito.setText(remito);
   }

   public void setDcFechaFactura(java.util.Date fechaFactura) {
      dcFechaFactura.setDate(fechaFactura);
   }

   public void setTfFacturaCuarto(String tfFacturaCuarto) {
      this.tfFacturaCuarto.setText(tfFacturaCuarto);
   }

   public void setTfFacturaOcteto(String tfFacturaOcteto) {
      this.tfFacturaOcteto.setText(tfFacturaOcteto);
   }

   public void setTfGravado(String tfGravado) {
      this.tfGravado.setText(tfGravado);
   }

   public void setTfProductoCodigo(String tfProductoCodigo) {
      this.tfProductoCodigo.setText(tfProductoCodigo);
   }

   public void setTfProductoIVA(String tfProductoIVA) {
      this.tfProductoIVA.setText(tfProductoIVA);
   }

   public void setTfProductoNombre(String tfProductoNombre) {
      this.tfProductoNombre.setText(tfProductoNombre);
   }

   public void setTfTotal(String tfTotal2) {
      this.tfTotal.setText(tfTotal2);
   }

   public void setTfTotalIVA105(String tfTotalIVA107) {
      this.tfTotalIVA105.setText(tfTotalIVA107);
   }

   public void setTfTotalIVA21(String tfTotalIVA23) {
      this.tfTotalIVA21.setText(tfTotalIVA23);
   }

   public void setTfPrecioUnitario(String precio) {
      this.tfPrecioUnitario.setText(precio);
   }

   public void setTfTotalDesc(String TotalDescuento) {
      this.tfTotalDesc.setText(TotalDescuento);
   }

   public String getTfCambio() {
      return tfCambio.getText();
   }

   public void setTfCambio(String tfCambio) {
      this.tfCambio.setText(tfCambio);
   }

   public void setTfCantidad(String cantidad) {
      tfCantidad.setText(cantidad);
   }

   public void setTfMonto(String tfMonto) {
      this.tfMonto.setText(tfMonto);
   }// </editor-fold>

   /**
    * Setea un mensaje de información.
    * Si @param messageType < -1 || > 3 no hace NADA.
    * @param msg,.. mensaje.
    * @param titulo (puede tener título o no).
    * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
    */
   public void showMessage(String msg, String titulo, int messageType) {
      if (messageType >= -1 && messageType <= 2) {
         javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, messageType);
      } else {
         javax.swing.JOptionPane.showMessageDialog(this, msg);
      }
   }

   public void setFocusCantidad() {
      tfCantidad.requestFocus();
   }

   public String getTfNumMovimiento() {
      return tfNumMovimiento.getText();
   }

   public void setTfNumMovimiento(String tfMovimientoInterno) {
      this.tfNumMovimiento.setText(tfMovimientoInterno);
   }

   public void setCambio() {
      java.text.DecimalFormatSymbols simbolos = new java.text.DecimalFormatSymbols();
      simbolos.setDecimalSeparator('.');
      java.text.DecimalFormat df = new java.text.DecimalFormat("########.##", simbolos);
      try {
         double total = Double.valueOf(tfTotal.getText());
         double monto = Double.valueOf(tfMonto.getText());
         tfCambio.setText(df.format((monto - total)));
      } catch (NumberFormatException ex) {
         showMessage("Monto no válido", "Cálculo de cambio", 2);
      }
   }

   public void modoVista() {
      cbCliente.setEnabled(false);
      btnCliente.setEnabled(false);
      cbSucursal.setEnabled(false);
      cbListaPrecio.setEnabled(false);
      dcFechaFactura.setEnabled(false);
      cbFacturaTipo.setEnabled(false);
      cbCaja.setEnabled(false);
      cbFormaPago.setEnabled(false);
      tfDias.setEnabled(false);
      //////////////////
      tfProductoCodigo.setEnabled(false);
      bBuscarProducto.setEnabled(false);
      btnADD.setEnabled(false);
      btnDEL.setEnabled(false);
      btnCancelar.setEnabled(false);
      btnAceptar.setEnabled(true);
      btnBuscarRemito.setEnabled(false);
   }

   public JButton getBtnFacturar() {
      return btnFacturar;
   }

   /**
    * 1 = FacturaVenta, 2 = Presupuesto, 3 = Remito
    * @return
    */
   public int getModoVista() {
      return modoVista;
   }
   

}

