/*
 * JDFacturaCompra.java
 *
 * Created on 08/02/2010, 17:36:00
 */
package gui;

import entity.UTIL;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author FiruzzZ
 */
public class JDFacturaCompra extends javax.swing.JDialog {

   /** Creates new form JDFacturaCompra */
   public JDFacturaCompra(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      initComponents();
      this.setLocationRelativeTo(parent);
      dcFechaFactura.setDate(new java.util.Date());
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jPanel1 = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      cbProveedor = new javax.swing.JComboBox();
      cbFacturaTipo = new javax.swing.JComboBox();
      jLabel1 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      cbFormaPago = new javax.swing.JComboBox();
      tfDias = new javax.swing.JTextField();
      dcFechaFactura = new com.toedter.calendar.JDateChooser();
      jLabel3 = new javax.swing.JLabel();
      tfFacturaCuarto = new javax.swing.JTextField();
      tfFacturaOcteto = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      cbSucursal = new javax.swing.JComboBox();
      cbCaja = new javax.swing.JComboBox();
      jLabel15 = new javax.swing.JLabel();
      jLabel19 = new javax.swing.JLabel();
      tfNumMovimiento = new javax.swing.JTextField();
      jLabel18 = new javax.swing.JLabel();
      cbConstanciasDeCompra = new javax.swing.JComboBox();
      bBuscarConstanciasDeCompra = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jTable1 = new javax.swing.JTable();
      jPanel4 = new javax.swing.JPanel();
      jLabel12 = new javax.swing.JLabel();
      tfGravado = new javax.swing.JTextField();
      tfTotal = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      tfTotalIVA21 = new javax.swing.JTextField();
      jLabel16 = new javax.swing.JLabel();
      tfTotalIVA105 = new javax.swing.JTextField();
      btnCancelar = new javax.swing.JButton();
      btnAceptar = new javax.swing.JButton();
      jPanel5 = new javax.swing.JPanel();
      checkActualizaStock = new javax.swing.JCheckBox();
      jLabel17 = new javax.swing.JLabel();
      tfPercIVA = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      jLabel7 = new javax.swing.JLabel();
      tfProductoCodigo = new javax.swing.JTextField();
      bBuscarProducto = new javax.swing.JButton();
      jLabel8 = new javax.swing.JLabel();
      tfProductoNombre = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      tfCantidad = new javax.swing.JTextField();
      tfPrecioUnitario = new javax.swing.JTextField();
      tfProductoIVA = new javax.swing.JTextField();
      btnADD = new javax.swing.JButton();
      cbCambioPrecio = new javax.swing.JComboBox();
      btnDEL = new javax.swing.JButton();
      jLabel21 = new javax.swing.JLabel();
      tfProductoPrecioActual = new javax.swing.JTextField();
      btnAnular = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Factura - Compra");
      setResizable(false);

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos compra"));

      jLabel5.setText("Forma Pago");

      jLabel1.setText("Proveedor");

      jLabel6.setText("Días");

      jLabel2.setText("Fecha");

      cbFormaPago.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbFormaPagoActionPerformed(evt);
         }
      });
      cbFormaPago.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            cbFormaPagoFocusLost(evt);
         }
      });

      tfDias.setColumns(3);
      tfDias.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfDias.setEnabled(false);
      tfDias.setName("dias"); // NOI18N
      tfDias.setRequestFocusEnabled(false);
      tfDias.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfDiasKeyTyped(evt);
         }
      });

      dcFechaFactura.setDateFormatString(entity.UTIL.DATE_FORMAT.toPattern());

      jLabel3.setText("Nº");

      tfFacturaCuarto.setColumns(4);
      tfFacturaCuarto.setName("cuarteto"); // NOI18N
      tfFacturaCuarto.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            tfFacturaCuartoFocusLost(evt);
         }
      });
      tfFacturaCuarto.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfFacturaCuartoKeyTyped(evt);
         }
      });

      tfFacturaOcteto.setColumns(8);
      tfFacturaOcteto.setName("octeto"); // NOI18N
      tfFacturaOcteto.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            tfFacturaOctetoFocusLost(evt);
         }
      });
      tfFacturaOcteto.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfFacturaOctetoKeyTyped(evt);
         }
      });

      jLabel4.setText("Tipo");

      jLabel20.setText("Sucursal");

      cbCaja.setName("caja"); // NOI18N

      jLabel15.setText("Caja");

      jLabel19.setText("Movimiento");

      tfNumMovimiento.setColumns(3);
      tfNumMovimiento.setEditable(false);
      tfNumMovimiento.setFont(new java.awt.Font("Tahoma", 1, 12));
      tfNumMovimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfNumMovimiento.setText("0");
      tfNumMovimiento.setFocusable(false);
      tfNumMovimiento.setRequestFocusEnabled(false);

      jLabel18.setText("C. compra");

      cbConstanciasDeCompra.setName("caja"); // NOI18N

      bBuscarConstanciasDeCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
      bBuscarConstanciasDeCompra.setName("buscarProducto"); // NOI18N
      bBuscarConstanciasDeCompra.setNextFocusableComponent(tfCantidad);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel1)
                     .addComponent(jLabel2))
                  .addGroup(jPanel1Layout.createSequentialGroup()
                     .addGap(28, 28, 28)
                     .addComponent(jLabel15)))
               .addComponent(jLabel18))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel20)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                  .addComponent(jLabel4)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(cbConstanciasDeCompra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(cbCaja, 0, 134, Short.MAX_VALUE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(bBuscarConstanciasDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1)
               .addComponent(jLabel20)
               .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(dcFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2)
               .addComponent(jLabel3)
               .addComponent(tfFacturaCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4)
               .addComponent(cbFacturaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfFacturaOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel15)
               .addComponent(jLabel5)
               .addComponent(cbFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel6)
               .addComponent(tfDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(tfNumMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel18)
                  .addComponent(cbConstanciasDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel19))
               .addComponent(bBuscarConstanciasDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      jScrollPane1.setViewportView(jTable1);

      jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resumen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

      jLabel12.setText("  Gravado");

      tfGravado.setEditable(false);
      tfGravado.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfGravado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfGravado.setText("0");

      tfTotal.setEditable(false);
      tfTotal.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotal.setText("0");

      jLabel13.setText("Total");

      jLabel14.setText("  IVA 21%");

      tfTotalIVA21.setEditable(false);
      tfTotalIVA21.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotalIVA21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotalIVA21.setText("0");

      jLabel16.setText("IVA 10,5%");

      tfTotalIVA105.setEditable(false);
      tfTotalIVA105.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfTotalIVA105.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfTotalIVA105.setText("0");

      javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
      jPanel4.setLayout(jPanel4Layout);
      jPanel4Layout.setHorizontalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel12)
               .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel16)
               .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel14)
               .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(217, 217, 217)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tfTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                  .addComponent(jLabel13)
                  .addGap(31, 31, 31)))
            .addContainerGap())
      );
      jPanel4Layout.setVerticalGroup(
         jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel12)
               .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel13))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                  .addComponent(tfGravado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(tfTotalIVA21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfTotalIVA105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.setName("cancelar"); // NOI18N

      btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
      btnAceptar.setText("Aceptar");
      btnAceptar.setName("aceptar"); // NOI18N

      jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

      checkActualizaStock.setSelected(true);
      checkActualizaStock.setText("Actualiza stock");
      checkActualizaStock.setToolTipText("Si la carga de factura afectará el stock");

      jLabel17.setText("PERC. IVA");

      tfPercIVA.setColumns(8);
      tfPercIVA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfPercIVA.setText("0");
      tfPercIVA.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyTyped(java.awt.event.KeyEvent evt) {
            tfPercIVAKeyTyped(evt);
         }
      });

      javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
      jPanel5.setLayout(jPanel5Layout);
      jPanel5Layout.setHorizontalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                  .addComponent(jLabel17)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfPercIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(checkActualizaStock)))
      );
      jPanel5Layout.setVerticalGroup(
         jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(checkActualizaStock)
            .addGap(7, 7, 7)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel17)
               .addComponent(tfPercIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(62, Short.MAX_VALUE))
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

      jLabel7.setText("Código");

      tfProductoCodigo.setColumns(4);
      tfProductoCodigo.setName("productoCodigo"); // NOI18N

      bBuscarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
      bBuscarProducto.setName("buscarProducto"); // NOI18N
      bBuscarProducto.setNextFocusableComponent(tfCantidad);

      jLabel8.setText("Nombre");

      tfProductoNombre.setEditable(false);
      tfProductoNombre.setFont(new java.awt.Font("Tahoma", 1, 11));
      tfProductoNombre.setRequestFocusEnabled(false);

      jLabel9.setText("Cantidad");

      jLabel10.setText("Precio U.");

      jLabel11.setText("IVA %");

      tfCantidad.setColumns(4);
      tfCantidad.setName("productoCant"); // NOI18N
      tfCantidad.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfCantidadFocusGained(evt);
         }
      });

      tfPrecioUnitario.setColumns(8);
      tfPrecioUnitario.setName("productoPrecio"); // NOI18N
      tfPrecioUnitario.setNextFocusableComponent(cbCambioPrecio);
      tfPrecioUnitario.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfPrecioUnitarioFocusGained(evt);
         }
      });

      tfProductoIVA.setColumns(4);
      tfProductoIVA.setEditable(false);
      tfProductoIVA.setEnabled(false);
      tfProductoIVA.setFocusable(false);
      tfProductoIVA.setRequestFocusEnabled(false);

      btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N
      btnADD.setToolTipText("Agregar producto");
      btnADD.setName("add"); // NOI18N

      cbCambioPrecio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Última", "Anterior", "PPP" }));
      cbCambioPrecio.setToolTipText("<html>Fijación de costo compra:\n<br>Última compra\n<br>Compra Anterior\n<br>PPP (Precio Ponderado Promedio)\n</html>");
      cbCambioPrecio.setNextFocusableComponent(btnADD);

      btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
      btnDEL.setToolTipText("Quitar producto");
      btnDEL.setName("del"); // NOI18N
      btnDEL.setNextFocusableComponent(tfProductoCodigo);
      btnDEL.setRequestFocusEnabled(false);

      jLabel21.setText("Precio Ac.");

      tfProductoPrecioActual.setToolTipText("<html>\nPrecio actual del producto\n<br>(última compra)\n</html>");
      tfProductoPrecioActual.setEnabled(false);
      tfProductoPrecioActual.setRequestFocusEnabled(false);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jLabel21)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfProductoPrecioActual, 0, 0, Short.MAX_VALUE))
               .addComponent(tfProductoNombre)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel10)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(jLabel11)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(cbCambioPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
            .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(48, 48, 48))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(btnDEL)
               .addComponent(btnADD)
               .addGroup(jPanel2Layout.createSequentialGroup()
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                     .addComponent(tfProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel7)
                     .addComponent(bBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel21)
                     .addComponent(tfProductoPrecioActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel8)
                     .addComponent(tfProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel9)
                     .addComponent(tfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel10)
                     .addComponent(tfPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel11)
                     .addComponent(tfProductoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(cbCambioPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );

      btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_editdelete.png"))); // NOI18N
      btnAnular.setText("Anular");
      btnAnular.setEnabled(false);
      btnAnular.setName("anular"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
               .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addComponent(btnAnular)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 292, Short.MAX_VALUE)
                  .addComponent(btnAceptar)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnCancelar)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void cbFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFormaPagoActionPerformed
       //habilitando el textfield para poner la cantidad de días de cta cte
       tfDias.setEnabled((cbFormaPago.getSelectedItem().toString().equalsIgnoreCase("Cta Cte")));
       tfDias.setRequestFocusEnabled((cbFormaPago.getSelectedItem().toString().equalsIgnoreCase("Cta Cte")));
       tfDias.setText("");
       //deshabilita la selección de caja
       //ya que cuando es CtaCte, no hay movimiento de Caja
       cbCaja.setEnabled(!tfDias.isEnabled());
    }//GEN-LAST:event_cbFormaPagoActionPerformed

    private void tfDiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiasKeyTyped

       soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiasKeyTyped

    private void tfFacturaCuartoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaCuartoFocusLost
       tfFacturaCuarto.setText(UTIL.AGREGAR_CEROS(tfFacturaCuarto.getText().trim(), 4));
    }//GEN-LAST:event_tfFacturaCuartoFocusLost

    private void tfFacturaOctetoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFacturaOctetoFocusLost
       tfFacturaOcteto.setText(UTIL.AGREGAR_CEROS(tfFacturaOcteto.getText().trim(), 8));
    }//GEN-LAST:event_tfFacturaOctetoFocusLost

    private void tfFacturaCuartoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaCuartoKeyTyped
       soloNumeros(evt);
    }//GEN-LAST:event_tfFacturaCuartoKeyTyped

    private void tfFacturaOctetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFacturaOctetoKeyTyped
       soloNumeros(evt);
    }//GEN-LAST:event_tfFacturaOctetoKeyTyped

    private void cbFormaPagoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbFormaPagoFocusLost
       if (tfDias.isEnabled()) {
          tfDias.requestFocus();
       }
    }//GEN-LAST:event_cbFormaPagoFocusLost

    private void tfPercIVAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPercIVAKeyTyped
//        soloNumeros(evt);
    }//GEN-LAST:event_tfPercIVAKeyTyped

    private void tfCantidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCantidadFocusGained
       tfCantidad.setSelectionStart(0);
    }//GEN-LAST:event_tfCantidadFocusGained

    private void tfPrecioUnitarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPrecioUnitarioFocusGained
       tfPrecioUnitario.setSelectionStart(0);
    }//GEN-LAST:event_tfPrecioUnitarioFocusGained
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bBuscarConstanciasDeCompra;
   private javax.swing.JButton bBuscarProducto;
   private javax.swing.JButton btnADD;
   private javax.swing.JButton btnAceptar;
   private javax.swing.JButton btnAnular;
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnDEL;
   private javax.swing.JComboBox cbCaja;
   private javax.swing.JComboBox cbCambioPrecio;
   private javax.swing.JComboBox cbConstanciasDeCompra;
   private javax.swing.JComboBox cbFacturaTipo;
   private javax.swing.JComboBox cbFormaPago;
   private javax.swing.JComboBox cbProveedor;
   private javax.swing.JComboBox cbSucursal;
   private javax.swing.JCheckBox checkActualizaStock;
   private com.toedter.calendar.JDateChooser dcFechaFactura;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel4;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable jTable1;
   private javax.swing.JTextField tfCantidad;
   private javax.swing.JTextField tfDias;
   private javax.swing.JTextField tfFacturaCuarto;
   private javax.swing.JTextField tfFacturaOcteto;
   private javax.swing.JTextField tfGravado;
   private javax.swing.JTextField tfNumMovimiento;
   private javax.swing.JTextField tfPercIVA;
   private javax.swing.JTextField tfPrecioUnitario;
   private javax.swing.JTextField tfProductoCodigo;
   private javax.swing.JTextField tfProductoIVA;
   private javax.swing.JTextField tfProductoNombre;
   private javax.swing.JTextField tfProductoPrecioActual;
   private javax.swing.JTextField tfTotal;
   private javax.swing.JTextField tfTotalIVA105;
   private javax.swing.JTextField tfTotalIVA21;
   // End of variables declaration//GEN-END:variables

   /**
    * Setea un mensaje de información.
    * Si @param messageType < -1 || > 3 no hace NADA.
    * @param msg,.. mensaje.
    * @param titulo (puede tener título o no).
    * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
    */
   public void showMessage(String msg, String titulo, int messageType) {
      if (messageType >= -1 && messageType <= 2) {
         javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, messageType);
      } else {
         javax.swing.JOptionPane.showMessageDialog(this, msg);
      }
   }

   public void setListener(Object o) {
      btnADD.addActionListener((ActionListener) o);
      btnDEL.addActionListener((ActionListener) o);
      bBuscarProducto.addActionListener((ActionListener) o);
      btnCancelar.addActionListener((ActionListener) o);
      btnAceptar.addActionListener((ActionListener) o);
      jTable1.addMouseListener((MouseListener) o);
      tfProductoCodigo.addKeyListener((KeyListener) o);
      tfFacturaCuarto.addKeyListener((KeyListener) o);
      tfFacturaOcteto.addKeyListener((KeyListener) o);
   }

   private void soloNumeros(KeyEvent evt) {
      int k = evt.getKeyChar();
      if (k < 48 || k > 57) {
         evt.setKeyChar((char) java.awt.event.KeyEvent.VK_CLEAR);
      }
   }


   // <editor-fold defaultstate="collapsed" desc="GETTERS">

   public JComboBox getCbCaja() {
      return cbCaja;
   }

   public String getTfNumMovimiento() {
      return tfNumMovimiento.getText();
   }

   public JTable getjTable1() {
      return jTable1;
   }

   public javax.swing.table.DefaultTableModel getDTM() {
      return (javax.swing.table.DefaultTableModel) jTable1.getModel();
   }

   public JComboBox getCbCambioPrecio() {
      return cbCambioPrecio;
   }

   public JComboBox getCbFacturaTipo() {
      return cbFacturaTipo;
   }

   public JComboBox getCbFormaPago() {
      return cbFormaPago;
   }

   public JComboBox getCbProveedor() {
      return cbProveedor;
   }

   public JComboBox getCbSucursal() {
      return cbSucursal;
   }

   public JCheckBox getCheckActualizaStock() {
      return checkActualizaStock;
   }

   public java.util.Date getDcFechaFactura() {
      return dcFechaFactura.getDate();
   }

   public String getTfCantidad() {
      return tfCantidad.getText().trim();
   }

   public String getTfDias() {
      return tfDias.getText().trim();
   }

   public String getTfFacturaCuarto() {
      return tfFacturaCuarto.getText().trim();
   }

   public String getTfFacturaOcteto() {
      return tfFacturaOcteto.getText().trim();
   }

   public String getTfGravado() {
      return tfGravado.getText().trim();
   }

   public String getTfMovimiento() {
      return tfNumMovimiento.getText().trim();
   }

   public String getTfPercIVA() {
      return tfPercIVA.getText().trim();
   }

   public String getTfPrecioUnitario() {
      return tfPrecioUnitario.getText().trim();
   }

   public String getTfProductoCodigo() {
      return tfProductoCodigo.getText().trim();
   }

   public String getTfProductoIVA() {
      return tfProductoIVA.getText().trim();
   }

   public String getTfProductoNombre() {
      return tfProductoNombre.getText().trim();
   }

   public String getTfTotal() {
      return tfTotal.getText().trim();
   }

   public String getTfTotalIVA105() {
      return tfTotalIVA105.getText().trim();
   }

   public String getTfTotalIVA21() {
      return tfTotalIVA21.getText().trim();
   }// </editor-fold>

   // <editor-fold defaultstate="collapsed" desc="SETTERS">
   public void setDcFechaFactura(java.util.Date fechaFactura) {
      dcFechaFactura.setDate(fechaFactura);
   }

   public void setTfDias(String tfDias) {
      this.tfDias.setText(tfDias);
   }

   public void setTfFacturaCuarto(String tfFacturaCuarto) {
      this.tfFacturaCuarto.setText(tfFacturaCuarto);
   }

   public void setTfFacturaOcteto(String tfFacturaOcteto) {
      this.tfFacturaOcteto.setText(tfFacturaOcteto);
   }

   public void setTfNumMovimiento(String tfNumMovimiento) {
      this.tfNumMovimiento.setText(tfNumMovimiento);
   }

   public void setTfProductoCodigo(String tfProductoCodigo) {
      this.tfProductoCodigo.setText(tfProductoCodigo);
   }

   public void setTfProductoIVA(String tfProductoIVA) {
      this.tfProductoIVA.setText(tfProductoIVA);
   }

   public void setTfProductoNombre(String tfProductoNombre) {
      this.tfProductoNombre.setText(tfProductoNombre);
   }

   public void setTfProductoPrecioActual(String ProductoPrecioActual) {
      this.tfProductoPrecioActual.setText(ProductoPrecioActual);
   }

   public void setTfGravado(String tfGravado) {
      this.tfGravado.setText(tfGravado);
   }

   public void setTfTotal(String tfTotal) {
      this.tfTotal.setText(tfTotal);
   }

   public void setTfTotalIVA105(String tfTotalIVA105) {
      this.tfTotalIVA105.setText(tfTotalIVA105);
   }

   public void setTfTotalIVA21(String tfTotalIVA21) {
      this.tfTotalIVA21.setText(tfTotalIVA21);
   }// </editor-fold>

   public void limpiarPanelProducto() {
      tfProductoCodigo.setText("");
      tfProductoPrecioActual.setText("");
      tfProductoIVA.setText("");
      tfProductoNombre.setText("");
      tfCantidad.setText("");
      tfPrecioUnitario.setText("");
      tfPercIVA.setText("0");
      checkActualizaStock.setSelected(true);
   }

   public void limpiarTabla() {
      for (int i = getDTM().getRowCount() - 1; i > -1; i--) {
         getDTM().removeRow(i);
      }
   }

   public void limpiarPanelDatos() {
      tfFacturaCuarto.setText("");
      tfFacturaOcteto.setText("");
      cbFormaPago.setSelectedIndex(0);
      tfDias.setText("");
   }

   public void limpiarResumen() {
      tfGravado.setText("0");
      tfTotal.setText("0");
      tfTotalIVA105.setText("0");
      tfTotalIVA21.setText("0");
   }

   public JButton getBtnAnular() {
      return btnAnular;
   }

   public void modoVista(boolean enable) {
      dcFechaFactura.setEnabled(enable);
      tfFacturaCuarto.setEnabled(enable);
      tfFacturaOcteto.setEnabled(enable);
      cbFormaPago.setEnabled(enable);
      tfDias.setEnabled(enable);
      checkActualizaStock.setEnabled(enable);
      tfPercIVA.setEnabled(enable);
      bBuscarProducto.setEnabled(enable);
      btnADD.setEnabled(enable);
      btnDEL.setEnabled(enable);
      btnAceptar.setEnabled(enable);
      btnCancelar.setEnabled(enable);

      btnAnular.setEnabled(!enable);
   }
}
