/*
 * JDRecibosRemesas.java
 *
 * Created on 05/04/2010, 11:03:26
 */
package gui;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utilities.general.UTIL;
import utilities.gui.SwingUtil;

/**
 * Ventana usada para el ABM de Recibos y Remitos
 *
 * @author FiruzzZ
 */
public class JDReRe extends javax.swing.JDialog {

    /**
     * Creates new form JDRecibosRemesas
     */
    public JDReRe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bImprimir = new javax.swing.JButton();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tfCuarto = new javax.swing.JTextField();
        labelReRe = new javax.swing.JLabel();
        labelClienteProveedor = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cbClienteProveedor = new javax.swing.JComboBox();
        cbSucursal = new javax.swing.JComboBox();
        dcFechaReRe = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tfOcteto = new javax.swing.JTextField();
        cbCaja = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        dcFechaCarga = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        labelCreditoDebito = new javax.swing.JLabel();
        tfCreditoDebitoDisponible = new javax.swing.JTextField();
        btnDetalleCreditoDebito = new javax.swing.JButton();
        labelRestanteCreditoDebito = new javax.swing.JLabel();
        tfCreditoDebitoRestante = new javax.swing.JTextField();
        tfTotalEfectivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bAnular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfEntrega = new javax.swing.JTextField();
        tfObservacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        btnDEL = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cbCtaCtes = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        tfImporte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfPagado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        checkAcreditarEntrega = new javax.swing.JCheckBox();
        tfTotalPorCreditoDebito = new javax.swing.JTextField();
        labelPorCreditoDebito = new javax.swing.JLabel();
        tfTOTAL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        checkPagoConCheque = new javax.swing.JCheckBox();
        tfRetencion = new javax.swing.JTextField();
        labelRetencionPercepcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("setear título!");
        setResizable(false);

        jScrollPane1.setViewportView(jTable1);

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_fileprint.png"))); // NOI18N
        bImprimir.setMnemonic('i');
        bImprimir.setText("Imprimir");
        bImprimir.setName("Print"); // NOI18N

        bAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_apply.png"))); // NOI18N
        bAceptar.setMnemonic('a');
        bAceptar.setText("Aceptar");
        bAceptar.setName("aceptar"); // NOI18N

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        bCancelar.setMnemonic('c');
        bCancelar.setText("Cancelar");
        bCancelar.setName("cancelar"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        tfCuarto.setColumns(4);
        tfCuarto.setEditable(false);
        tfCuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfCuarto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCuarto.setRequestFocusEnabled(false);

        labelReRe.setText("Nº ReReRe");

        labelClienteProveedor.setText("Prov/Client");

        jLabel20.setText("Sucursal");

        cbClienteProveedor.setName("cbClienteProveedor"); // NOI18N

        cbSucursal.setName("cbSucursal"); // NOI18N

        dcFechaReRe.setDate(new java.util.Date());

        jLabel4.setText("Fecha");

        tfOcteto.setColumns(8);
        tfOcteto.setEditable(false);
        tfOcteto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tfOcteto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfOcteto.setRequestFocusEnabled(false);
        tfOcteto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfOctetoKeyTyped(evt);
            }
        });

        cbCaja.setName("caja"); // NOI18N

        jLabel15.setText("Caja");

        dcFechaCarga.setDate(new java.util.Date());
        dcFechaCarga.setEnabled(false);
        dcFechaCarga.setFocusable(false);
        dcFechaCarga.setRequestFocusEnabled(false);

        jLabel7.setText("Fecha carga");

        labelCreditoDebito.setText("Crédito");

        tfCreditoDebitoDisponible.setColumns(8);
        tfCreditoDebitoDisponible.setEditable(false);
        tfCreditoDebitoDisponible.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfCreditoDebitoDisponible.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCreditoDebitoDisponible.setText("0");
        tfCreditoDebitoDisponible.setFocusable(false);
        tfCreditoDebitoDisponible.setRequestFocusEnabled(false);

        btnDetalleCreditoDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/view_detail_16x.png"))); // NOI18N

        labelRestanteCreditoDebito.setText("Restante");

        tfCreditoDebitoRestante.setColumns(8);
        tfCreditoDebitoRestante.setEditable(false);
        tfCreditoDebitoRestante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfCreditoDebitoRestante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfCreditoDebitoRestante.setText("0");
        tfCreditoDebitoRestante.setFocusable(false);
        tfCreditoDebitoRestante.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelCreditoDebito)
                    .addComponent(jLabel20)
                    .addComponent(labelClienteProveedor)
                    .addComponent(labelReRe)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(dcFechaReRe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dcFechaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cbClienteProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfCreditoDebitoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDetalleCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelRestanteCreditoDebito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCreditoDebitoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfOcteto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReRe)
                    .addComponent(tfCuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dcFechaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcFechaReRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClienteProveedor)
                    .addComponent(cbClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelCreditoDebito)
                    .addComponent(tfCreditoDebitoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetalleCreditoDebito)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCreditoDebitoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelRestanteCreditoDebito))))
        );

        tfTotalEfectivo.setColumns(8);
        tfTotalEfectivo.setEditable(false);
        tfTotalEfectivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfTotalEfectivo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalEfectivo.setText("0");
        tfTotalEfectivo.setToolTipText("NO incluye el monto ACREDITADO ni la RETENCIÓN");
        tfTotalEfectivo.setFocusable(false);
        tfTotalEfectivo.setRequestFocusEnabled(false);

        jLabel2.setText("Efectivo");

        bAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_editdelete.png"))); // NOI18N
        bAnular.setText("Anular");
        bAnular.setToolTipText("");
        bAnular.setFocusable(false);
        bAnular.setName("anular"); // NOI18N
        bAnular.setRequestFocusEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N

        tfEntrega.setColumns(10);
        tfEntrega.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfEntrega.setToolTipText("Monto ($)");
        tfEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectAllText(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEntregaFocusLost(evt);
            }
        });

        tfObservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectAllText(evt);
            }
        });

        jLabel8.setText("Entrega");

        jLabel9.setText("Observación");

        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_add.png"))); // NOI18N
        btnADD.setToolTipText("Agregar entrega al detalle");
        btnADD.setName("add"); // NOI18N
        btnADD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnADDFocusLost(evt);
            }
        });

        btnDEL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px-Crystal_Clear_action_edit_remove.png"))); // NOI18N
        btnDEL.setToolTipText("Eliminar entrega");
        btnDEL.setFocusable(false);
        btnDEL.setName("del"); // NOI18N
        btnDEL.setRequestFocusEnabled(false);

        jLabel21.setText("Facturas");

        cbCtaCtes.setName("cbCtactes"); // NOI18N

        jLabel5.setText("Importe");

        tfImporte.setColumns(8);
        tfImporte.setEditable(false);
        tfImporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfImporte.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfImporte.setText("0");
        tfImporte.setFocusable(false);
        tfImporte.setRequestFocusEnabled(false);

        jLabel6.setText("Pagado");

        tfPagado.setColumns(8);
        tfPagado.setEditable(false);
        tfPagado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfPagado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfPagado.setText("0");
        tfPagado.setFocusable(false);
        tfPagado.setRequestFocusEnabled(false);

        jLabel3.setText("Saldo");

        tfSaldo.setColumns(8);
        tfSaldo.setEditable(false);
        tfSaldo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfSaldo.setText("0");
        tfSaldo.setToolTipText("Saldo restante");
        tfSaldo.setFocusable(false);
        tfSaldo.setRequestFocusEnabled(false);

        checkAcreditarEntrega.setMnemonic('r');
        checkAcreditarEntrega.setText("desacreditar entrega");
        checkAcreditarEntrega.setToolTipText("La entrega será ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbCtaCtes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEntrega, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfImporte, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(checkAcreditarEntrega))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCtaCtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfPagado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAcreditarEntrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tfTotalPorCreditoDebito.setColumns(8);
        tfTotalPorCreditoDebito.setEditable(false);
        tfTotalPorCreditoDebito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfTotalPorCreditoDebito.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTotalPorCreditoDebito.setText("0");
        tfTotalPorCreditoDebito.setFocusable(false);
        tfTotalPorCreditoDebito.setRequestFocusEnabled(false);

        labelPorCreditoDebito.setText("Acreditado");

        tfTOTAL.setColumns(8);
        tfTOTAL.setEditable(false);
        tfTOTAL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfTOTAL.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfTOTAL.setText("0");
        tfTOTAL.setFocusable(false);
        tfTOTAL.setRequestFocusEnabled(false);

        jLabel1.setText("Total pagado");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBox1.setMnemonic('o');
        jCheckBox1.setText("Ocultar Datos");
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jCheckBox1.setRequestFocusEnabled(false);
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("** Desacreditado");

        checkPagoConCheque.setText("Pago con cheque");
        checkPagoConCheque.setToolTipText("Seleccione para relacionar el pago del documento con un Cheque");

        tfRetencion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfRetencion.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfRetencion.setText("0");
        tfRetencion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfRetencionFocusLost(evt);
            }
        });
        tfRetencion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfRetencionKeyTyped(evt);
            }
        });

        labelRetencionPercepcion.setText("Retención");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(checkPagoConCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPorCreditoDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalPorCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRetencionPercepcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTotalEfectivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfTOTAL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfRetencion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAnular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bCancelar)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTotalEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkPagoConCheque))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTotalPorCreditoDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelPorCreditoDebito)
                        .addComponent(tfRetencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelRetencionPercepcion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void selectAllText(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectAllText
       ((JTextField) evt.getSource()).setSelectionStart(0);
   }//GEN-LAST:event_selectAllText

   private void btnADDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnADDFocusLost
       cbCtaCtes.requestFocus();
   }//GEN-LAST:event_btnADDFocusLost

private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
    jPanel1.setVisible(!jCheckBox1.isSelected());
    pack();
}//GEN-LAST:event_jCheckBox1StateChanged

private void tfEntregaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEntregaFocusLost
    try {
        tfEntrega.setText(UTIL.PRECIO_CON_PUNTO.format(Double.valueOf(tfEntrega.getText())));
        tfEntrega.setForeground(Color.BLACK);
    } catch (Exception exception) {
        tfEntrega.setForeground(Color.RED);
    }
}//GEN-LAST:event_tfEntregaFocusLost

    private void tfOctetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfOctetoKeyTyped
        SwingUtil.checkInputDigit(tfOcteto, evt, 8);
    }//GEN-LAST:event_tfOctetoKeyTyped

    private void tfRetencionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfRetencionKeyTyped
        SwingUtil.checkInputDigit(evt, true, 11);
    }//GEN-LAST:event_tfRetencionKeyTyped

    private void tfRetencionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfRetencionFocusLost
        try {
            UTIL.PRECIO_CON_PUNTO.format(Double.valueOf(tfRetencion.getText()));
            tfRetencion.setForeground(Color.BLACK);
        } catch (Exception exception) {
            tfRetencion.setForeground(Color.RED);
        }
    }//GEN-LAST:event_tfRetencionFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bAnular;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnDEL;
    private javax.swing.JButton btnDetalleCreditoDebito;
    private javax.swing.JComboBox cbCaja;
    private javax.swing.JComboBox cbClienteProveedor;
    private javax.swing.JComboBox cbCtaCtes;
    private javax.swing.JComboBox cbSucursal;
    private javax.swing.JCheckBox checkAcreditarEntrega;
    private javax.swing.JCheckBox checkPagoConCheque;
    private com.toedter.calendar.JDateChooser dcFechaCarga;
    private com.toedter.calendar.JDateChooser dcFechaReRe;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelClienteProveedor;
    private javax.swing.JLabel labelCreditoDebito;
    private javax.swing.JLabel labelPorCreditoDebito;
    private javax.swing.JLabel labelReRe;
    private javax.swing.JLabel labelRestanteCreditoDebito;
    private javax.swing.JLabel labelRetencionPercepcion;
    private javax.swing.JTextField tfCreditoDebitoDisponible;
    private javax.swing.JTextField tfCreditoDebitoRestante;
    private javax.swing.JTextField tfCuarto;
    private javax.swing.JTextField tfEntrega;
    private javax.swing.JTextField tfImporte;
    private javax.swing.JTextField tfObservacion;
    private javax.swing.JTextField tfOcteto;
    private javax.swing.JTextField tfPagado;
    private javax.swing.JTextField tfRetencion;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfTOTAL;
    private javax.swing.JTextField tfTotalEfectivo;
    private javax.swing.JTextField tfTotalPorCreditoDebito;
    // End of variables declaration//GEN-END:variables

    /**
     * Setea un mensaje de información.
     *
     * @param msg mensaje.
     * @param titulo (puede tener título o no).
     * @param messageType -1=PLAIN, 0=ERROR, 1=INFO, 2=WARRNING.
     */
    public void showMessage(String msg, String titulo, int messageType) {
        if (messageType >= -1 && messageType <= 2) {
            javax.swing.JOptionPane.showMessageDialog(this, msg, titulo,
                    messageType);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, msg);
        }
    }

    public void addActionListener(Object o) {
        btnADD.addActionListener((ActionListener) o);
        btnDEL.addActionListener((ActionListener) o);
        bCancelar.addActionListener((ActionListener) o);
        bAceptar.addActionListener((ActionListener) o);
        bImprimir.addActionListener((ActionListener) o);
        bAnular.addActionListener((ActionListener) o);
        cbClienteProveedor.addActionListener((ActionListener) o);
        cbCtaCtes.addActionListener((ActionListener) o);
    }

    public void limpiarDetalle() {
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setRowCount(0);
        tfImporte.setText("");
        tfPagado.setText("");
        tfSaldo.setText("");
        tfEntrega.setText("");
        tfObservacion.setText("");
        tfCreditoDebitoRestante.setText("0");
    }

    public void defaultSetFields() {
        dcFechaReRe.setDate(new Date());
        cbSucursal.setSelectedIndex(0);
        cbCaja.setSelectedIndex(0);
        cbClienteProveedor.setSelectedIndex(0);
    }

    // <editor-fold defaultstate="collapsed" desc="GETTERS">
    public JTextField getTfTotalPorCreditoDebito() {
        return tfTotalPorCreditoDebito;
    }

    public JTextField getTfRetencion() {
        return tfRetencion;
    }

    public JTextField getTfTotalEfectivo() {
        return tfTotalEfectivo;
    }

    public JTextField getTfTOTAL() {
        return tfTOTAL;
    }

    public JButton getBtnDetalleCreditoDebito() {
        return btnDetalleCreditoDebito;
    }

    public JTextField getTfCreditoDebitoDisponible() {
        return tfCreditoDebitoDisponible;
    }

    public JTextField getTfCreditoDebitoRestante() {
        return tfCreditoDebitoRestante;
    }

    public JCheckBox getCheckAcreditarEntrega() {
        return checkAcreditarEntrega;
    }

    public JCheckBox getCheckPagoConCheque() {
        return checkPagoConCheque;
    }

    public JComboBox getCbCaja() {
        return cbCaja;
    }

    public JComboBox getCbClienteProveedor() {
        return cbClienteProveedor;
    }

    public JComboBox getCbCtaCtes() {
        return cbCtaCtes;
    }

    public JComboBox getCbSucursal() {
        return cbSucursal;
    }

    public Date getDcFechaReRe() {
        return dcFechaReRe.getDate();
    }

    public Date getDcFechaCarga() {
        return dcFechaCarga.getDate();
    }

    public JLabel getLabelClienteProveedor() {
        return labelClienteProveedor;
    }

    public JLabel getLabelReRe() {
        return labelReRe;
    }

    public String getTfEntrega() {
        return tfEntrega.getText().trim();
    }

    public String getTfObservacion() {
        return tfObservacion.getText().trim();
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public DefaultTableModel getDtm() {
        return (DefaultTableModel) jTable1.getModel();
    }

    public String getTfCuarto() {
        return tfCuarto.getText();
    }

    public String getTfOcteto() {
        return tfOcteto.getText();
    }

    public JButton getbAnular() {
        return bAnular;
    }

    public JButton getBtnADD() {
        return btnADD;
    }

    public JButton getBtnDEL() {
        return btnDEL;
    }

    public JButton getbAceptar() {
        return bAceptar;
    }

    public JButton getbImprimir() {
        return bImprimir;
    }

    public JButton getbCancelar() {
        return bCancelar;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="SETTERS">
    public void setDcFechaReRe(Date dcFecha) {
        this.dcFechaReRe.setDate(dcFecha);
    }

    public void setTfCuarto(String tfCuarto) {
        this.tfCuarto.setText(tfCuarto);
    }

    public void setTfEntrega(String tfEntrega) {
        this.tfEntrega.setText(tfEntrega);
    }

    public void setTfImporte(String tfImporte) {
        this.tfImporte.setText(tfImporte);
    }

    public void setTfObservacion(String tfObservacion) {
        this.tfObservacion.setText(tfObservacion);
    }

    public void setTfOcteto(String tfOcteto) {
        this.tfOcteto.setText(tfOcteto);
    }

    public void setTfPagado(String tfPagado) {
        this.tfPagado.setText(tfPagado);
    }

    public void setTfSaldo(String tfSaldo) {
        this.tfSaldo.setText(tfSaldo);
    }

    public void setDcFechaCarga(Date fechaCarga) {
        dcFechaCarga.setDate(fechaCarga);
    }

    public void getDcFechaReRe(boolean b) {
        dcFechaReRe.setEnabled(b);
    }
    // </editor-fold>

    public void setUIForRecibos() {
        setTitle("Recibos");
        getLabelReRe().setText("Nº Recibo");
        getLabelClienteProveedor().setText("Cliente");
        labelCreditoDebito.setText("Crédito");
        btnDetalleCreditoDebito.setToolTipText("Ver detalle de Crédito");
        labelRestanteCreditoDebito.setText("Crédito restante");
        labelPorCreditoDebito.setText("Por crédito");
        labelRetencionPercepcion.setText("Retención");
    }

    public void setUIForRemesas() {
        setTitle("Remesas");
        getLabelReRe().setText("Nº Remesa");
        getLabelClienteProveedor().setText("Proveedor");
        labelCreditoDebito.setText("Débito");
        btnDetalleCreditoDebito.setToolTipText("Ver detalle de débito");
        labelRestanteCreditoDebito.setText("Débito restante");
        labelPorCreditoDebito.setText("Por débito");
        labelReRe.setVisible(false);
        tfCuarto.setVisible(false);
        tfOcteto.setVisible(false);
        labelRetencionPercepcion.setText("Percepción");
    }

    public void setTfOctetoEditable(boolean b) {
        tfOcteto.setEnabled(true);
        tfOcteto.setEditable(true);
        tfOcteto.setFocusable(true);
        tfOcteto.setRequestFocusEnabled(true);
    }
}
