/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDSystemMessages.java
 *
 * Created on 09/11/2010, 10:05:05
 */

package gui;


/**
 *
 * @author FiruzzZ
 */
public class JDSystemMessages extends javax.swing.JDialog implements Runnable {

    /** Creates new form JDSystemMessages */
    public JDSystemMessages(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextField1 = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setResizable(false);

      jTextField1.setBackground(new java.awt.Color(0, 0, 0));
      jTextField1.setColumns(10);
      jTextField1.setEditable(false);
      jTextField1.setForeground(new java.awt.Color(51, 255, 51));
      jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
      jTextField1.setText("<html>\nporqueriaa..........<p>awñeoifjawñeoifjwaeo\n</html");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField jTextField1;
   // End of variables declaration//GEN-END:variables

   public void agregar(String mensajeParaConcatenar) {
      jTextField1.setText(jTextField1.getText() + "\n" + mensajeParaConcatenar);
   }

   @Override
   public void run() {
      this.setVisible(true);
   }


}
