/*
 * JFP.java
 *
 * Created on 19/11/2009, 15:32:19
 */
package gui;

import controller.*;
import controller.exceptions.DatabaseErrorException;
import controller.exceptions.MessageException;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.*;
import jgestion.Main;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.eclipse.persistence.exceptions.DatabaseException;

/**
 *
 * @author FiruzzzzzZ
 */
public class JFP extends javax.swing.JFrame implements Runnable {

    private static final long serialVersionUID = 777666000L;

    /**
     * Creates new form JFP
     */
    public JFP() {
        loginUser();
        initComponents();
        setAppIcons();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        jMenuItem11.setVisible(false); // Menú -> Datos Generales -> Contribuyente
        this.setTitle(Main.resourceBundle.getString("softwareTitle")
                + " - "
                + Main.resourceBundle.getString("softwareDescription")
                + " V" + Main.resourceBundle.getString("softwareVersion"));
    }

    private void loginUser() {
        if (this.isVisible()) {
            this.setVisible(false);
        }
        new UsuarioController().initLogin(this);
        if (UsuarioController.getCurrentUser() == null) {
            DAO.getEntityManager().close();
            Runtime.getRuntime().exit(0);
        } else {
            if (!activa) {
                // para evitar un doble thread connetion check (cuando hace el 1er login)
                //re activa el Thread de checkeo de conexion
                activa = true;
                new Thread(this, "conexion").start();
            }
            this.setVisible(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        labelConnetionState = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem80 = new javax.swing.JMenuItem();
        jMenuItem81 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem82 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem84 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu26 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem78 = new javax.swing.JMenuItem();
        jMenuItem79 = new javax.swing.JMenuItem();
        jMenuItem69 = new javax.swing.JMenuItem();
        jMenuItem83 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem70 = new javax.swing.JMenuItem();
        jMenuItem85 = new javax.swing.JMenuItem();
        jMenuItem95 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        menuTesoreria = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem66 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem77 = new javax.swing.JMenuItem();
        jMenuItem71 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem88 = new javax.swing.JMenuItem();
        menuCtaCte = new javax.swing.JMenu();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem87 = new javax.swing.JMenuItem();
        jMenuItem90 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jMenuItem63 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        menuIitemCuentas = new javax.swing.JMenuItem();
        menuItemSubCuentas = new javax.swing.JMenuItem();
        jMenuItem68 = new javax.swing.JMenuItem();
        jMenu25 = new javax.swing.JMenu();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem74 = new javax.swing.JMenuItem();
        jMenuItem75 = new javax.swing.JMenuItem();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem91 = new javax.swing.JMenuItem();
        jMenuItem92 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem73 = new javax.swing.JMenuItem();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItemCuentasBancarias = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem67 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem72 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem93 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem94 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem89 = new javax.swing.JMenuItem();
        jMenuItem76 = new javax.swing.JMenuItem();
        jMenuItem86 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItemCatalogoWeb = new javax.swing.JMenuItem();
        jMenuItemOfertas = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(220, 220, 220));

        labelConnetionState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/database_32.png"))); // NOI18N
        labelConnetionState.setToolTipText("Conexión establecida y funcionando");
        labelConnetionState.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelConnetionState.setBounds(820, 390, 32, 32);
        jDesktopPane1.add(labelConnetionState, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/kf.png"))); // NOI18N
        jMenu1.setMnemonic('a');
        jMenu1.setText("Archivo");
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem23.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem23.setText("Cerrar sesión                 ");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem23);

        menuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application-exit.png"))); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_coins.png"))); // NOI18N
        jMenu2.setMnemonic('i');
        jMenu2.setText("Ingresos");
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem2.setText("Facturación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenu23.setText("Recibo");

        jMenuItem14.setText("Alta");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem14);

        jMenuItem80.setText("A Conciliar");
        jMenuItem80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem80ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem80);

        jMenuItem81.setText("Buscar para Conciliar");
        jMenuItem81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem81ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem81);

        jMenu2.add(jMenu23);

        jMenuItem5.setText("Remito");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem47.setText("Nota de Crédito");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem47);

        jMenuItem82.setText("Nota de Débito");
        jMenuItem82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem82ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem82);

        jMenuItem6.setText("Presupuesto                         ");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenu11.setText("Buscar");

        jMenuItem18.setText("Facturas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem18);

        jMenuItem34.setText("Recibos");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem34);

        jMenuItem35.setText("Remitos");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem35);

        jMenuItem48.setText("Notas de Crédito");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem48);

        jMenuItem84.setText("Notas de Débito");
        jMenuItem84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem84ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem84);

        jMenuItem36.setText("Presupuestos");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem36);

        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_invoice.png"))); // NOI18N
        jMenu3.setMnemonic('e');
        jMenu3.setText("Egresos");
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem4.setText("Facturas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu26.setText("Remesas");

        jMenuItem1.setText("Alta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu26.add(jMenuItem1);

        jMenuItem78.setText("A Conciliar");
        jMenuItem78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem78ActionPerformed(evt);
            }
        });
        jMenu26.add(jMenuItem78);

        jMenuItem79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenuItem79.setText("Buscador para Conciliar");
        jMenuItem79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem79ActionPerformed(evt);
            }
        });
        jMenu26.add(jMenuItem79);

        jMenu3.add(jMenu26);

        jMenuItem69.setText("Nota de Crédito");
        jMenuItem69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem69ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem69);

        jMenuItem83.setText("Nota de Débito");
        jMenuItem83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem83ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem83);

        jMenu21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenu21.setText("Buscar");

        jMenuItem28.setText("Facturas");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem28);

        jMenuItem55.setText("Remesas");
        jMenuItem55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem55ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem55);

        jMenuItem70.setText("Notas de Crédito");
        jMenuItem70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem70ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem70);

        jMenuItem85.setText("Notas de Débito");
        jMenuItem85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem85ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem85);

        jMenu3.add(jMenu21);

        jMenuItem95.setText("ABM Dominios");
        jMenuItem95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem95ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem95);

        jMenuBar1.add(jMenu3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_products.png"))); // NOI18N
        jMenu5.setMnemonic('p');
        jMenu5.setText("Productos");
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem7.setText("ABM Productos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);
        jMenu5.add(jSeparator4);

        jMenuItem17.setText("ABM Marcas");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem17);

        jMenuItem12.setText("ABM Rubros");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem27.setText("ABM IVAs");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem27);

        jMenuItem13.setText("ABM Unidades de medición");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem20.setText("ABM Lista de Precios");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem20);
        jMenu5.add(jSeparator5);

        jMenuItem43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenuItem43.setText("Listados");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem43);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agt_family.png"))); // NOI18N
        jMenu6.setMnemonic('l');
        jMenu6.setText("Clientes");
        jMenu6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem8.setText("ABM Cliente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem45.setText("Cliente a Proveedor");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem45);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/agt_family.png"))); // NOI18N
        jMenu7.setMnemonic('v');
        jMenu7.setText("Proveedores");
        jMenu7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem9.setText("ABM Proveedor");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem54.setText("Proveedor a Cliente");
        jMenuItem54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem54ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem54);

        jMenuBar1.add(jMenu7);

        menuTesoreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_change_values.png"))); // NOI18N
        menuTesoreria.setMnemonic('t');
        menuTesoreria.setText("Tesorería");
        menuTesoreria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuTesoreria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/candadito.png"))); // NOI18N
        jMenuItem25.setText("Cierre cajas");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem25);
        menuTesoreria.add(jSeparator3);

        jMenuItem26.setText("Movimientos entre Cajas");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem26);

        jMenuItem32.setText("Movimientos varios");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem32);

        jMenuItem66.setText("Movimientos Bancarios");
        jMenuItem66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem66ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem66);

        jMenu15.setText("Ordenes");

        jMenuItem40.setText("Orden de Entrada/Salida");
        jMenuItem40.setActionCommand("Orden de ....?");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem40);

        jMenuItem41.setText("Buscar..");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem41);

        menuTesoreria.add(jMenu15);
        menuTesoreria.add(jSeparator2);

        jMenu14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenu14.setText("Anular Comprobante..");

        jMenu27.setText("Ingresos");

        jMenuItem3.setText("Facturas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu27.add(jMenuItem3);

        jMenuItem49.setText("Nota de crédito");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        jMenu27.add(jMenuItem49);

        jMenuItem77.setText("Recibo");
        jMenuItem77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem77ActionPerformed(evt);
            }
        });
        jMenu27.add(jMenuItem77);

        jMenuItem71.setText("Remito");
        jMenuItem71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem71ActionPerformed(evt);
            }
        });
        jMenu27.add(jMenuItem71);

        jMenu14.add(jMenu27);

        jMenu28.setText("Egresos");

        jMenuItem38.setText("Facturas");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu28.add(jMenuItem38);

        jMenuItem88.setText("Remesas");
        jMenuItem88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem88ActionPerformed(evt);
            }
        });
        jMenu28.add(jMenuItem88);

        jMenu14.add(jMenu28);

        menuTesoreria.add(jMenu14);

        menuCtaCte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        menuCtaCte.setText("Cta. Cte.");

        jMenuItem37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/appfinder.png"))); // NOI18N
        jMenuItem37.setText("Resumen General");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        menuCtaCte.add(jMenuItem37);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/appfinder.png"))); // NOI18N
        jMenuItem30.setText("Por Cliente");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        menuCtaCte.add(jMenuItem30);

        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/appfinder.png"))); // NOI18N
        jMenuItem31.setText("Por Proveedores");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        menuCtaCte.add(jMenuItem31);

        jMenuItem42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/appfinder.png"))); // NOI18N
        jMenuItem42.setText("Vencimientos");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        menuCtaCte.add(jMenuItem42);

        menuTesoreria.add(menuCtaCte);

        jMenu17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_check.png"))); // NOI18N
        jMenu17.setText("Cheques");

        jMenu19.setText("Propios");

        jMenuItem60.setText("Administrar");
        jMenuItem60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem60ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem60);

        jMenu17.add(jMenu19);

        jMenu20.setText("Terceros");

        jMenuItem56.setText("Administrar");
        jMenuItem56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem56ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem56);

        jMenuItem87.setText("Entregas");
        jMenuItem87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem87ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem87);

        jMenuItem90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenuItem90.setText("Buscar Entregas");
        jMenu20.add(jMenuItem90);

        jMenu17.add(jMenu20);

        menuTesoreria.add(jMenu17);

        jMenu22.setText("Ventas (Numeración manual)");

        jMenuItem57.setText("Facturación");
        jMenuItem57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem57ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem57);

        jMenuItem61.setText("Recibo");
        jMenuItem61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem61ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem61);

        jMenuItem62.setText("Remito");
        jMenuItem62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem62ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem62);

        jMenuItem63.setText("Nota de Crédito");
        jMenu22.add(jMenuItem63);

        menuTesoreria.add(jMenu22);
        menuTesoreria.add(jSeparator6);

        jMenuItem21.setText("ABM Cajas");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem21);

        menuIitemCuentas.setText("ABM Cuentas");
        menuIitemCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIitemCuentasActionPerformed(evt);
            }
        });
        menuTesoreria.add(menuIitemCuentas);

        menuItemSubCuentas.setText("ABM Sub Cuentas");
        menuItemSubCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSubCuentasActionPerformed(evt);
            }
        });
        menuTesoreria.add(menuItemSubCuentas);

        jMenuItem68.setText("ABM Operaciones Bancarias");
        jMenuItem68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem68ActionPerformed(evt);
            }
        });
        menuTesoreria.add(jMenuItem68);

        jMenu25.setText("Asignación de Unidad, Cuenta y Sub Cuenta");

        jMenuItem50.setText("Facturas Venta");
        jMenuItem50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem50ActionPerformed(evt);
            }
        });
        jMenu25.add(jMenuItem50);

        jMenuItem74.setText("Facturas Compra");
        jMenuItem74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem74ActionPerformed(evt);
            }
        });
        jMenu25.add(jMenuItem74);

        jMenuItem75.setText("Movimientos Varios");
        jMenuItem75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem75ActionPerformed(evt);
            }
        });
        jMenu25.add(jMenuItem75);

        menuTesoreria.add(jMenu25);

        jMenu29.setText("Conciliacion Bancaria");

        jMenuItem91.setText("Conciliar");
        jMenuItem91.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem91ActionPerformed(evt);
            }
        });
        jMenu29.add(jMenuItem91);

        jMenuItem92.setText("Buscar");
        jMenu29.add(jMenuItem92);

        menuTesoreria.add(jMenu29);

        jMenuBar1.add(menuTesoreria);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/home.png"))); // NOI18N
        jMenu9.setMnemonic('d');
        jMenu9.setText("Datos Generales");
        jMenu9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem22.setText("Datos de la empresa");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem22);

        jMenuItem19.setText("Sucursales (Puntos de Venta)");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem19);

        jMenuItem73.setText("Unidades de Negocio");
        jMenuItem73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem73ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem73);

        jMenuItem64.setText("Vendedores");
        jMenuItem64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem64ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem64);

        jMenuItem11.setText("Contribuyentes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11);
        jMenu9.add(jSeparator1);

        jMenuItem10.setText("Departamentos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenuItem15.setText("Municipios");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem15);

        jMenu18.setText("Bancos/Cuentas Bancarias");

        jMenuItem58.setText("Bancos");
        jMenuItem58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem58ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem58);

        jMenuItem59.setText("Sucursales Bancarias");
        jMenuItem59.setEnabled(false);
        jMenuItem59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem59ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem59);

        jMenuItemCuentasBancarias.setText("Cuentas Bancarias");
        jMenuItemCuentasBancarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCuentasBancariasActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItemCuentasBancarias);

        jMenu9.add(jMenu18);

        jMenuBar1.add(jMenu9);

        jMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/32px_view_detail.png"))); // NOI18N
        jMenuReportes.setMnemonic('r');
        jMenuReportes.setText("Informes");
        jMenuReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenu24.setText("Comprobantes..");

        jMenuItem67.setText("de Compras");
        jMenuItem67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem67ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem67);

        jMenuItem29.setText("de Ventas");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem29);

        jMenuReportes.add(jMenu24);

        jMenuItem39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa-simple.png"))); // NOI18N
        jMenuItem39.setText("Movimientos de Productos");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem39);

        jMenuItem72.setText("Movimientos generales");
        jMenuItem72.setEnabled(false);
        jMenuItem72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem72ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem72);

        jMenuItem46.setText("Facturas Compra/Venta");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem46);

        jMenuItem93.setText("Detalle Facturación");
        jMenuItem93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem93ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem93);

        jMenu8.setText("Flujo de fondos");

        jMenuItem44.setText("de Movimientos de Cajas");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem44);

        jMenuItem94.setText("de Ventas");
        jMenuItem94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem94ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem94);

        jMenuReportes.add(jMenu8);

        jMenu12.setText("Resultados");

        jMenuItem89.setText("Informe de Resultados");
        jMenuItem89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem89ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem89);

        jMenuItem76.setText("Informe de Resultados v2");
        jMenuItem76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem76ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem76);

        jMenuReportes.add(jMenu12);

        jMenuItem86.setText("Productos (Costo/Venta)");
        jMenuItem86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem86ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem86);

        jMenuBar1.add(jMenuReportes);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/edit_user.png"))); // NOI18N
        jMenu4.setMnemonic('u');
        jMenu4.setText("Usuarios");
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem16.setText("ABM Usuarios");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem16);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/candadito.png"))); // NOI18N
        jMenuItem24.setText("Cambiar contraseña");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem24);

        jMenuItem65.setText("Registro de acciones de usuarios");
        jMenuItem65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem65ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem65);

        jMenuBar1.add(jMenu4);

        jMenu13.setText("Ayuda");

        jMenuItem33.setText("Sobre..");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem33);

        jMenuBar1.add(jMenu13);

        jMenu10.setMnemonic('w');
        jMenu10.setText("WEB");

        jMenuItemCatalogoWeb.setText("Catálogo Web");
        jMenuItemCatalogoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCatalogoWebActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemCatalogoWeb);

        jMenuItemOfertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/16px_star_offer.png"))); // NOI18N
        jMenuItemOfertas.setText("ABM Ofertas");
        jMenuItemOfertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOfertasActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItemOfertas);

        jMenuBar1.add(jMenu10);

        jMenu16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gnome-panel-force-quit.png"))); // NOI18N
        jMenu16.setText("WS-AFIP");
        jMenu16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem53.setText("Certificación");
        jMenuItem53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem53ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem53);

        jMenuItem51.setText("Facturación Electrónica (FE)");
        jMenuItem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem51ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem51);

        jMenuItem52.setText("Preexistente");
        jMenu16.add(jMenuItem52);

        jMenuBar1.add(jMenu16);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            new ProductoController().initContenedor(this, true, false);
        } catch (DatabaseErrorException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR CRÍTICO", JOptionPane.ERROR_MESSAGE);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            JDialog jd = new ProveedorController().initContenedor(this, true);
            jd.setLocationRelativeTo(this);
            jd.setVisible(true);
            refreshConnectionDB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(this.getClass()).log(Level.ERROR, null, ex);
        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            new FacturaCompraController().initABMFacturaCompra(this, true);
        } catch (MessageException ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    //Datos Gral -> Ubicación
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new DepartamentoController().initContenedor(this, true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    //Rubro->Proveedores
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        try {
            JDialog jd = new RubroController().getABM(this);
            jd.setLocationRelativeTo(this);
            jd.setVisible(true);
            refreshConnectionDB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    //Rubro->Productos..    //Rubros->Clientes
    //abm unidades de medida
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try {
            new UnidadmedidaJpaController().initABM(this, true);
            refreshConnectionDB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(this.getName()).log(Level.ERROR, null, ex);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        try {
            new MarcaController().getABM(this, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new SucursalController().initContenedor(this, true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new ContribuyenteController().initABM(this, true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        new MunicipioController().initContenedor(this, true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new ClienteController().initContenedor(this, true).setVisible(true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        new ListaPreciosController().initContenedor(this, true);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            new FacturaVentaController().initFacturaVenta(this, true, null, 1, true, true);
        } catch (MessageException ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        try {
            JDialog jd = new CajaController().initABM(this, true);
            jd.setLocationRelativeTo(this);
            jd.setVisible(true);
            refreshConnectionDB();
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        try {
            new DatosEmpresaJpaController().initJD(this, true);
            refreshConnectionDB();
        } catch (Exception ex) {
            Logger.getLogger(JFP.class.getName()).log(Level.ERROR, null, ex);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        new UsuarioController().initCambiarPass(this);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            new RemesaController().initRemesa(this, true, true);
        } catch (Exception ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        if (cajaMovimientoController == null) {
            cajaMovimientoController = new CajaMovimientosController();
        }
        cajaMovimientoController.initCierreCaja(this, false);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try {
            new ReciboController().initRecibos(this, true, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        try {
            new CajaMovimientosController().initCajaToCaja(this, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        try {
            new IvaController().initABM(this, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.out.println("login OFF.........");
        cerrandoAplicacion();
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        try {
            new FacturaCompraController().initBuscador(this, false, false);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        try {
            new UsuarioController().initContenedor(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("formWindowClosing .....");
        cerrandoAplicacion();
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        try {
            new CajaMovimientosController().getABMMovimientosVarios(this, true).setVisible(true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        activa = false;
        UsuarioController.cerrarSessionActual();
        loginUser();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        try {
            new CtacteClienteController().getResumenCtaCte(this, false).setVisible(true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        try {
            new PresupuestoController().initPresupuesto(this, false, true, true);
        } catch (Exception ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            new RemitoController().initRemito(this, false, true, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        try {
            new FacturaVentaController().initBuscador(this, false, false);
        } catch (Exception ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        try {
            new PresupuestoController().initBuscador(this);
        } catch (Exception ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        new ReciboController().showBuscador(this, false, false);
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        try {
            new RemitoController().showBuscador(this, false, true);
        } catch (Exception ex) {
            showError(ex.getMessage());
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        try {
            new CtacteProveedorController().getResumenCtaCte(this, false).setVisible(true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            new FacturaVentaController().initBuscador(this, false, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        new ProductoController().initMovimientoProducto(this, false);
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        try {
            new FacturaCompraController().initBuscador(this, false, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        new JDAbout(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        try {
            new OrdenJpaController().initOrden(this, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        try {
            new OrdenJpaController().initBuscador(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        new ProductoController().initListadoProducto(this);
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        try {
            new CtacteClienteController().initCheckVencimientos((JFrame) this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        try {
            new Contabilidad().initMovimientosCajasUI(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        try {
            new Contabilidad().initBalanceCompraVentaUI(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, 2);
        }
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItemOfertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOfertasActionPerformed
        try {
            new ProductosWebJpaController().initOfertasUI((JFrame) this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, 2);
        }
    }//GEN-LAST:event_jMenuItemOfertasActionPerformed

    private void jMenuItemCatalogoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCatalogoWebActionPerformed
        try {
            new ProductosWebJpaController().initCatalogoGUI((JFrame) this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", 2);
        }
    }//GEN-LAST:event_jMenuItemCatalogoWebActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        try {
            new NotaCreditoController().initComprobanteUI(this, Boolean.TRUE, true, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", 2);
        }
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        try {
            new NotaCreditoController().initBuscador(this, false);
        } catch (MessageException ex) {
            showError(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        try {
            new NotaCreditoController().initBuscador(this, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void menuIitemCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIitemCuentasActionPerformed
        new CuentaController().initContenedor((JFrame) this);
    }//GEN-LAST:event_menuIitemCuentasActionPerformed

    private void jMenuItem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem51ActionPerformed
        try {
            JDialog initFE = new AFIPWSController().initFE((JFrame) this);
            initFE.setLocationRelativeTo(this);
            initFE.setVisible(true);
            //        } catch (ParserConfigurationException ex) {
            //            java.util.logging.Logger.getLogger(JFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            //        } catch (SAXException ex) {
            //            java.util.logging.Logger.getLogger(JFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            //        } catch (IOException ex) {
            //            java.util.logging.Logger.getLogger(JFP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de conexión con AFIP Web Service", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(JFP.class).error(ex, ex);
        }
    }//GEN-LAST:event_jMenuItem51ActionPerformed

    private void jMenuItem53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem53ActionPerformed
        JDialog initWSAA = AFIPWSController.initWSAA((JFrame) this);
        initWSAA.setLocationRelativeTo(this);
        initWSAA.setVisible(true);
    }//GEN-LAST:event_jMenuItem53ActionPerformed

private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
    new ClienteController().initClienteToProveedor((JFrame) this).setVisible(true);
}//GEN-LAST:event_jMenuItem45ActionPerformed

private void jMenuItem54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem54ActionPerformed
    new ProveedorController().initProveedorToCliente((JFrame) this).setVisible(true);
}//GEN-LAST:event_jMenuItem54ActionPerformed

private void jMenuItem58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem58ActionPerformed
    try {
        new BancoController().initContenedor(this, true, false).setVisible(true);
    } catch (DatabaseErrorException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
        Logger.getLogger(JFP.class.getName()).error(ex);
    }
}//GEN-LAST:event_jMenuItem58ActionPerformed

private void jMenuItem59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem59ActionPerformed
    try {
        new BancoSucursalController().initContenedor(this, true, false).setVisible(true);
    } catch (DatabaseErrorException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}//GEN-LAST:event_jMenuItem59ActionPerformed

private void jMenuItem60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem60ActionPerformed
    try {
        new ChequePropioController().getManager(this).setVisible(true);
    } catch (MessageException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_jMenuItem60ActionPerformed

private void jMenuItem56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem56ActionPerformed
    try {
        new ChequeTercerosController().getManager(this).setVisible(true);
    } catch (MessageException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
    }
}//GEN-LAST:event_jMenuItem56ActionPerformed

    private void jMenuItem55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem55ActionPerformed
        try {
            new RemesaController().showBuscador(this, true, false);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem55ActionPerformed

    private void jMenuItem57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem57ActionPerformed
        try {
            new FacturaVentaController().unlockedABM(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem57ActionPerformed

    private void jMenuItem62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem62ActionPerformed
        try {
            new RemitoController().unlockedABM(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem62ActionPerformed

    private void jMenuItem61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem61ActionPerformed
        try {
            new ReciboController().initRecibosNumeracionManual(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
        refreshConnectionDB();
    }//GEN-LAST:event_jMenuItem61ActionPerformed

    private void jMenuItem67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem67ActionPerformed
        try {
            new Contabilidad().displayInformeComprobantesCompra(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem67ActionPerformed

    private void jMenuItemCuentasBancariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCuentasBancariasActionPerformed
        try {
            JDialog jd = new CuentabancariaController().initContenedor(this);
            jd.setLocationRelativeTo(this);
            jd.setVisible(true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemCuentasBancariasActionPerformed

    private void jMenuItem66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem66ActionPerformed
        JDialog jd = new CuentabancariaMovimientosController().getManager(this);
        jd.setLocationRelativeTo(this);
        jd.setVisible(true);
    }//GEN-LAST:event_jMenuItem66ActionPerformed

    private void jMenuItem68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem68ActionPerformed
        try {
            new OperacionesBancariasController().initUIABM((Window) this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem68ActionPerformed

    private void jMenuItem69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem69ActionPerformed
        try {
            new NotaCreditoProveedorController().initABM(this, true);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", 2);
        }
    }//GEN-LAST:event_jMenuItem69ActionPerformed

    private void jMenuItem70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem70ActionPerformed
        try {
            new NotaCreditoProveedorController().initBuscador(this, true, false);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", 2);
        }

    }//GEN-LAST:event_jMenuItem70ActionPerformed

    private void jMenuItem71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem71ActionPerformed
        try {
            new RemitoController().initBuscadorToAnular(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Advertencia", 2);
        }
    }//GEN-LAST:event_jMenuItem71ActionPerformed

    private void jMenuItem72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem72ActionPerformed
        new Contabilidad().displayMovimientosGenerales(this);
    }//GEN-LAST:event_jMenuItem72ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        try {
            new Contabilidad().displayInformeComprobantesVenta(this);
        } catch (MessageException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        new Contabilidad().displayCtaCteGeneralResumen((Window) this);
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem73ActionPerformed
        new UnidadDeNegocioController().initContenedor(this, true, false);
    }//GEN-LAST:event_jMenuItem73ActionPerformed

    private void menuItemSubCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSubCuentasActionPerformed
        new SubCuentaController().initContenedor(this);
    }//GEN-LAST:event_menuItemSubCuentasActionPerformed

    private void jMenuItem50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem50ActionPerformed
        new FacturaVentaController().asignador();
    }//GEN-LAST:event_jMenuItem50ActionPerformed

    private void jMenuItem65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem65ActionPerformed
        new UsuarioController().showTracker();
    }//GEN-LAST:event_jMenuItem65ActionPerformed

    private void jMenuItem74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem74ActionPerformed
        new FacturaCompraController().asignador();
    }//GEN-LAST:event_jMenuItem74ActionPerformed

    private void jMenuItem75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem75ActionPerformed
        new CajaMovimientosController().asignador();
    }//GEN-LAST:event_jMenuItem75ActionPerformed

    private void jMenuItem76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem76ActionPerformed
        new Contabilidad().showInformePorUnidadesDeNegocios(this);
    }//GEN-LAST:event_jMenuItem76ActionPerformed

    private void jMenuItem77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem77ActionPerformed
        new ReciboController().showBuscador(this, false, true);
    }//GEN-LAST:event_jMenuItem77ActionPerformed

    private void jMenuItem78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem78ActionPerformed
        try {
            new RemesaController().initRemesaAConciliar(this);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem78ActionPerformed

    private void jMenuItem64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem64ActionPerformed
        new VendedorController().initContenedor(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem64ActionPerformed

    private void jMenuItem84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem84ActionPerformed
        try {
            new NotaDebitoController().initBuscador(this, true, false);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem84ActionPerformed

    private void jMenuItem82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem82ActionPerformed
        new NotaDebitoController().initContenedor(this, true);
    }//GEN-LAST:event_jMenuItem82ActionPerformed

    private void jMenuItem86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem86ActionPerformed
        new Contabilidad().displayProductosCostoVenta(this);
    }//GEN-LAST:event_jMenuItem86ActionPerformed

    private void jMenuItem87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem87ActionPerformed
        new ChequeTercerosController().showEntregas(this);
    }//GEN-LAST:event_jMenuItem87ActionPerformed

    private void jMenuItem83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem83ActionPerformed
        try {
            new NotaDebitoProveedorController().initContenedor(this, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem83ActionPerformed

    private void jMenuItem85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem85ActionPerformed
        try {
            new NotaDebitoProveedorController().initBuscador(this, false, false);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem85ActionPerformed

    private void jMenuItem88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem88ActionPerformed
        try {
            new RemesaController().showBuscador(null, false, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem88ActionPerformed

    private void jMenuItem89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem89ActionPerformed
        new Contabilidad().showInformeResultados(this);
    }//GEN-LAST:event_jMenuItem89ActionPerformed

    private void jMenuItem80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem80ActionPerformed
        try {
            new ReciboController().initReciboAConciliar(this);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem80ActionPerformed

    private void jMenuItem81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem81ActionPerformed
        new ReciboController().showBuscadorToConciliar(this);
    }//GEN-LAST:event_jMenuItem81ActionPerformed

    private void jMenuItem91ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem91ActionPerformed
        new CuentabancariaMovimientosController().getConciliacion(this).setVisible(true);
    }//GEN-LAST:event_jMenuItem91ActionPerformed

    private void jMenuItem79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem79ActionPerformed
        try {
            new RemesaController().showBuscadorToConciliar(this);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem79ActionPerformed

    private void jMenuItem93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem93ActionPerformed
        new Contabilidad().displayInformeDetalleFacturacion((Window)this);
    }//GEN-LAST:event_jMenuItem93ActionPerformed

    private void jMenuItem94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem94ActionPerformed
        new Contabilidad().displayFlujoPorVentas((Window)this);
    }//GEN-LAST:event_jMenuItem94ActionPerformed

    private void jMenuItem95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem95ActionPerformed
        try {
            new DominioController().getABM(this, true);
        } catch (MessageException ex) {
            ex.displayMessage(this);
        }
    }//GEN-LAST:event_jMenuItem95ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem66;
    private javax.swing.JMenuItem jMenuItem67;
    private javax.swing.JMenuItem jMenuItem68;
    private javax.swing.JMenuItem jMenuItem69;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem70;
    private javax.swing.JMenuItem jMenuItem71;
    private javax.swing.JMenuItem jMenuItem72;
    private javax.swing.JMenuItem jMenuItem73;
    private javax.swing.JMenuItem jMenuItem74;
    private javax.swing.JMenuItem jMenuItem75;
    private javax.swing.JMenuItem jMenuItem76;
    private javax.swing.JMenuItem jMenuItem77;
    private javax.swing.JMenuItem jMenuItem78;
    private javax.swing.JMenuItem jMenuItem79;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem80;
    private javax.swing.JMenuItem jMenuItem81;
    private javax.swing.JMenuItem jMenuItem82;
    private javax.swing.JMenuItem jMenuItem83;
    private javax.swing.JMenuItem jMenuItem84;
    private javax.swing.JMenuItem jMenuItem85;
    private javax.swing.JMenuItem jMenuItem86;
    private javax.swing.JMenuItem jMenuItem87;
    private javax.swing.JMenuItem jMenuItem88;
    private javax.swing.JMenuItem jMenuItem89;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem90;
    private javax.swing.JMenuItem jMenuItem91;
    private javax.swing.JMenuItem jMenuItem92;
    private javax.swing.JMenuItem jMenuItem93;
    private javax.swing.JMenuItem jMenuItem94;
    private javax.swing.JMenuItem jMenuItem95;
    private javax.swing.JMenuItem jMenuItemCatalogoWeb;
    private javax.swing.JMenuItem jMenuItemCuentasBancarias;
    private javax.swing.JMenuItem jMenuItemOfertas;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel labelConnetionState;
    private javax.swing.JMenu menuCtaCte;
    private javax.swing.JMenuItem menuIitemCuentas;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemSubCuentas;
    private javax.swing.JMenu menuTesoreria;
    // End of variables declaration//GEN-END:variables
    private boolean activa = true;
    private CajaMovimientosController cajaMovimientoController;

    private void refreshConnectionDB() {
        DAO.getEntityManager().clear();
    }

    private void cerrandoAplicacion() {
        System.out.println("cerrandoAplicacion");
        activa = false;
        dispose();
//        Runtime.getRuntime().exit(0);
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    @Override
    @SuppressWarnings("SleepWhileInLoop")
    public void run() {
        System.out.println("Connectivity Thread begining..");
        EntityManager em = null;
        while (activa) {
            if (UsuarioController.getCurrentUser() != null) {
                try {
                    em = DAO.getEntityManager();
                    em.createNativeQuery("SELECT * FROM usuario WHERE id = " + UsuarioController.getCurrentUser().getId()).getSingleResult();
                    if (labelConnetionState.getText().length() > 0) {
                        labelConnetionState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/database_32.png"))); // NOI18N
                        labelConnetionState.setToolTipText("Conexión establecida y funcionando");
                        labelConnetionState.setText("");
                    }
                } catch (DatabaseException e) {
                    labelConnetionState.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/database_close_32.png"))); // NOI18N
                    labelConnetionState.setToolTipText("¡ERROR DE CONEXIÓN!");
                    labelConnetionState.setText("¡ERROR DE CONEXIÓN!");
                    labelConnetionState.setForeground(Color.RED);
                    Logger.getLogger(this.getClass()).log(Level.ERROR, e);
                } catch (Exception e) {
                    labelConnetionState.setEnabled(false);
                    labelConnetionState.setText("¡ERROR DE CONEXIÓN!");
                    labelConnetionState.setForeground(Color.RED);
                    labelConnetionState.setToolTipText("¡ERROR DE CONEXIÓN!");
                    Logger
                            .getLogger(JFP.class).log(Level.ERROR, "Error en Thread de Chequeo de conexión con DB", e);
                    activa = false;
                } finally {
                    try {
                        em.close();
                        em = null;
                        Thread.sleep(3000);


                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFP.class
                                .getName()).log(Level.ERROR, null, ex);
                        JOptionPane.showMessageDialog(
                                this, "Sucedió un error en el hilo de conexión, para asegurar un correcto funcionamiento del sistema, cierre y vuelva a abrirlo");
                    }
                }
            }
        }
        System.out.println("Connectivity Thread finished..");
    }

    private void setAppIcons() {
        List<Image> iconsList = new ArrayList<Image>(3);
        iconsList.add(Toolkit.getDefaultToolkit().createImage(getClass().getResource(Main.resourceBundle.getString("softwareIcon"))));
        iconsList.add(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/iconos/16px_sum.ico")));
        iconsList.add(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/iconos/24px_sum.ico")));
        iconsList.add(Toolkit.getDefaultToolkit().createImage(getClass().getResource("/iconos/32px_sum.ico")));
        this.setIconImages(iconsList);
    }
}
