
/*
 * PanelMovimientosVarios.java
 *
 * Created on 05/05/2010, 11:25:50
 */
package gui;

import entity.UTIL;
import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 *
 * @author FiruzzZ
 */
public class PanelMovimientosVarios extends javax.swing.JPanel {

   /** Creates new form PanelMovimientosVarios */
   public PanelMovimientosVarios() {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      bBuscar = new javax.swing.JButton();
      radioIngreso = new javax.swing.JRadioButton();
      radioEgreso = new javax.swing.JRadioButton();
      cbCaja = new javax.swing.JComboBox();
      jLabel15 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      tfMontoMovimiento = new javax.swing.JTextField();
      jLabel9 = new javax.swing.JLabel();
      tfDescripcion = new javax.swing.JTextField();
      jSeparator1 = new javax.swing.JSeparator();

      bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lupa.png"))); // NOI18N
      bBuscar.setText("Buscar");
      bBuscar.setToolTipText("Buscar comprobante");
      bBuscar.setName("buscar"); // NOI18N

      radioIngreso.setSelected(true);
      radioIngreso.setText("Ingreso");
      radioIngreso.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioIngresoActionPerformed(evt);
         }
      });

      radioEgreso.setText("Egreso");
      radioEgreso.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioEgresoActionPerformed(evt);
         }
      });

      cbCaja.setName("cajaOrigen"); // NOI18N

      jLabel15.setText("Caja");

      jLabel8.setText("Monto");

      tfMontoMovimiento.setColumns(7);
      tfMontoMovimiento.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      tfMontoMovimiento.setToolTipText("Monto ($)");
      tfMontoMovimiento.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfMontoMovimientoFocusGained(evt);
         }
         public void focusLost(java.awt.event.FocusEvent evt) {
            tfMontoMovimientoFocusLost(evt);
         }
      });

      jLabel9.setText("Descripción");

      tfDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            tfDescripcionFocusGained(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel9)
                     .addComponent(jLabel8))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(tfMontoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                     .addComponent(jLabel15)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGap(18, 18, 18)
                     .addComponent(radioIngreso)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(radioEgreso))
                  .addComponent(bBuscar)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel15)
                     .addComponent(cbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(tfMontoMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel8)))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(radioIngreso)
                  .addComponent(radioEgreso)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(12, Short.MAX_VALUE))
      );
   }// </editor-fold>//GEN-END:initComponents

    private void tfMontoMovimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMontoMovimientoFocusLost
       try {
          tfMontoMovimiento.setText(UTIL.PRECIO_CON_PUNTO.format(Double.valueOf(tfMontoMovimiento.getText())));
       } catch (NumberFormatException ex) {
       }
}//GEN-LAST:event_tfMontoMovimientoFocusLost

    private void radioIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIngresoActionPerformed
       radioEgreso.setSelected(!radioIngreso.isSelected());
    }//GEN-LAST:event_radioIngresoActionPerformed

    private void radioEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEgresoActionPerformed
       radioIngreso.setSelected(!radioEgreso.isSelected());
    }//GEN-LAST:event_radioEgresoActionPerformed

    private void tfMontoMovimientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMontoMovimientoFocusGained
      tfMontoMovimiento.setSelectionStart(0);
    }//GEN-LAST:event_tfMontoMovimientoFocusGained

    private void tfDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDescripcionFocusGained
      tfDescripcion.setSelectionStart(0);
    }//GEN-LAST:event_tfDescripcionFocusGained

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bBuscar;
   private javax.swing.JComboBox cbCaja;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JRadioButton radioEgreso;
   private javax.swing.JRadioButton radioIngreso;
   private javax.swing.JTextField tfDescripcion;
   private javax.swing.JTextField tfMontoMovimiento;
   // End of variables declaration//GEN-END:variables

   public void setListener(Object o) {
      bBuscar.addActionListener((ActionListener) o);
   }

   public JComboBox getCbCaja() {
      return cbCaja;
   }

   public boolean isIngreso() {
      return radioIngreso.isSelected();
   }

   public String getTfDescripcion() {
      return tfDescripcion.getText().trim();
   }

   public String getTfMontoMovimiento() {
      return tfMontoMovimiento.getText().trim();
   }

   public void setTfMonto(String monto) {
      tfMontoMovimiento.setText(monto);
   }

   public void setTfDescripcion(String descripcion) {
      tfDescripcion.setText(descripcion);
   }
}
